import type { LocalText } from './engineeringData'
import type { PartId } from './data'

export type SubassemblyFact = {
  position: LocalText
  role: LocalText
  principle: LocalText
  plain: LocalText
}

const l = (zh: string, en: string): LocalText => ({ zh, en })
const fact = (positionZh: string, positionEn: string, roleZh: string, roleEn: string, principleZh: string, principleEn: string, plainZh: string, plainEn: string): SubassemblyFact => ({
  position: l(positionZh, positionEn),
  role: l(roleZh, roleEn),
  principle: l(principleZh, principleEn),
  plain: l(plainZh, plainEn),
})

export type SubassemblyFacts = [SubassemblyFact, SubassemblyFact, SubassemblyFact, SubassemblyFact, SubassemblyFact, SubassemblyFact]

export const COMPONENT_FACTS: Record<PartId, SubassemblyFacts> = {
  'front-wing': [
    fact('横跨车鼻前方、最接近地面的主承载翼面。', 'The primary load-carrying surface spanning the nose close to the road.', '建立前翼的基础下压力，并决定进入后续翼片与车轮区域的来流方向。', 'Creates the base front load and sets the inflow for the flap and wheel region.', '上下表面压力差沿翼面积分形成下压力；离地高度会改变地面效应和失速边界。', 'Integrated pressure difference creates downforce; ride height changes ground effect and stall margin.', '它像一把倒扣的空气铲，先把气流转向，再把反作用力传给前轴。', 'It behaves like an inverted air shovel that turns flow and sends the reaction into the front axle.'),
    fact('位于主翼片后上方，沿翼展布置并可改变安装角。', 'Mounted aft and above the main plane with an adjustable angle.', '通过改变总弯度快速调节前轴下压力和整车气动平衡。', 'Adjusts front load and whole-car aero balance by changing total camber.', '缝翼组合让气流在更大转角下仍能附着，但角度过大会增加阻力并诱发分离。', 'The slotted assembly sustains attached flow at greater turning, but excess angle adds drag and separation.', '它相当于前翼的“音量旋钮”，小幅转动就能明显改变前轴抓地。', 'It is the front wing volume knob: a small adjustment noticeably changes front grip.'),
    fact('竖立在翼片左右端部，靠近前轮内侧。', 'Vertical plates at both wing tips near the inner faces of the front tyres.', '限制高低压气流横向串流，并管理翼尖涡与前轮尾流。', 'Limits spanwise pressure leakage and manages tip vortices and tyre wake.', '端板通过边界约束改变涡结构；其形状同时影响有效翼展、阻力和下游流场。', 'Boundary control changes vortex structure, effective span, drag and downstream flow.', '它像翼片两端的挡板，防止空气从高压侧轻易绕到低压侧。', 'It acts like a fence at each tip, stopping air from easily spilling from high to low pressure.'),
    fact('存在于主翼片后缘与襟翼前缘之间，沿翼展形成连续缝隙。', 'The continuous gap between the main-plane trailing edge and flap leading edge.', '把高能气流送往襟翼吸力面，扩大可用迎角和工作窗口。', 'Feeds energetic flow to the flap suction side, extending usable angle and operating range.', '缝隙尺寸和重叠量决定射流方向与动量；过小会堵塞，过大则泄漏并增阻。', 'Gap and overlap set jet direction and momentum; too small chokes, too large leaks and adds drag.', '它像给边界层开的呼吸缝，让快空气去扶住快要脱落的慢空气。', 'It is a breathing slot that sends fast air to support the slow boundary layer before it detaches.'),
    fact('连接翼片、车鼻与前隔板，调节孔位通常位于端部或支架处。', 'Links the wing to the nose and front bulkhead, with adjusters at the tips or mounts.', '传递气动力并保证设定角度在振动、碰撞路肩和高速载荷下不漂移。', 'Transfers aero load and preserves angle under vibration, kerb strikes and high-speed loading.', '支架刚度、连接预紧和间隙共同决定动态变形；柔度会把静态设定变成另一套装车角。', 'Mount stiffness, preload and play govern dynamic deflection; compliance changes the installed angle.', '它既是骨架也是铰链：既要扛住力，又要让工程师可重复地调角度。', 'It is both skeleton and hinge: strong enough for load, precise enough for repeatable adjustment.'),
    fact('小孔与翼面齐平，通常分布在弦向关键位置并通过细管连接扫描阀。', 'Flush holes placed at chordwise stations and connected to a pressure scanner by small tubes.', '测量局部静压，用来重建压力分布、识别分离并校核 CFD。', 'Measures local static pressure to rebuild pressure distribution, detect separation and correlate CFD.', '孔口几何、管路长度、泄漏和动态响应都会影响读数，必须做零点与频响校核。', 'Port geometry, tube length, leakage and dynamics affect readings and require zero and response checks.', '它像贴在翼面上的听诊器，不看气流本身，而是听它留下的压力脉搏。', 'It is a stethoscope on the wing, reading the pressure pulse left by otherwise invisible flow.'),
  ],
  'rear-wing': [
    fact('横跨车尾上方、位于后轴之后的主要翼面。', 'The main spanwise surface above and behind the rear axle.', '提供后轴高速下压力，并构成尾翼整体气动载荷的基准。', 'Provides high-speed rear load and the baseline for the rear-wing assembly.', '装车来流受驾驶舱、车身和轮胎尾流影响，因此实际压力分布不同于孤立翼型。', 'Installed flow is distorted by cockpit, body and tyre wakes, so pressure differs from isolated airfoil data.', '它像车尾的一只倒扣机翼，在高速时把后轮更牢地压向地面。', 'It is an inverted wing at the tail, pressing the rear tyres harder into the road as speed rises.'),
    fact('位于主翼后上方，可通过孔位或偏心件改变迎角。', 'Mounted aft and above the main plane with angle adjustment by holes or eccentrics.', '细调后轴载荷、阻力和前后气动平衡。', 'Fine-tunes rear load, drag and front-to-rear aero balance.', '提高襟翼角度通常增加环量和压力差，直到分离使增益下降。', 'More flap angle generally raises circulation and pressure difference until separation erodes the gain.', '它是尾翼的调节旋钮：转得越大不一定越快，因为直线阻力也在增加。', 'It is the rear-wing control knob; more is not always faster because straight-line drag rises too.'),
    fact('安装在尾翼左右两侧，连接多个翼片端部。', 'Mounted at both sides, joining the ends of the wing elements.', '抑制翼尖泄漏、支撑翼片并限定多段翼的相对位置。', 'Suppresses tip leakage, supports the elements and fixes their relative geometry.', '端板改变翼尖涡强度和诱导阻力，同时承受面外弯曲与连接载荷。', 'It changes tip-vortex strength and induced drag while carrying out-of-plane bending and joint loads.', '它既像空气围栏，也像把几层书夹在一起的书挡。', 'It is both an aerodynamic fence and a bookend holding the wing stack together.'),
    fact('形成于翼展末端、端板外缘和后缘附近的三维流动区域。', 'A three-dimensional flow region near the span ends, endplate edges and trailing edge.', '显示高低压泄漏和诱导损失，是效率、稳定性与后方尾流的重要来源。', 'Reveals pressure leakage and induced loss, affecting efficiency, stability and downstream wake.', '压力梯度卷起旋涡；涡核位置和强度随迎角、偏航与端板几何变化。', 'Pressure gradients roll into vortices whose position and strength vary with angle, yaw and endplate geometry.', '它像水里桨尖卷出的涡，只是发生在空气中，肉眼看不见却会消耗能量。', 'It resembles the vortex from a paddle tip in water, invisible in air but still consuming energy.'),
    fact('从变速箱、后防滚架或车架伸向主翼下表面。', 'Runs from gearbox, rear structure or chassis to the underside of the main plane.', '把尾翼下压力传入车架，并控制翼面在高速下的挠度与振动。', 'Transfers downforce into the chassis and controls high-speed wing deflection and vibration.', '支架截面和连接边界决定弯曲、扭转与固有频率；挠度会改变有效迎角。', 'Section and joints set bending, torsion and natural frequency; deflection changes effective incidence.', '它像尾翼的腿，既要轻，又不能在高速气流里发软或抖动。', 'It is the wing leg: light, but unable to flex or shake excessively in high-speed flow.'),
    fact('布置在翼片与端板或支架连接处，通常是一组离散孔位。', 'Located at element-to-endplate or element-to-pylon joints as discrete holes.', '让赛道工程师可重复地选择迎角，并保证左右设定一致。', 'Lets engineers select repeatable incidence and keep left-right settings matched.', '孔距决定调节分辨率，紧固预紧和定位面决定角度重复性与抗滑移能力。', 'Hole pitch sets adjustment resolution; preload and datums set repeatability and slip resistance.', '它像机械式刻度盘，每个孔位都是一档可验证的气动设定。', 'It is a mechanical dial where each hole is a verifiable aero setting.'),
  ],
  floor: [
    fact('位于前轮后方、底板受控流道的最前端。', 'At the leading edge of the controlled underfloor passage behind the front wheels.', '接收并整理由前翼与车轮带来的来流，为后续低压通道建立质量流量。', 'Receives front-wing and wheel flow and establishes mass flow into the low-pressure tunnels.', '入口唇口、离地高度和边界层厚度决定流量；过低可能堵塞并引发载荷崩塌。', 'Lip geometry, ride height and boundary-layer thickness set flow; too low can choke and collapse load.', '它像吸尘器的吸口，入口条件不好，后面再大的流道也吸不动。', 'It is the vacuum-cleaner inlet: poor entry flow starves everything downstream.'),
    fact('沿车底纵向延伸，位于车架两侧或中央的收缩流道。', 'Longitudinal contracting passages beneath or beside the chassis.', '加速底部气流、降低静压并产生底板主要下压力。', 'Accelerates underbody flow, lowers static pressure and creates most floor load.', '连续方程、压力梯度和粘性边界层共同控制速度；几何突变会增加损失。', 'Continuity, pressure gradient and viscous boundary layer jointly set speed; abrupt geometry adds loss.', '它像一条越来越窄的河道，水流会加快；这里只是流体换成了空气。', 'It is like a narrowing river channel where flow speeds up, except the fluid is air.'),
    fact('沿底板外缘、靠近地面和旋转轮胎尾流的位置。', 'Along the floor edges near the road and rotating-tyre wake.', '阻止外部高压空气侵入低压底板，维持有效压差。', 'Prevents high-pressure ambient air from entering the low-pressure floor.', '边缘涡相当于非接触式气封；偏航、侧倾或轮胎尾流可使涡脱离并泄压。', 'Edge vortices act as a contactless seal; yaw, roll or tyre wake can detach them and leak pressure.', '它像没有橡胶条的空气密封圈，用旋转气流守住低压区。', 'It is an air gasket with no rubber, using rotating flow to protect the low-pressure region.'),
    fact('位于底板后段，流道高度逐渐增加并通向车尾。', 'At the rear of the floor where passage height expands toward the tail.', '让高速低压气流平稳减速并恢复压力，同时帮助抽吸前方流道。', 'Decelerates low-pressure high-speed flow smoothly, recovers pressure and helps draw the upstream tunnel.', '扩张角过大或入口边界层能量不足会分离，导致压力恢复和下压力同时下降。', 'Too much expansion or weak inlet boundary layer causes separation, reducing recovery and load.', '它像把高速出口逐渐放大的喇叭，张得太快，气流就会脱离壁面。', 'It is a gradually opening horn; open it too quickly and flow peels away from the wall.'),
    fact('竖立在扩散器与通道内部，沿流向布置。', 'Vertical fences running through the tunnels and diffuser.', '控制横向迁移、隔离轮胎尾流并稳定局部流动。', 'Controls crossflow, isolates tyre wake and stabilises local flow.', '分流片引导涡量与边界层，但也增加湿面积和干扰阻力，位置必须与流线匹配。', 'Strakes guide vorticity and boundary layers but add wetted area and interference drag.', '它像河道里的导流墙，把容易乱窜的流体送进各自通道。', 'It is a guide wall in a channel, keeping wandering flow in its intended lane.'),
    fact('位于扩散器最后缘和车尾自由流交汇处。', 'Where the diffuser trailing edge meets the free stream behind the car.', '完成压力恢复并决定尾流动量、基底压力与扩散器抽吸能力。', 'Completes pressure recovery and sets wake momentum, base pressure and diffuser pumping.', '出口面积、后方阻塞和尾翼耦合改变回压；回压过高会把分离向前推。', 'Exit area, blockage and rear-wing coupling alter back pressure; excess back pressure moves separation forward.', '它像排风口，出口是否顺畅会反过来决定整条流道能吸多少空气。', 'It is an exhaust outlet whose freedom determines how much the whole passage can draw.'),
  ],
  nose: [
    fact('覆盖吸能盒并形成车头外形，位于前翼与前隔板之间。', 'Covers the attenuator and shapes the nose between front wing and front bulkhead.', '整理由前翼上方经过的气流，并保护内部吸能结构与传感器。', 'Conditions flow over the front wing region and protects the attenuator and sensors.', '外壳通常不承担主要碰撞能量，必须避免阻碍吸能盒按设计压溃。', 'The fairing normally carries little crash energy and must not obstruct designed crushing.', '它像吸能结构外面的整流罩，负责空气与外观，不应抢走安全结构的工作。', 'It is the aerodynamic cover around the crash structure, responsible for flow rather than crash work.'),
    fact('位于车头最前方、紧贴防侵入板之前；规则要求的基础体积至少为高 100 mm、宽 200 mm、向前延伸 200 mm。', 'At the foremost structural point ahead of the anti-intrusion plate; the rules define at least a 100 mm high, 200 mm wide volume extending 200 mm forward.', '通过受控压溃吸收正面碰撞动能并限制平均与峰值减速度。', 'Absorbs frontal impact energy by controlled crushing and limits mean and peak deceleration.', 'Formula Student 2026 基准试验为 300 kg、7 m/s，要求吸收不少于 7350 J，平均减速度不超过 20 g、峰值不超过 40 g。', 'The Formula Student 2026 baseline test uses 300 kg at 7 m/s and requires at least 7,350 J with no more than 20 g average and 40 g peak deceleration.', '它像赛车前端的一次性缓冲区，用可控变形换取驾驶舱不变形。', 'It is a sacrificial crumple buffer that deforms so the cockpit does not.'),
    fact('夹在吸能盒与前隔板之间，覆盖前隔板开口。', 'Between the attenuator and front bulkhead, covering the bulkhead face.', '阻止吸能材料或尖锐部件侵入驾驶舱，并把碰撞载荷扩散到主结构。', 'Stops penetrators and distributes crash load into the primary structure.', '规则基准为 1.5 mm 实心钢板或 4.0 mm 实心铝板；替代方案必须通过等效试验验证。', 'The rule baseline is 1.5 mm solid steel or 4.0 mm solid aluminium; alternatives require equivalent physical validation.', '它像盾牌，把前方压溃产生的力摊开，不让硬物直接顶进车架。', 'It is a shield that spreads crush load and blocks hard objects from entering the chassis.'),
    fact('围绕防侵入板后方，连接前隔板、单体壳或管架。', 'Around the rear of the anti-intrusion plate, joining it to the front bulkhead and chassis.', '建立碰撞、制动和前悬架载荷进入主结构的连续路径。', 'Creates a continuous path for crash, braking and front-suspension loads into the chassis.', '螺栓、胶接或焊缝必须传递轴向、剪切和偏心力矩，连接柔度会放大局部应力。', 'Bolts, bonds or welds carry axial, shear and eccentric moments; joint compliance magnifies local stress.', '它像接力棒交接区，前端收下的力必须在这里完整交给车架。', 'It is the hand-off zone where loads received at the nose pass safely into the chassis.'),
    fact('位于鼻锥外侧或前隔板附近，与前翼支架相连。', 'On the nose sides or near the front bulkhead where wing supports attach.', '确定前翼位置与姿态，并把气动力和路肩冲击载荷传入车架。', 'Locates the front wing and transfers aero and kerb-strike loads into the chassis.', '硬点位置决定力臂；插入件、局部铺层和紧固预紧控制承载与疲劳。', 'Hardpoint location sets moment arms; inserts, local laminate and preload control strength and fatigue.', '它是前翼与安全车架之间的“插座”，位置要准，周围也要足够结实。', 'It is the socket between wing and safety structure: accurately located and locally reinforced.'),
    fact('布置在吸能芯体前端、折线、孔列或预压区域。', 'Placed at the crush-core front, folds, holes or pre-crushed zones.', '降低初始峰值并让压溃沿预定顺序稳定传播。', 'Reduces the initial force spike and starts progressive collapse in a designed sequence.', '局部削弱先触发屈曲或胞元塌陷，之后稳定平台载荷完成主要吸能。', 'Local weakening initiates buckling or cell collapse before the plateau absorbs most energy.', '它像易拉罐上先压出的折痕，告诉结构从哪里开始、按什么顺序变形。', 'It is like a pre-creased can, telling the structure where and how to begin collapsing.'),
  ],
  monocoque: [
    fact('构成单体壳内外表层，包围驾驶舱与主要载荷路径。', 'Forms the inner and outer faces surrounding the cockpit and primary load paths.', '承担面内拉压、剪切和弯曲表面应力，并保护夹芯。', 'Carries in-plane tension, compression, shear and bending face stress while protecting the core.', '纤维方向决定各向刚度与强度；铺层必须围绕载荷路径、开孔和冲击要求设计。', 'Fibre direction sets directional stiffness and strength; layup follows load paths, cut-outs and impact needs.', '它像夹芯板的两层硬皮，薄却承担大部分拉伸和压缩。', 'It is the hard skin of a sandwich panel, thin but carrying most tension and compression.'),
    fact('夹在内外碳纤维面板之间，覆盖大面积壳体区域。', 'Sandwiched between carbon skins over large shell areas.', '拉开两层面板以提高截面惯性，同时传递面外剪切。', 'Separates the skins to raise section inertia while transferring through-thickness shear.', '蜂窝或泡沫以极小质量增加厚度；局部压溃、脱粘和吸湿是关键失效模式。', 'Honeycomb or foam adds depth at low mass; crushing, debonding and moisture are key failures.', '它像纸板箱中间的瓦楞层，让两张薄皮相隔更远，整块板就更难弯。', 'It is the corrugated middle of cardboard, spacing thin skins apart so the panel resists bending.'),
    fact('横向封闭车架前后端，并与地板、侧壁和上部结构相交。', 'Transverse closures at the front and rear connecting floor, sidewalls and upper shell.', '闭合扭转载荷路径、支撑悬架或动力系统并分散集中载荷。', 'Closes torsional load paths, supports suspension or powertrain and spreads concentrated loads.', '隔板通过面内剪切工作；开孔、边缘连接和局部嵌件会决定实际刚度。', 'Bulkheads work mainly in in-plane shear; apertures, edge joints and inserts govern real stiffness.', '它像盒子里的横隔板，既保持外壳形状，也给重要部件一个坚实落脚点。', 'It is a transverse wall in a box, preserving shape and giving major systems a firm base.'),
    fact('埋入壳体局部，位于控制臂、弹簧阻尼器或副车架连接点。', 'Embedded locally where arms, dampers or subframes attach.', '把螺栓集中载荷扩散到大面积复合材料，防止面板压溃和剥离。', 'Spreads bolt loads into the laminate and prevents local crushing and peel.', '金属嵌件、填充芯和局部补强铺层共同形成三维载荷扩散区。', 'Metal inserts, core fill and local plies form a three-dimensional load-spreading zone.', '它像在薄墙里预埋的承重底座，让螺栓不是只拽住一小片碳纤维。', 'It is a load-bearing anchor in a thin wall, preventing a bolt from pulling on a tiny patch of carbon.'),
    fact('沿驾驶舱两侧、位于车手髋部与外部碰撞区之间。', 'Along both cockpit sides between the driver and external impact zone.', '抵抗侧向侵入、分配侧碰载荷并保护驾驶员生存空间。', 'Resists side intrusion, distributes side-impact load and protects survival space.', '连续面板与上下边界形成梁/壳组合；冲击性能依赖铺层、芯材和连接连续性。', 'The panel and its upper/lower boundaries act as a beam-shell system; impact depends on layup, core and joints.', '它像驾驶员两侧的装甲门槛，首要任务不是轻，而是守住空间。', 'It is an armoured sill beside the driver, prioritising preservation of space.'),
    fact('分布在面板搭接、隔板周边、嵌件和可拆盖板位置。', 'Distributed at panel overlaps, bulkhead edges, inserts and removable covers.', '把独立零件连接成连续壳体，并在检查或维修处提供可拆接口。', 'Joins separate parts into a continuous shell and provides removable service interfaces.', '胶接适合均匀传递剪切，机械紧固提供定位与保险；剥离、表面处理和预紧需受控。', 'Bonding distributes shear; fasteners locate and retain; peel, surface preparation and preload must be controlled.', '它像把拼图真正变成一块结构的接缝，接缝不好，再好的面板也无法协同工作。', 'It is the seam that turns panels into one structure; poor seams prevent good panels from working together.'),
  ],
  halo: [
    fact('位于驾驶员头部后方，是车辆最高的主要防滚构件。', 'Behind the driver head as the highest primary rollover member.', '在翻滚中保持生存空间，并把顶部与后向载荷传入车架。', 'Preserves survival space in a rollover and transfers top and rearward loads into the chassis.', '封闭截面与支撑共同抵抗弯曲和侧向屈曲；几何必须覆盖驾驶员头盔包络。', 'Closed section and braces resist bending and lateral buckling; geometry must cover the helmet envelope.', '它像驾驶员后方的安全拱门，赛车倒扣时先替头部撑住地面。', 'It is the safety arch behind the driver, holding the ground away from the helmet if the car overturns.'),
    fact('位于方向盘前方、驾驶舱开口前缘附近。', 'Ahead of the steering wheel near the front edge of the cockpit opening.', '与主防滚架共同定义保护线，并承受前方斜向冲击载荷。', 'Works with the main hoop to define the protection line and carry forward oblique loads.', '前后防滚结构之间的切线必须越过头盔和方向盘，保证硬物先接触结构。', 'The line between front and main structures must clear helmet and steering wheel so objects meet structure first.', '它是安全拱门的前支点，和后方主拱一起搭出驾驶员上方的保护屋顶。', 'It is the forward support of the safety arch, forming a protective roof line with the main hoop.'),
    fact('从主防滚架向后下方连接至车架或后部结构。', 'Runs rearward and downward from the main hoop into the chassis or rear structure.', '限制防滚架向前后或侧向倒伏，并建立稳定三角形载荷路径。', 'Prevents the hoop folding fore-aft or sideways and creates triangulated load paths.', '斜撑把弯矩转化为轴向拉压；节点位置和夹角决定效率与屈曲裕量。', 'Bracing converts bending into axial force; node location and angle set efficiency and buckling margin.', '它像帐篷的拉绳，让高高的防滚架不只靠根部硬撑。', 'It acts like a tent guy-line, stopping the tall hoop relying only on its base.'),
    fact('由防滚架、头盔、头枕和规则定义的空间边界共同形成。', 'The protected volume defined by roll structures, helmet, restraint and rules.', '保证不同身材驾驶员在正常坐姿和约束条件下都不会越出安全线。', 'Ensures drivers of different sizes remain inside the safety line when seated and restrained.', '设计使用人体模板、头盔位置和结构切线校核；座椅或安全带变化会改变包络。', 'Design checks templates, helmet position and structural tangents; seat or harness changes alter the envelope.', '它不是一个实体零件，而是一块必须永远保持空出的“安全空气”。', 'It is not a solid part but a volume of safety air that must always remain clear.'),
    fact('头枕贴近头盔后方，座椅承托骨盆、背部和大腿。', 'The head restraint sits close behind the helmet while the seat supports pelvis, back and thighs.', '在加速、制动和碰撞中控制人体运动并把载荷分散到可承受部位。', 'Controls body motion and spreads acceleration and crash loads into tolerable regions.', '刚度、泡沫吸能、间隙和人体姿态共同决定颈部运动与压力分布。', 'Stiffness, energy-absorbing foam, clearance and posture govern neck motion and pressure distribution.', '它像为驾驶员定制的模具，既固定身体，也避免冲击只落在一个小点上。', 'It is a driver-shaped cradle that locates the body and avoids concentrating impact at one point.'),
    fact('位于骨盆两侧、肩部后方和座椅底部的强化结构节点。', 'Reinforced structural nodes beside the pelvis, behind the shoulders and below the seat.', '固定多点式安全带，并按正确方向把人体约束载荷传入车架。', 'Anchors the multi-point harness and transfers restraint loads into the chassis in the intended directions.', '带路角度、节点强度和安装间距决定约束效果；错误角度会增加脊柱或肩部载荷。', 'Belt angles, node strength and spacing govern restraint; poor angles increase spinal or shoulder load.', '它是安全带真正抓住赛车的地方，织带再强也必须有可靠的结构锚点。', 'It is where the harness truly grips the car; strong webbing still needs reliable structural anchors.'),
  ],
  tires: [
    fact('构成轮胎与赛道接触的最外层光滑橡胶。', 'The smooth outer rubber layer contacting the track.', '产生纵向和横向力，并通过胶料温度窗口提供可重复抓地。', 'Generates longitudinal and lateral force within a repeatable compound temperature window.', '粘弹性、真实接触面积和微观路面嵌合作用产生摩擦；过冷、过热或磨损都会改变性能。', 'Viscoelasticity, real contact area and road asperity interlock create friction; temperature and wear change it.', '它是赛车唯一真正抓住地面的手掌，四个接地斑加起来也不大。', 'It is the only palm gripping the road, and the four contact patches are surprisingly small.'),
    fact('隐藏在胎面下方，由帘布层、带束层和侧壁骨架构成。', 'Hidden beneath the tread as carcass plies, belts and sidewall structure.', '保持轮胎形状、控制接地斑变形并传递轮辋与胎面之间的载荷。', 'Maintains shape, controls contact-patch deformation and transfers load between rim and tread.', '帘线角度与带束刚度决定径向、侧向和扭转柔度，从而影响侧偏刚度与瞬态响应。', 'Cord angle and belt stiffness set radial, lateral and torsional compliance, affecting cornering stiffness and response.', '它像橡胶外衣里的骨架，让轮胎可以变形，却不会像气球一样失去方向。', 'It is the skeleton inside the rubber, allowing useful deformation without behaving like a balloon.'),
    fact('位于轮胎内径两侧，紧扣轮辋胎圈座。', 'At both inner edges, locked onto the rim bead seats.', '密封气压、定位轮胎并传递驱动、制动和侧向剪切力。', 'Seals pressure, locates the tyre and transfers drive, braking and lateral shear.', '高强钢丝或纤维束承受周向拉力；座面几何与装配润滑影响防滑和气密。', 'High-strength wire or fibre carries hoop tension; seat geometry and fitting control slip and sealing.', '它像绷紧的锁环，把柔软轮胎牢牢扣在刚性轮辋上。', 'It is a tensioned lock ring securing the flexible tyre to the rigid rim.'),
    fact('由气密内衬包围，位于胎体与轮辋之间。', 'The sealed volume bounded by the liner, carcass and rim.', '保存充气压力，提供主要径向弹性并影响温度、刚度和滚动半径。', 'Stores inflation pressure, provides radial springing and affects temperature, stiffness and rolling radius.', '气体状态随温度变化；泄漏、含水量和热传递会使热态压力偏离冷态设定。', 'Gas state changes with temperature; leakage, moisture and heat transfer shift hot pressure from cold setting.', '它像一个可调空气弹簧，几十分之一 bar 的变化就可能改变轮胎工作状态。', 'It is an adjustable air spring where a few tenths of a bar can change tyre behaviour.'),
    fact('位于轮胎中心，与轮毂、轴承和制动盘相连。', 'At the tyre centre, connected to hub, bearings and brake disc.', '支撑胎圈、保持气密并把轮端力矩传入悬架和传动系统。', 'Supports the beads, seals the air and transfers wheel torque into suspension and driveline.', '轮辋宽度与轮廓改变侧壁姿态和接地斑；质量直接属于非簧载和旋转质量。', 'Rim width and contour change sidewall shape and contact patch; mass is both unsprung and rotating.', '它像轮胎的刚性骨盆，尺寸不对，橡胶再好也站不稳。', 'It is the rigid pelvis of the tyre; wrong dimensions prevent even good rubber working properly.'),
    fact('温度测量覆盖胎面内中外，压力传感位于气门或轮内。', 'Temperature sensing spans inner, middle and outer tread; pressure sensing sits at valve or inside wheel.', '监控工作窗口、泄漏与左右差异，为外倾、前束和压力调校提供证据。', 'Monitors operating window, leaks and side-to-side differences for camber, toe and pressure setup.', '红外、热电偶和压力传感器具有不同带宽与测量深度，采样时机必须一致。', 'Infrared, thermocouple and pressure sensors differ in bandwidth and depth; timing must be consistent.', '它像轮胎的体温计和血压计，告诉工程师抓地变化到底来自哪里。', 'It is the tyre thermometer and blood-pressure monitor, revealing why grip changes during a run.'),
  ],
  brakes: [
    fact('安装在驾驶员脚下，平衡杆横跨前后两个主缸推杆；Formula Student 规则要求踏板及安装结构承受 2 kN 而不失效。', 'At the driver feet with a balance bar spanning both master-cylinder pushrods; Formula Student rules require the pedal and mount to withstand 2 kN without failure.', '把脚力放大并可机械分配前后回路压力。', 'Multiplies pedal force and mechanically distributes it between front and rear circuits.', '踏板比决定力与行程交换；平衡杆支点偏置改变两个主缸的受力比例。', 'Pedal ratio trades force for travel; balance-bar pivot offset changes force split between cylinders.', '它像一个可调跷跷板，把同一只脚的力按比例分给前后制动。', 'It is an adjustable seesaw dividing one foot force between front and rear brakes.'),
    fact('并排连接在踏板盒内，分别服务前、后独立液压回路。', 'Mounted side by side in the pedal box, serving independent front and rear hydraulic circuits.', '把机械推力转化为液压，并在单回路失效时保留另一回路制动能力。', 'Converts pushrod force into pressure and preserves braking on one circuit if the other fails.', '活塞面积决定压力与排液量；密封、补偿孔和储液罐保证回位与补液。', 'Piston area sets pressure and displacement; seals, compensation ports and reservoirs enable return and replenishment.', '它们像两支独立注射器，即使一支漏了，另一支仍能推动部分车轮制动。', 'They are two independent syringes, so one leak still leaves the other braking part of the car.'),
    fact('从主缸沿车架通向四个轮端，避开热源、运动件与碰撞区。', 'Runs from master cylinders along the chassis to four corners, away from heat, motion and impact zones.', '把压力低损失地传到卡钳，并在高温振动下保持密封。', 'Carries pressure to calipers with low loss while remaining sealed under heat and vibration.', '制动液近似不可压缩；软管膨胀、气泡和沸腾会把踏板行程变成无效压缩。', 'Brake fluid is nearly incompressible; hose expansion, gas and boiling turn pedal travel into lost compression.', '它像液压力的神经和血管，任何气泡都会让清晰踏板变得发软。', 'It is the hydraulic nerve and vessel; any gas bubble makes a crisp pedal feel soft.'),
    fact('固定在转向节或立柱上，跨越制动盘两侧。', 'Fixed to the upright and straddling both sides of the disc.', '用活塞把制动片夹向制动盘，将液压变成切向摩擦力。', 'Uses pistons to clamp pads onto the disc, turning pressure into tangential friction.', '卡钳刚度、活塞面积和回退量决定压力分布、踏板感觉与拖滞。', 'Caliper stiffness, piston area and rollback set pressure distribution, pedal feel and drag.', '它像一只液压虎钳，夹得越均匀，制动力越可控。', 'It is a hydraulic vice; more even clamping gives more controllable braking.'),
    fact('与轮毂同轴旋转，摩擦环通过钟形座连接轮毂。', 'Rotates coaxially with the hub, with the friction ring joined to a bell.', '提供摩擦半径与热容量，把车辆动能转化并暂存在热量中。', 'Provides friction radius and thermal capacity, converting vehicle kinetic energy into heat.', '盘径、厚度、材料和浮动连接控制制动矩、温升、热膨胀与锥形变形。', 'Diameter, thickness, material and floating joint govern torque, temperature rise, expansion and coning.', '它像高速旋转的热电池，每次刹车都把速度临时存成高温。', 'It is a spinning thermal battery, temporarily storing speed as heat during every stop.'),
    fact('制动片位于卡钳内，风道从车体开口把空气引向盘面或盘帽。', 'Pads sit in the caliper while ducts guide air from body openings to disc faces or bell.', '制动片提供稳定摩擦，风道带走热量并控制盘、片和卡钳温度。', 'Pads provide stable friction while ducts remove heat and control disc, pad and caliper temperatures.', '摩擦材料系数随温度变化；对流换热取决于流量、通道和旋转盘内部通风。', 'Friction coefficient varies with temperature; convective cooling depends on flow, ducts and disc ventilation.', '制动片是橡皮擦，风道是散热风扇；一个负责生热，一个负责把热带走。', 'The pad is the eraser and the duct the cooling fan: one creates heat, the other removes it.'),
  ],
  'front-suspension': [
    fact('以两个三角形连杆连接车架硬点与前轮转向节；Formula Student 2026 要求前后悬架均可用，轮跳行程至少 50 mm、驾驶员就座时压缩行程至少 25 mm。', 'Two triangular links connect chassis hardpoints to the front upright; Formula Student 2026 requires operational front and rear suspension with at least 50 mm usable travel and 25 mm jounce with the driver seated.', '约束轮心运动并控制外倾、主销和轮距随跳动的变化。', 'Constrains wheel-centre motion and controls camber, kingpin and track change through travel.', '控制臂长度与硬点决定瞬心和运动学；杆件主要承受轴向拉压以减轻质量。', 'Arm lengths and hardpoints define instant centres and kinematics; members carry mainly axial load.', '它像两只上下布置的手臂，允许车轮上下走，却限制它乱跑。', 'It is a pair of upper and lower arms, allowing vertical travel while preventing unwanted motion.'),
    fact('位于车轮中心，连接控制臂、转向拉杆、轮毂轴承与卡钳。', 'At the wheel centre, joining arms, tie rod, hub bearing and caliper.', '汇集轮胎六分力并让轮毂低摩擦旋转。', 'Collects tyre forces and moments while allowing the hub to rotate with low friction.', '转向节刚度维持几何，轴承预紧和跨距控制挠度、温升与寿命。', 'Upright stiffness preserves geometry; bearing preload and span control deflection, heat and life.', '它是轮端的关节和骨盆，几乎所有悬架、转向与制动力都在这里会合。', 'It is the wheel-corner joint where suspension, steering and brake loads meet.'),
    fact('从轮端或下控制臂斜向连接到车内摇臂。', 'An inclined link from the wheel or lower arm to an inboard rocker.', '把车轮垂向运动传入车内弹簧阻尼器，并设定运动比。', 'Transmits wheel travel to the inboard spring-damper and sets motion ratio.', '杆件轴向位移驱动摇臂旋转；安装角和连接点决定轮率与载荷放大。', 'Axial link motion rotates the rocker; angle and pickup point set wheel rate and force ratio.', '它像一根传力推杆，把轮端的上下动作送到车内更安全、更整洁的位置。', 'It is a transfer rod carrying wheel motion to a protected inboard location.'),
    fact('安装在车架内部，摇臂连接推杆、弹簧阻尼器与防倾杆。', 'Mounted inboard, with the rocker joining pushrod, spring-damper and anti-roll bar.', '把运动方向重新分配，并用弹簧承重、阻尼器控制振荡。', 'Redirects motion, supports load with the spring and controls oscillation with the damper.', '摇臂杠杆比塑造非线性轮率；阻尼阀根据活塞速度耗散振动能量。', 'Rocker leverage shapes wheel-rate progression; damper valves dissipate energy according to piston speed.', '摇臂像钟摆转换方向，弹簧托住车身，阻尼器负责让它不要反复弹跳。', 'The rocker redirects motion, the spring supports the car, and the damper stops repeated bouncing.'),
    fact('横跨左右悬架，通过摇臂或连杆连接两侧。', 'Spans left and right suspension through rockers or drop links.', '在左右轮反向运动时增加侧倾刚度，而对同向起伏影响较小。', 'Adds roll stiffness when wheels move oppositely with less effect in heave.', '扭杆角变形产生恢复力矩；臂长、杆径和材料决定可调刚度。', 'Torsional twist creates restoring moment; arm length, diameter and material set stiffness.', '它像连接左右悬架的扭簧，转弯时帮车身少歪，过直坎时尽量不插手。', 'It is a torsion spring linking both sides, resisting cornering roll while mostly ignoring common bumps.'),
    fact('球铰位于杆件端部，硬点分布在车架和转向节连接位置。', 'Rod ends sit at member ends, with hardpoints on chassis and upright.', '允许所需转角、精确定位几何，并把载荷传入结构。', 'Allows articulation, locates geometry precisely and transfers load into the structure.', '球面轴承消除弯曲约束，但间隙、错位和安装双剪条件决定精度与疲劳。', 'Spherical bearings avoid bending constraint, while play, misalignment and double shear govern precision and fatigue.', '它们像骨骼之间的关节和关节窝，小小的位置误差就会改变整套运动学。', 'They are the joints and sockets of the suspension; small location errors alter the whole kinematic system.'),
  ],
  'rear-suspension': [
    fact('以两层三角控制臂连接车架与后立柱。', 'Upper and lower triangular arms link the chassis to the rear upright.', '限定后轮外倾、前束和轮心轨迹，并承受驱动与侧向载荷。', 'Defines rear camber, toe and wheel path while carrying drive and lateral loads.', '硬点几何决定瞬心、侧倾中心和外倾增益；杆件尽量以轴向载荷工作。', 'Hardpoint geometry sets instant centres, roll centre and camber gain; members work mainly axially.', '它像后轮的双层导轨，让车轮能跳动，却始终保持工程师设计的姿态。', 'It is a two-level guide keeping the rear wheel on its designed attitude through travel.'),
    fact('位于后轮中心，同时连接控制臂、轮毂轴承、卡钳和半轴。', 'At the rear wheel centre, joining arms, hub bearings, caliper and half-shaft.', '汇集轮胎、制动和驱动载荷，并保持轮毂与半轴正确同轴。', 'Collects tyre, brake and drive loads while maintaining hub and shaft alignment.', '高刚度限制动态外倾与前束误差；轴承跨距和壳体热变形影响寿命。', 'High stiffness limits dynamic camber and toe error; bearing span and thermal distortion affect life.', '它是后轮端的交通枢纽，悬架、制动和动力都在这里交叉。', 'It is the rear-corner junction where suspension, braking and power paths cross.'),
    fact('连杆从轮端通向车内摇臂，摇臂靠近弹簧和防倾杆。', 'A rod runs from the wheel to an inboard rocker near the spring and anti-roll bar.', '把轮跳转化为摇臂旋转，并按设定运动比驱动弹性元件。', 'Turns wheel travel into rocker rotation and drives elastic elements at the chosen motion ratio.', '连接点半径和角度可形成递增或递减轮率；几何必须避免过中心。', 'Pickup radius and angle can create rising or falling wheel rate and must avoid over-centre geometry.', '它像机械传动中的曲柄，把不方便放置的轮端运动搬到车内。', 'It behaves like a crank relocating awkward wheel motion into the chassis.'),
    fact('沿车身纵向或横向布置在后舱内部，与摇臂相连。', 'Mounted longitudinally or transversely inside the rear bay and linked to the rocker.', '弹簧支撑静载与气动载荷，阻尼器控制轮跳、俯仰和牵引瞬态。', 'The spring supports static and aero load; the damper controls wheel hop, pitch and traction transients.', '弹簧刚度和运动比决定轮率，压缩与回弹阻尼阀分别管理能量流。', 'Spring rate and motion ratio set wheel rate; bump and rebound valves manage energy flow separately.', '弹簧决定车身愿意动多少，阻尼器决定它以多快速度动。', 'The spring decides how far the car wants to move; the damper decides how fast.'),
    fact('横跨后部左右悬架，连接两个摇臂或下控制臂。', 'Spans the rear suspension and connects both rockers or lower arms.', '分配后轴侧倾刚度，直接影响入弯、稳态平衡和出弯牵引。', 'Allocates rear roll stiffness and affects turn-in, steady balance and exit traction.', '扭杆只在左右相对位移时显著变形；调节臂孔位改变有效杠杆。', 'The torsion bar twists mainly under differential wheel motion; blade or arm position changes leverage.', '它像后轴的平衡旋钮，太硬会让内侧后轮更容易失去载荷。', 'It is a rear-axle balance knob; too stiff can unload the inside rear tyre.'),
    fact('从差速器输出法兰伸向左右后轮，等速节位于两端。', 'Runs from differential output flanges to both rear wheels with CV joints at each end.', '在悬架跳动和角度变化时持续传递驱动扭矩。', 'Continues transmitting drive torque as suspension travel changes shaft angle and length.', '等速节通过滚道或三叉结构补偿角度和滑移；工作角越大，损失和温度通常越高。', 'CV geometry accommodates angle and plunge; larger working angle generally raises loss and temperature.', '它像会弯曲的传动轴，后轮上下跳时仍把电机扭矩送到轮胎。', 'It is a flexible drive shaft carrying motor torque while the rear wheel moves.'),
  ],
  steering: [
    fact('位于驾驶员手前，通过快拆花键连接转向柱。', 'In front of the driver, attached to the column through a splined quick release.', '接收转向输入、承载开关和显示，并允许紧急撤离时快速拆除。', 'Receives steering input, carries controls and display, and removes quickly for egress.', '轮缘直径决定手力与转角范围；快拆必须无间隙定位并有可靠锁止。', 'Rim diameter sets hand effort and angular range; the quick release must locate without play and lock positively.', '它是驾驶员与前轮之间的手柄，快拆则像一只只能在正确位置锁上的插头。', 'It is the driver handle to the front wheels; the quick release is a plug that locks only when correctly seated.'),
    fact('从方向盘向前延伸，使用一个或多个万向节绕开驾驶舱结构。', 'Runs forward from the wheel with one or more universal joints around cockpit structure.', '把转角和扭矩传给小齿轮，同时适应包装和碰撞安全要求。', 'Transmits angle and torque to the pinion while meeting packaging and crash-safety needs.', '万向节夹角会引入非匀速误差；相位、支承和防脱设计决定手感与可靠性。', 'Joint angle can create velocity non-uniformity; phasing, support and retention govern feel and reliability.', '它像一根带关节的长骨头，能绕开障碍但不能松、卡或脱落。', 'It is a long articulated bone that routes around obstacles without looseness, bind or separation.'),
    fact('固定在前隔板附近，小齿轮与横向齿条啮合。', 'Fixed near the front bulkhead with a pinion meshing to a transverse rack.', '把方向盘旋转转换为左右拉杆的直线位移。', 'Converts steering-wheel rotation into lateral tie-rod motion.', '齿数、模数和小齿轮半径决定转向比；啮合预紧控制回差和摩擦。', 'Tooth count, module and pinion radius set ratio; mesh preload controls backlash and friction.', '它像把拧动门把手变成推拉门闩的机构，把旋转变成直线。', 'It is the mechanism that turns a rotating handle into a sliding bolt.'),
    fact('从齿条两端连接到左右转向节。', 'Runs from each rack end to the left and right uprights.', '把齿条位移传给车轮，并与控制臂几何共同控制跳动转向。', 'Transfers rack travel to the wheels and works with arm geometry to control bump steer.', '内外球铰位置决定阿克曼与前束曲线；杆长误差会造成左右不对称。', 'Inner and outer joint positions set Ackermann and toe curve; length error creates asymmetry.', '它们像两根推拉杆，长度和铰点稍有偏差，车轮就会在跳动时自己转向。', 'They are push-pull links; small length or pivot errors make wheels steer themselves in bump.'),
    fact('集成在转向节上，连接拉杆外球头与主销轴线附近。', 'Integrated into the upright near the kingpin axis and outer tie-rod joint.', '提供转向力臂，并决定轮角对齿条位移的响应。', 'Provides steering lever arm and sets wheel-angle response to rack travel.', '臂长和方向影响转向比、阿克曼和轮胎回正力矩传回驾驶员的幅度。', 'Arm length and orientation affect ratio, Ackermann and how tyre aligning torque reaches the driver.', '它像轮端的小杠杆，既决定转多少，也决定驾驶员能感觉到多少路面信息。', 'It is the wheel-side lever controlling both steering amount and road feel.'),
    fact('支承轴承分布在转向柱与齿条壳体，限位位于齿条行程端。', 'Support bearings locate the column and rack; stops sit at rack travel limits.', '保持轴线、降低摩擦，并防止车轮或机构超过安全转角。', 'Maintains alignment, lowers friction and prevents unsafe over-travel.', '轴承错位会产生卡滞，硬限位必须承受驾驶员峰值输入而不把载荷传给脆弱齿面。', 'Bearing misalignment causes bind; stops must take peak input without loading fragile gear teeth.', '轴承让转向顺滑，限位像门挡，告诉机构“到这里就不能再走”。', 'Bearings keep steering smooth; stops are doorstops that define the safe end of travel.'),
  ],
  battery: [
    fact('成组排列在电池箱分段内部，是高压能量的基本单元；2026 规则把每个分段限制在 120 VDC、6 MJ 与 12 kg 以内。', 'Grouped into modules inside accumulator segments; the 2026 rules limit each segment to 120 VDC, 6 MJ and 12 kg.', '储存直流电能并在加速与回收时提供或吸收电流。', 'Stores DC energy and sources or absorbs current during acceleration and regeneration.', '电芯电压、内阻、温度与 SOC 共同限制功率；模块机械约束防止振动和膨胀移动。', 'Cell voltage, resistance, temperature and SOC limit power; module restraint prevents vibration and swelling movement.', '电芯像水箱里的小水桶，串联提高电压，并联提高可供电流。', 'Cells are small buckets in a reservoir: series raises voltage and parallel paths raise current capability.'),
    fact('母排跨接电芯端子，主保险串联在高压输出路径。', 'Busbars bridge cell terminals while the main fuse sits in the high-voltage output path.', '以低电阻汇集电流，并在严重过流时永久切断故障能量。', 'Collects current with low resistance and permanently interrupts severe overcurrent.', '截面积、接触电阻和电动力决定温升与机械载荷；保险 I²t 必须与线束和接触器协调。', 'Cross-section, contact resistance and electrodynamic force set heat and stress; fuse I-squared-t coordinates protection.', '母排是电流高速公路，保险丝是只能用一次的安全闸门。', 'Busbars are current highways; the fuse is a one-use safety gate.'),
    fact('两个主接触器位于电池输出两极，预充电阻与小接触器跨接主回路。', 'Two main contactors sit at the pack outputs, with a precharge resistor and relay across the main path.', '在安全状态下隔离高压，并在闭合前缓慢给逆变器电容充电。', 'Isolates high voltage in safe states and gently charges inverter capacitors before closing.', '预充限制浪涌电流；电压差达到阈值后主接触器闭合，异常则保持断开。', 'Precharge limits inrush; main contactors close after voltage converges and stay open on faults.', '它像高压系统的总闸和缓开阀，先小流量充满，再打开主通道。', 'It is the main breaker plus a slow-opening valve: fill gently first, then open the main path.'),
    fact('采样线连接每串电芯，温度传感器分布在模块热点附近。', 'Sense wires reach each cell group and temperature sensors sit near module hot spots.', '监控电压、温度与电流，估算 SOC，并在越界时请求切断高压。', 'Monitors voltage, temperature and current, estimates SOC and requests shutdown on limits.', 'AMS/BMS 需要隔离采样、开线诊断和一致的阈值逻辑；最弱电芯决定整包边界。', 'The AMS/BMS needs isolated sensing, open-wire diagnosis and coherent limits; the weakest cell sets the pack boundary.', '它是电池的护士，持续检查每个小单元，而不是只看整包平均值。', 'It is the battery nurse, watching every cell group rather than only the pack average.'),
    fact('连接高压系统与车架参考之间，通常独立于主控制软件。', 'Connected between the high-voltage system and chassis reference, normally independent of main control software.', '持续检测绝缘电阻，在线束或冷却液漏电时触发安全停机。', 'Continuously measures insulation resistance and triggers shutdown on leakage through wiring or coolant.', '通过测试信号估算正负母线到车架的等效阻抗；阈值与响应时间必须可验证。', 'A test signal estimates equivalent resistance from both rails to chassis; threshold and delay must be testable.', '它像高压系统的漏电保护器，发现电流可能走错路就立即报警。', 'It is the high-voltage leakage protector, reacting when current may find an unintended path.'),
    fact('外壳包围全部高压部件，冷却板贴近模块底部或侧面。', 'The enclosure surrounds all HV parts, with cold plates beneath or beside modules.', '提供防火、绝缘、碰撞与液体防护，并把电芯热量传给冷却回路。', 'Provides fire, isolation, impact and fluid protection while transferring cell heat to coolant.', '分隔墙限制故障传播；导热界面、流道和压紧力决定电芯温差与热点。', 'Internal walls limit propagation; thermal interface, channels and clamping set cell temperature spread.', '外壳像防火保险柜，冷却板像保险柜底下的冷水地板。', 'The enclosure is a fire-resistant safe; the cold plate acts as its chilled floor.'),
  ],
  inverter: [
    fact('位于直流母线与三相电机之间，由六个开关桥臂构成。', 'Between the DC bus and three-phase motor as six switching legs.', '用高速开关把直流电变成可控幅值与频率的三相交流。', 'Switches DC into three-phase AC with controlled amplitude and frequency.', 'IGBT 或 SiC MOSFET 通过 PWM 合成相电压；导通与开关损耗形成主要热源。', 'IGBTs or SiC MOSFETs synthesize phase voltage by PWM; conduction and switching losses create heat.', '它像极快的电子水龙头，每秒开关许多次，把直流切成电机需要的波形。', 'It is an extremely fast electronic tap chopping DC into the waveform the motor needs.'),
    fact('紧贴每个功率开关的控制端，与高压功率侧电隔离。', 'Placed close to each power-switch control terminal and isolated from the HV power side.', '快速充放栅极、控制开关速度并在短路或欠压时保护器件。', 'Charges and discharges gates, controls switching speed and protects devices on short circuit or undervoltage.', '驱动阻抗在损耗、过冲和电磁干扰间折中；去饱和检测可在微秒级关断故障。', 'Drive impedance trades loss, overshoot and EMI; desaturation protection can shut faults in microseconds.', '它像功率开关的贴身指挥员，命令必须又快又干净，出事时还要先救器件。', 'It is the switch bodyguard and commander, issuing clean fast orders and rescuing the device on faults.'),
    fact('跨接逆变器直流正负母线，尽量靠近功率模块。', 'Across the positive and negative DC rails, as close as possible to the power module.', '提供脉冲电流并吸收母线电压纹波与开关瞬态。', 'Supplies pulse current and absorbs DC-bus ripple and switching transients.', '低等效电感减少电压过冲；纹波电流在电容内发热，温度决定寿命。', 'Low equivalent inductance reduces overshoot; ripple current heats the capacitor and temperature governs life.', '它像电流的缓冲水箱，在功率开关突然要水时就近供给。', 'It is a current buffer tank supplying nearby demand when the switches suddenly ask for flow.'),
    fact('电流传感器位于相线或直流母线，电压采样跨接母线与相节点。', 'Current sensors sit in phase lines or DC bus; voltage sensing spans bus and phase nodes.', '给扭矩控制、功率计算、故障保护和能量统计提供反馈。', 'Provides feedback for torque control, power calculation, fault protection and energy accounting.', '带宽、偏置、隔离和采样同步直接影响电流环稳定性与保护阈值。', 'Bandwidth, offset, isolation and sampling alignment directly affect current-loop stability and protection.', '它们是逆变器的眼睛，开关很快，所以眼睛也必须看得快且准。', 'They are inverter eyes; fast switching requires equally fast and accurate sensing.'),
    fact('低压控制板位于屏蔽区域，通过 PWM 与驱动板连接并接收转子位置。', 'The low-voltage controller sits in a shielded region, linked to drivers and rotor-position sensing.', '执行 FOC、电流环、转矩命令、限幅和故障状态机。', 'Executes FOC, current loops, torque commands, limits and fault state machine.', '坐标变换把三相电流转成励磁与转矩分量，实时调节使磁场与转子保持目标关系。', 'Coordinate transforms separate flux and torque currents, regulating their relationship to the rotor in real time.', '它像会不断算方向的导航员，让定子磁场始终在最有效的位置推转子。', 'It is a navigator continuously orienting the stator field to push the rotor efficiently.'),
    fact('构成逆变器底面，功率模块通过导热界面压紧在流道上方。', 'Forms the inverter base, with power modules clamped over coolant channels through a thermal interface.', '把半导体与电容产生的热量低热阻地传给冷却液。', 'Transfers semiconductor and capacitor heat to coolant with low thermal resistance.', '接触平面度、界面材料、流道压降和热点流量分配共同限制结温。', 'Flatness, interface material, pressure drop and channel distribution together limit junction temperature.', '它像功率电子下面的冷水盘，表面任何空隙都会变成隔热层。', 'It is a cold-water tray under the electronics; any interface gap becomes insulation.'),
  ],
  motor: [
    fact('固定在电机壳体内圈，由叠片铁芯和多相铜绕组组成。', 'Fixed to the housing inner diameter as laminated steel and multiphase copper windings.', '产生旋转磁场并把电能转换成电磁转矩。', 'Creates the rotating magnetic field and converts electrical power into electromagnetic torque.', '相电流在齿槽磁路中建立磁势；铜损和铁损随电流、频率与磁通变化。', 'Phase current creates magnetomotive force in the slotted magnetic circuit; copper and iron losses vary with load and speed.', '它像不动的电磁跑道，磁场沿圆周奔跑，拉着里面的转子转动。', 'It is a stationary magnetic racetrack whose field runs around and pulls the rotor.'),
    fact('位于定子内部并与输出轴刚性连接，永磁体嵌入或贴装在转子上。', 'Inside the stator and rigidly attached to the output shaft, with magnets embedded or surface-mounted.', '与旋转磁场相互作用产生转矩，并以低惯量跟随扭矩命令。', 'Interacts with the rotating field to produce torque and follows commands with low inertia.', '磁体磁链与 q 轴电流产生转矩；高速离心力、退磁温度和套筒应力是关键限制。', 'Magnet flux and q-axis current produce torque; centrifugal stress, demagnetisation temperature and sleeve strength are limits.', '它像被看不见的磁力推着旋转的陀螺，是电机真正转起来的核心。', 'It is the spinning core pushed by an invisible magnetic field.'),
    fact('贯穿转子并由前后轴承支撑，端部连接齿轮或联轴器。', 'Passes through the rotor, supported by front and rear bearings and connected to gearing or coupling.', '保持气隙同心、传递转矩并承受齿轮或联轴器带来的径向与轴向载荷。', 'Maintains air-gap concentricity, transmits torque and carries radial or axial drivetrain loads.', '轴挠度影响气隙，轴承预紧影响摩擦与寿命；临界转速必须远离工作区。', 'Shaft deflection affects air gap, bearing preload affects friction and life, and critical speeds must avoid operation.', '它是电机的脊柱，既要把力送出去，也要让转子始终悬在正确中心。', 'It is the motor spine, transmitting torque while keeping the rotor precisely centred.'),
    fact('安装在轴端，传感器定子固定在壳体、转子随轴旋转。', 'Mounted at a shaft end with sensor stator fixed to the housing and rotor turning with the shaft.', '提供电角度和转速，使逆变器知道何时给哪一相通电。', 'Provides electrical angle and speed so the inverter knows when to energise each phase.', '位置偏置、极对数和信号解调决定换相精度；角度误差会降低转矩并增加电流。', 'Offset, pole count and demodulation set commutation accuracy; angle error reduces torque and raises current.', '它像电机的时钟和指南针，告诉控制器转子此刻朝哪里、转多快。', 'It is the motor clock and compass, telling the controller rotor angle and speed.'),
    fact('壳体包围定转子，冷却套环绕定子背铁或端部绕组。', 'The housing surrounds rotor and stator, with a cooling jacket around back iron or end windings.', '保持机械同轴、封闭高压部件并把铜损铁损传给冷却液。', 'Maintains alignment, encloses HV parts and transfers copper and iron losses to coolant.', '流道覆盖、对流系数和壳体接触热阻决定绕组热点；壳体还承担安装反力矩。', 'Channel coverage, convection and contact resistance set winding hot spots; the housing also carries reaction torque.', '它既是电机外骨骼也是水冷外套，既扛扭矩又带走热。', 'It is both motor exoskeleton and water jacket, carrying reaction torque and removing heat.'),
    fact('三根高压相线从逆变器进入电机接线端，配有屏蔽和应变释放。', 'Three HV phase leads enter the motor terminals from the inverter with shielding and strain relief.', '传输高幅值脉冲电流，并把电磁干扰和绝缘风险限制在可控范围。', 'Carries high-amplitude pulsed current while containing EMI and insulation risk.', '导体截面、端子接触、爬电间距和屏蔽回路决定温升、局放与共模噪声。', 'Conductor size, terminal contact, creepage and shielding govern heat, discharge and common-mode noise.', '它们像三条高频动力管道，连接不好不仅会发热，还会把噪声撒到全车。', 'They are three high-frequency power pipes; poor connections create heat and spread noise through the car.'),
  ],
  differential: [
    fact('位于电机输出与差速器壳体之间，由小齿轮驱动大齿圈。', 'Between motor output and differential case, with a pinion driving a larger ring gear.', '降低转速、放大轮端扭矩并设定整车最高车速与加速能力。', 'Reduces speed, multiplies wheel torque and sets the acceleration/top-speed trade.', '齿数比决定传动比；齿面接触、侧隙和润滑决定效率、噪声与疲劳。', 'Tooth count sets ratio; contact pattern, backlash and lubrication govern efficiency, noise and fatigue.', '它像自行车的齿比，只是功率更大，尺寸与强度要求更严。', 'It is a bicycle gear ratio at much higher power and with far tighter strength requirements.'),
    fact('安装在大齿圈内部，由行星/锥齿轮与十字轴连接左右输出。', 'Inside the ring gear, using bevel or planetary gears between left and right outputs.', '允许左右驱动轮在转弯时以不同速度旋转，同时传递总扭矩。', 'Allows different left-right wheel speeds in a corner while transmitting total torque.', '齿轮运动学满足平均转速关系；开放式结构会把可用扭矩限制在低抓地一侧。', 'Gear kinematics enforce the average-speed relation; an open unit is torque-limited by the low-grip side.', '它像允许两个人以不同步幅一起推车的协调器，转弯时外侧轮可以走更远。', 'It coordinates two pushers with different step lengths so the outside wheel can travel farther.'),
    fact('摩擦片组和斜坡凸轮位于差速器壳体与输出侧齿轮之间。', 'Clutch packs and ramp cams sit between the case and output side gears.', '在驱动或滑行时建立可调锁止扭矩，限制单轮空转。', 'Creates adjustable locking torque in drive or coast and limits one-wheel spin.', '预紧提供基础锁止，斜坡角把输入扭矩转成压紧力；片数与摩擦系数决定扭矩偏置。', 'Preload gives baseline lock; ramp angle converts input torque into clamp force; plates and friction set bias.', '它像两边车轮之间的可调摩擦纽带，一侧打滑时会拉另一侧一起工作。', 'It is an adjustable friction bond between wheels, recruiting the grippier side when one slips.'),
    fact('伸出差速器左右两侧，与半轴内等速节连接。', 'Projects from both sides of the differential and joins the inner CV joints.', '把差速器侧齿轮扭矩传给半轴，并提供可靠定位与密封表面。', 'Transfers side-gear torque into half-shafts and provides location and sealing surfaces.', '花键接触应力、法兰跳动和紧固预紧决定疲劳、振动与同轴度。', 'Spline contact stress, flange runout and fastener preload set fatigue, vibration and alignment.', '它们是差速器的左右输出插座，把内部齿轮的力交给两根半轴。', 'They are the two output sockets handing internal gear torque to the half-shafts.'),
    fact('轴承支撑输入与差速器总成，壳体包围齿轮并连接车架。', 'Bearings support input and differential assemblies while the housing encloses gears and mounts to the chassis.', '保持齿轮啮合位置、承受反力并封存润滑油。', 'Maintains gear mesh, carries reaction loads and contains lubricant.', '轴承预紧和壳体刚度控制齿面偏载；热膨胀会改变间隙与密封状态。', 'Bearing preload and case stiffness control tooth misalignment; thermal expansion changes clearance and sealing.', '壳体像齿轮箱的骨架和油盆，位置一软，齿轮再精密也会啮合不好。', 'The case is both gearbox skeleton and oil container; a flexible case ruins precise gear mesh.'),
    fact('润滑油覆盖齿轮与摩擦片，温度传感器位于回油或壳体热点。', 'Lubricant reaches gears and clutches while a temperature sensor monitors return flow or a case hot spot.', '形成油膜、带走摩擦热并提供差速器健康状态证据。', 'Forms oil films, removes friction heat and provides evidence of differential health.', '粘度随温度变化；油量过少会断膜，过多会搅油增损，污染物可揭示磨损。', 'Viscosity changes with temperature; too little starves films, too much churns, debris reveals wear.', '润滑油像齿轮的血液，温度和碎屑能提前告诉工程师内部是否受伤。', 'Lubricant is gear blood; temperature and debris warn of internal damage.'),
  ],
  cooling: [
    fact('冷却板贴合电池或逆变器，水套包围电机定子与壳体。', 'Cold plates contact the battery or inverter; jackets surround motor stator and housing.', '把固体热点产生的热量传入流动冷却液。', 'Transfers heat from solid hot spots into flowing coolant.', '导热界面、接触压力和内部流道决定总热阻与温度均匀性。', 'Thermal interface, contact pressure and internal channels set total resistance and uniformity.', '它像贴在发热部件上的水冷地板，接触越完整，热越容易走。', 'It is a water-cooled floor against hot hardware; better contact gives heat an easier exit.'),
    fact('安装在低位或回路入口附近，由低压电机驱动叶轮。', 'Mounted low or near a circuit inlet with an electric motor driving an impeller.', '克服管路、冷板和散热器压降，维持所需冷却液流量。', 'Overcomes pressure losses in hoses, cold plates and radiator to maintain flow.', '泵曲线与系统阻力曲线交点决定实际流量；气蚀和含气会使扬程骤降。', 'The pump/system curve intersection sets flow; cavitation and aeration collapse head.', '它是冷却回路的心脏，但实际流量由整条管路共同决定，不只看泵标称值。', 'It is the cooling-system heart, but the full circuit—not the label—sets actual flow.'),
    fact('位于侧箱或车尾进风区域，由翅片、扁管与集液室构成。', 'In sidepod or rear airflow, built from fins, flat tubes and headers.', '把冷却液热量通过管壁与翅片传给外部空气。', 'Moves coolant heat through tubes and fins into ambient air.', '换热取决于液侧与气侧热阻；堵塞、旁通和低速风量常成为限制。', 'Heat transfer depends on liquid- and air-side resistance; blockage, bypass and low-speed airflow often limit it.', '它像一排把水中热量递给空气的薄墙，表面积和穿过它的风都很重要。', 'It is a bank of thin walls handing heat from water to air; both area and airflow matter.'),
    fact('位于回路高点，连接泵入口和回液支路。', 'At a circuit high point, connected to pump inlet and return branches.', '容纳热膨胀、分离气泡并保证泵入口保持液柱。', 'Accommodates expansion, separates bubbles and maintains a liquid head at the pump inlet.', '流速降低让气体上浮；正确接管避免回流把气泡重新卷入主回路。', 'Reduced velocity lets gas rise; correct plumbing prevents return flow re-entraining bubbles.', '它像冷却系统的缓冲杯和排气站，让水有地方膨胀、让气泡有地方停。', 'It is the circuit buffer cup and air station, giving expansion and bubbles somewhere to go.'),
    fact('软管连接各部件，弯头、接头、阀和狭窄流道形成局部阻力。', 'Hoses join components while bends, fittings, valves and narrow passages create local restriction.', '完成可靠密封与柔性布置，并按需要分配各支路流量。', 'Provides sealed flexible routing and distributes branch flow as intended.', '压降随流量近似平方增长；弯折、截面突变和软管塌陷会消耗泵能力。', 'Pressure loss grows roughly with flow squared; bends, area changes and collapse consume pump capacity.', '它像城市水管网，泵再强，如果管道太细、弯太多，末端仍然没有流量。', 'It is a city pipe network; even a strong pump cannot overcome every narrow pipe and bend.'),
    fact('温度传感器布置在热源进出口，压力与流量传感器位于诊断关键段。', 'Temperature sensors sit across heat sources, with pressure and flow sensors at diagnostic points.', '计算吸热量、发现堵塞/漏液/含气，并验证热模型。', 'Calculates heat pickup, detects blockage, leakage or air and validates the thermal model.', '成对温度与可信流量可估算热功率；传感器安装位置和响应时间决定结论。', 'Paired temperatures and trusted flow estimate heat rate; placement and response time govern the result.', '它们是冷却回路的体检仪，单看一个水温往往无法判断问题在哪里。', 'They are the circuit diagnostic instruments; one coolant temperature rarely locates a fault.'),
  ],
  ecu: [
    fact('位于车辆控制器主板中央，与存储器、时钟和看门狗相连。', 'At the centre of the controller board with memory, clocks and watchdogs.', '按确定周期执行扭矩、能量、热管理与安全协调算法。', 'Executes torque, energy, thermal and safety coordination at deterministic intervals.', '实时任务按优先级和周期调度；最坏执行时间必须小于截止时间。', 'Real-time tasks are scheduled by priority and period; worst-case execution must meet deadlines.', '它像赛车的值班总工程师，每个控制周期都要准时做完该做的决定。', 'It is the on-duty chief engineer, finishing every decision before the next control deadline.'),
    fact('通过连接器接收踏板、压力、速度和开关信号，并输出继电器或执行器命令。', 'Receives pedal, pressure, speed and switch signals and drives relays or actuators through connectors.', '把真实世界电压、频率与开关状态转换成可计算数据，再把命令安全输出。', 'Converts real voltages, frequencies and states into data and safely drives commands back out.', '滤波、量程、上拉、开线/短路诊断和输出保护共同决定通道可信度。', 'Filtering, range, pull-ups, open/short diagnosis and output protection determine channel trust.', '它们像控制器的眼睛、耳朵和手，既要看清，也要识别断线与短路。', 'They are controller eyes, ears and hands, also detecting broken or shorted wiring.'),
    fact('CAN 收发器连接动力系统、仪表、传感器节点和数据记录器。', 'CAN transceivers link powertrain, display, sensor nodes and logger.', '用共享总线交换状态、命令、故障与时间信息。', 'Exchanges state, commands, faults and timing over a shared bus.', '仲裁 ID 决定优先级；终端、电缆拓扑、总线负载与超时策略决定可靠性。', 'Arbitration ID sets priority; termination, topology, bus load and timeout strategy set reliability.', '它像赛车内部的群聊，但关键消息必须有优先级、期限和失联处理。', 'It is the car group chat, where critical messages need priority, deadlines and dropout handling.'),
    fact('位于驾驶员请求与逆变器扭矩命令之间的软件决策层。', 'A software decision layer between driver request and inverter torque command.', '综合踏板、抓地、电池、热限制与故障状态，输出唯一允许扭矩。', 'Combines pedal, traction, battery, thermal limits and faults into one permitted torque.', '通常采用多限制器取最小值并施加速率限制；正负扭矩边界分别处理。', 'Often selects the most restrictive limit and applies rate control, with separate positive and negative bounds.', '它像多个部门共同签字：驾驶员想要多少不等于系统最终允许多少。', 'It is multi-department approval: driver demand is not automatically the allowed output.'),
    fact('以一组明确定义的正常、准备、驱动、降级与故障状态运行。', 'Runs as explicit normal, ready, drive, degraded and fault states.', '保证上电、预充、驱动和关断只按安全顺序发生。', 'Ensures power-up, precharge, drive and shutdown occur only in safe sequences.', '状态转移需要可验证条件、超时与锁存；安全关键故障不能靠软件自动随意复位。', 'Transitions need testable guards, timeouts and latches; critical faults must not auto-reset casually.', '它像航空检查单，步骤顺序不满足，就不能跳到“可以行驶”。', 'It is an aviation checklist: the car cannot jump to ready-to-drive when conditions are missing.'),
    fact('标定存储在版本化参数集中，运行数据写入内部存储或外部记录器。', 'Calibration lives in versioned parameter sets and runtime data goes to internal or external logging.', '让同一软件适应不同赛车设定，并留下可追溯的工程证据。', 'Lets one software build support setups and leaves traceable engineering evidence.', '参数需有单位、范围、权限和校验；日志需保存时间基准、软件版本与车辆配置。', 'Parameters need units, ranges, authority and checks; logs need time base, software version and vehicle configuration.', '标定像控制策略的旋钮，日志像黑匣子；两者都必须知道是谁、何时改过。', 'Calibration is the control knob and logging the black box; both need traceable change history.'),
  ],
  sensors: [
    fact('轮速传感器靠近轮毂齿圈，位置传感器安装在转向、踏板、电机或执行器轴上。', 'Wheel-speed sensors face tone rings; position sensors sit on steering, pedals, motor or actuator shafts.', '测量旋转速度与位移，为车辆状态估计和闭环控制提供基础。', 'Measures rotational speed and displacement for state estimation and closed-loop control.', '磁阻、霍尔或编码器把几何运动转成边沿/角度；齿隙、气隙和零点决定误差。', 'Magnetoresistive, Hall or encoder devices turn motion into edges or angle; runout, gap and zero set error.', '它们像给每个运动部件配的计步器和量角器。', 'They are pedometers and protractors attached to moving vehicle parts.'),
    fact('压力传感器接入制动与冷却回路，温度传感器贴近轮胎、制动、电池和电机热点。', 'Pressure sensors tap brake/cooling circuits; temperature sensors sit near tyre, brake, battery and motor hot spots.', '把液压、气压和热状态转成可记录信号。', 'Converts fluid pressure and thermal state into recordable signals.', '安装端口、导热路径和时间常数决定传感器是否代表真正被测位置。', 'Port geometry, heat path and time constant determine whether the reading represents the intended point.', '它们像赛车各系统的血压计与体温计，但放错位置就会量错对象。', 'They are system blood-pressure and temperature monitors, but wrong placement measures the wrong thing.'),
    fact('IMU 靠近车辆重心且刚性安装，GPS 天线位于开阔上表面。', 'The IMU mounts rigidly near the vehicle CG; the GPS antenna sits on an open upper surface.', '测量加速度、角速度、姿态、速度与赛道位置。', 'Measures acceleration, angular rate, attitude, velocity and track position.', '坐标系、安装角和时间同步必须校准；振动与多路径会污染惯性和卫星数据。', 'Axes, mounting angles and timing need calibration; vibration and multipath contaminate inertial and satellite data.', 'IMU 是内耳，GPS 是地图定位；两者结合才知道车怎么动、在哪里动。', 'The IMU is the inner ear and GPS the map position; together they describe motion and location.'),
    fact('应变片粘贴在连杆、支架或测力件表面，载荷传感器布置在目标力路径。', 'Strain gauges bond to links, mounts or load cells positioned in the intended force path.', '把微小结构变形转换成载荷，用于气动力、轮胎力和耐久验证。', 'Converts tiny structural strain into load for aero, tyre-force and durability validation.', '惠斯通电桥补偿温度并放大微应变；贴片方向、胶层和旁路载荷决定准确度。', 'A Wheatstone bridge compensates temperature and amplifies microstrain; alignment, bonding and load bypass set accuracy.', '它像贴在结构上的电子皮肤，感知肉眼看不到的微小拉伸。', 'It is electronic skin on the structure, sensing stretch too small to see.'),
    fact('数据记录器位于低振动区域，通过 CAN 与模拟/数字接口收集全车信号。', 'The logger sits in a low-vibration area and gathers signals through CAN and analogue/digital interfaces.', '统一时间戳、存储通道并提供赛后分析所需的完整数据集。', 'Applies a common time base, stores channels and creates the dataset for post-run analysis.', '采样率、反混叠、总线负载和时间同步必须按信号带宽设计，而不是越高越好。', 'Sample rate, anti-aliasing, bus load and timing follow signal bandwidth rather than simply maximising rate.', '它是赛车的黑匣子和会议记录员，把每个系统在同一时刻发生的事写下来。', 'It is the car black box and meeting recorder, writing what every system did on one timeline.'),
    fact('车载调制解调器与天线把选定通道传到维修区，分析软件在地面端解码与可视化。', 'An onboard modem and antenna send selected channels to the pit, where software decodes and visualises them.', '让工程师实时监控安全和性能，并在赛后进行更深层关联分析。', 'Enables live safety/performance monitoring and deeper post-run correlation.', '带宽预算、压缩、丢包、延迟和加密决定哪些数据适合实时传输；原始全量仍应车载保存。', 'Bandwidth, compression, packet loss, latency and security govern live channels; full raw data should remain onboard.', '它像赛车与工程师之间的实时对讲机，但不能把所有黑匣子数据都塞进一条无线链路。', 'It is the live radio between car and engineers, but cannot carry the entire black-box stream.'),
  ],
}
