import type { Locale } from './i18n'
import type { PartId } from './data'

export type LocalText = { zh: string; en: string }
export type LabKind = 'wing' | 'floor' | 'impact' | 'structure' | 'protection' | 'tire' | 'brake' | 'suspension' | 'steering' | 'battery' | 'inverter' | 'motor' | 'differential' | 'cooling' | 'control' | 'telemetry'

export type FormulaCard = {
  name: LocalText
  expression: string
  latex: string
  variables: LocalText
  insight: LocalText
}

export type GuidedExperiment = {
  title: LocalText
  question: LocalText
  steps: LocalText[]
  evidence: LocalText
}

export type DiagnosticCase = {
  title: LocalText
  symptom: LocalText
  checks: LocalText[]
  resolution: LocalText
}

export type EngineeringLesson = {
  labKind: LabKind
  overview: LocalText
  subcomponents: [LocalText, LocalText, LocalText, LocalText, LocalText, LocalText]
  concepts: [LocalText, LocalText, LocalText]
  formulas: [FormulaCard, FormulaCard, FormulaCard]
  experiments: [GuidedExperiment, GuidedExperiment]
  decisions: [LocalText, LocalText, LocalText]
  validation: [LocalText, LocalText]
  diagnostics: [DiagnosticCase, DiagnosticCase]
  references: { title: string; url: string }[]
}

export const t = (value: LocalText, locale: Locale) => value[locale]
export const localise = t
const l = (zh: string, en: string): LocalText => ({ zh, en })
const FORMULA_LATEX: Record<string, string> = {
  'Fz = ½ρV²S·CL': String.raw`F_{z,\downarrow} = \frac{1}{2}\rho V^2 S C_{L,\downarrow}`,
  'D = ½ρV²S·CD': String.raw`D = \frac{1}{2}\rho V^2 S C_D`,
  'βa = Fzf / (Fzf + Fzr)': String.raw`\beta_a = \frac{F_{z,f}}{F_{z,f}+F_{z,r}}`,
  'Fzr = ½ρV²Sr·CLr': String.raw`F_{z,r,\downarrow} = \frac{1}{2}\rho V^2 S_r C_{L,r,\downarrow}`,
  'ηa = |CL| / CD': String.raw`\eta_a = \frac{\lvert C_L\rvert}{C_D}`,
  'My = Fzf·af − Fzr·ar': String.raw`M_y = F_{z,f}a_f - F_{z,r}a_r`,
  'ṁ = ρA·V': String.raw`\dot{m} = \rho A V`,
  'p + ½ρV² ≈ constant': String.raw`p + \frac{1}{2}\rho V^2 \approx \mathrm{constant}`,
  'Cp = (p − p∞) / (½ρV∞²)': String.raw`C_p = \frac{p-p_\infty}{\frac{1}{2}\rho V_\infty^2}`,
  'Ek = ½mV²': String.raw`E_k = \frac{1}{2}mV^2`,
  'Eabs = ∫ F(x) dx': String.raw`E_{\mathrm{abs}} = \int F(x)\,\mathrm{d}x`,
  'ā = Eabs / (m·s)': String.raw`\bar{a} = \frac{E_{\mathrm{abs}}}{m s}`,
  'Kt = T / θ': String.raw`K_t = \frac{T}{\theta}`,
  'σ = M·y / I': String.raw`\sigma = \frac{M y}{I}`,
  'n = allowable / applied': String.raw`n = \frac{\mathrm{allowable}}{\mathrm{applied}}`,
  'σ = F / A': String.raw`\sigma = \frac{F}{A}`,
  'Pcr = π²EI / (KL)²': String.raw`P_{\mathrm{cr}} = \frac{\pi^2 E I}{(K L)^2}`,
  'MoS = allowable / applied − 1': String.raw`\mathrm{MoS} = \frac{\mathrm{allowable}}{\mathrm{applied}} - 1`,
  'κ = (Rω − Vx) / max(|Rω|, |Vx|)': String.raw`\kappa = \frac{R\omega-V_x}{\max\!\left(\lvert R\omega\rvert,\lvert V_x\rvert\right)}`,
  'α = atan2(Vy, |Vx|) − δ': String.raw`\alpha = \operatorname{atan2}\!\left(V_y,\lvert V_x\rvert\right)-\delta`,
  '(Fx / Fx,max)² + (Fy / Fy,max)² ≤ 1': String.raw`\left(\frac{F_x}{F_{x,\max}}\right)^2 + \left(\frac{F_y}{F_{y,\max}}\right)^2 \leq 1`,
  'p = Fpedal · Rp / Am': String.raw`p = \frac{F_{\mathrm{pedal}}R_p}{A_m}`,
  'Tb = μpad · p · Ap · Re · N': String.raw`T_b = \mu_{\mathrm{pad}}\,p\,A_p\,R_e\,N`,
  'E = ½m(V1² − V2²)': String.raw`E = \frac{1}{2}m\left(V_1^2-V_2^2\right)`,
  'kw = ks · MR²': String.raw`k_w = k_s\,\mathrm{MR}^2`,
  'fn = (1 / 2π) · √(kw / ms)': String.raw`f_n = \frac{1}{2\pi}\sqrt{\frac{k_w}{m_s}}`,
  'ζ = c / (2√(kw · ms))': String.raw`\zeta = \frac{c}{2\sqrt{k_w m_s}}`,
  'ΔFz,rear,el ≈ (Kφ,rear / Kφ,total) · ms·ay·hr / tr': String.raw`\Delta F_{z,r,\mathrm{el}} \approx \frac{K_{\phi,r}}{K_{\phi,\mathrm{total}}}\frac{m_s a_y h_r}{t_r}`,
  'P = Tshaft · ωshaft': String.raw`P = T_{\mathrm{shaft}}\,\omega_{\mathrm{shaft}}`,
  'cot(δo) − cot(δi) = t / L': String.raw`\cot\delta_o - \cot\delta_i = \frac{t}{L}`,
  'is = Δθwheel / Δδroadwheel': String.raw`i_s = \frac{\Delta\theta_{\mathrm{wheel}}}{\Delta\delta_{\mathrm{road\ wheel}}}`,
  'Tpinion ≈ Frack · rp': String.raw`T_{\mathrm{pinion}} \approx F_{\mathrm{rack}}\,r_p`,
  'E = ∫ V(t)·I(t) dt': String.raw`E = \int V(t)I(t)\,\mathrm{d}t`,
  'SOC = SOC0 − (1 / Qn)∫ I(t) dt': String.raw`\mathrm{SOC} = \mathrm{SOC}_0 - \frac{1}{Q_n}\int I(t)\,\mathrm{d}t`,
  'Q̇loss ≈ I²Rint': String.raw`\dot{Q}_{\mathrm{loss}} \approx I^2 R_{\mathrm{int}}`,
  'ηinv = Pac,out / Pdc,in': String.raw`\eta_{\mathrm{inv}} = \frac{P_{\mathrm{ac,out}}}{P_{\mathrm{dc,in}}}`,
  'Psw ≈ fsw · (Eon + Eoff) · Nswitch': String.raw`P_{\mathrm{sw}} \approx f_{\mathrm{sw}}\left(E_{\mathrm{on}}+E_{\mathrm{off}}\right)N_{\mathrm{switch}}`,
  'fe = p · nm / 60': String.raw`f_e = \frac{p\,n_m}{60}`,
  'Pmech = T · ω': String.raw`P_{\mathrm{mech}} = T\omega`,
  'Fx = Tmotor · ig · ηg / Rtire': String.raw`F_x = \frac{T_{\mathrm{motor}}\,i_g\,\eta_g}{R_{\mathrm{tire}}}`,
  'Pcu = 3 · Irms² · Rphase': String.raw`P_{\mathrm{cu}} = 3 I_{\mathrm{rms}}^2 R_{\mathrm{phase}}`,
  'ωcarrier = (ωL + ωR) / 2': String.raw`\omega_{\mathrm{carrier}} = \frac{\omega_L+\omega_R}{2}`,
  'TBR = Thigh / Tlow': String.raw`\mathrm{TBR} = \frac{T_{\mathrm{high}}}{T_{\mathrm{low}}}`,
  'Mz ≈ (Fx,R − Fx,L) · t / 2': String.raw`M_z \approx \left(F_{x,R}-F_{x,L}\right)\frac{t}{2}`,
  'Q̇ = ṁ · cp · ΔT': String.raw`\dot{Q} = \dot{m}\,c_p\,\Delta T`,
  'Rth = ΔT / Q̇': String.raw`R_{\mathrm{th}} = \frac{\Delta T}{\dot{Q}}`,
  'Ppump = Δp · qv / ηpump': String.raw`P_{\mathrm{pump}} = \frac{\Delta p\,q_v}{\eta_{\mathrm{pump}}}`,
  'y[k] = y[k−1] + α(x[k] − y[k−1])': String.raw`y[k] = y[k-1] + \alpha\left(x[k]-y[k-1]\right)`,
  '|Tcmd[k] − Tcmd[k−1]| ≤ Ṫmax · Δt': String.raw`\left\lvert T_{\mathrm{cmd}}[k]-T_{\mathrm{cmd}}[k-1]\right\rvert \leq \dot{T}_{\max}\Delta t`,
  'U = Σ(Ci / Ti)': String.raw`U = \sum_i \frac{C_i}{T_i}`,
  'y = a·x + b': String.raw`y = ax+b`,
  'fs > 2·fmax': String.raw`f_s > 2f_{\max}`,
  'uc = √(u1² + u2² + …)': String.raw`u_c = \sqrt{u_1^2+u_2^2+\cdots}`,
}
const f = (nameZh: string, nameEn: string, expression: string, variablesZh: string, variablesEn: string, insightZh: string, insightEn: string): FormulaCard => {
  const latex = FORMULA_LATEX[expression]
  if (!latex) throw new Error(`Missing LaTeX mapping for formula: ${expression}`)
  return { name: l(nameZh, nameEn), expression, latex, variables: l(variablesZh, variablesEn), insight: l(insightZh, insightEn) }
}
const e = (titleZh: string, titleEn: string, questionZh: string, questionEn: string, steps: [string, string][], evidenceZh: string, evidenceEn: string): GuidedExperiment => ({
  title: l(titleZh, titleEn), question: l(questionZh, questionEn), steps: steps.map(([zh, en]) => l(zh, en)), evidence: l(evidenceZh, evidenceEn),
})
const d = (titleZh: string, titleEn: string, symptomZh: string, symptomEn: string, checks: [string, string][], resolutionZh: string, resolutionEn: string): DiagnosticCase => ({
  title: l(titleZh, titleEn), symptom: l(symptomZh, symptomEn), checks: checks.map(([zh, en]) => l(zh, en)), resolution: l(resolutionZh, resolutionEn),
})

const FSG = { title: 'Formula Student Rules 2026 v1.1', url: 'https://www.formulastudent.de/fileadmin/user_upload/all/2026/rules/FS-Rules_2026_v1.1.pdf' }
const NASA = { title: 'NASA Glenn — Lift and Drag Equations', url: 'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/lift-to-drag-ratio/' }
const RCVD = { title: 'SAE — Race Car Vehicle Dynamics', url: 'https://www.sae.org/images/books/toc_pdfs/R280.pdf' }
const BOSCH = { title: 'Bosch Motorsport — Vehicle Control Unit', url: 'https://www.bosch-motorsport.com/products/control/vehicle-control-units/vehicle-control-unit-ms-50-4/' }
const NREL = { title: 'NREL — Battery Thermal Characterization', url: 'https://docs.nrel.gov/docs/fy17osti/68275.pdf' }
const FIA = { title: 'FIA 2026 F1 Technical Regulations — Issue 19', url: 'https://www.fia.com/system/files/documents/fia_2026_f1_regulations_-_section_c_technical_-_iss_19_-_2026-06-25.pdf' }

export const ENGINEERING_LESSONS: Record<PartId, EngineeringLesson> = {
  'front-wing': {
    labKind: 'wing',
    overview: l('前翼不仅产生前轴下压力，还决定前轮尾流怎样进入底板、侧箱和车尾。它是整车气动链路的起点，因此任何局部调节都会改变后方部件的来流质量。', 'The front wing creates front-axle downforce and conditions the wheel wake entering the floor, sidepods and rear of the car. It begins the aerodynamic chain, so a local adjustment changes the flow seen by downstream devices.'),
    subcomponents: [l('主翼片', 'Main plane'), l('襟翼', 'Flap'), l('端板', 'Endplate'), l('翼型间隙与重叠', 'Slot gap and overlap'), l('安装支架与调节机构', 'Mount and adjuster'), l('压力测点', 'Pressure taps')],
    concepts: [
      l('上下表面的压力积分形成净气动力；赛车把机翼反置，使合力指向地面。', 'Integrated surface pressure creates aerodynamic force; a race-car wing is inverted so the net force points toward the road.'),
      l('迎角、翼型、雷诺数和离地高度共同决定升力系数、阻力系数以及失速边界。', 'Angle of attack, profile, Reynolds number and ride height jointly determine force coefficients and stall boundary.'),
      l('前翼的目标不是单独获得最大下压力，而是在可接受阻力下获得稳定、可用的整车气动平衡。', 'The goal is not isolated peak downforce, but stable whole-car balance at acceptable drag.'),
    ],
    formulas: [
      f('下压力', 'Downforce', 'Fz = ½ρV²S·CL', 'ρ 空气密度；V 车速；S 参考面积；CL,↓ 为取正值的下压力系数', 'ρ air density; V speed; S reference area; CL,↓ is downforce-coefficient magnitude taken positive', '速度翻倍时，仅在姿态与系数近似不变的简化条件下，下压力约变为四倍。', 'Doubling speed produces roughly four times the downforce only when attitude and coefficient remain approximately constant.'),
      f('阻力', 'Drag', 'D = ½ρV²S·CD', 'CD 是包含型面、诱导和干扰效应的阻力系数', 'CD contains profile, induced and interference effects', '增加迎角通常同时增加下压力和阻力，接近失速后收益会迅速恶化。', 'More angle usually adds both downforce and drag; near stall the trade-off deteriorates rapidly.'),
      f('前轴气动平衡', 'Front aero balance', 'βa = Fzf / (Fzf + Fzr)', 'Fzf、Fzr 为前后轴气动载荷', 'Fzf and Fzr are front and rear aerodynamic loads', '气动平衡随车速和车身姿态变化，会直接改变高速转向特性。', 'Aero balance varies with speed and attitude, directly changing high-speed handling.'),
    ],
    experiments: [
      e('迎角扫描', 'Angle sweep', '更大的迎角是否永远更快？', 'Is more angle always faster?', [['先预测前轴载荷和阻力怎样变化。', 'Predict changes in front load and drag.'], ['从低迎角逐级增加到失速区域。', 'Sweep from low angle toward stall.'], ['比较 CL、CD、效率和气动平衡。', 'Compare CL, CD, efficiency and balance.']], '应观察到收益递减以及失速附近的不稳定，而不是一条无限增长的直线。', 'Look for diminishing returns and instability near stall, not unlimited linear growth.'),
      e('离地高度敏感性', 'Ride-height sensitivity', '制动俯仰为什么会改变前翼表现？', 'Why does braking pitch change front-wing performance?', [['锁定迎角并降低前轴离地高度。', 'Hold angle and lower front ride height.'], ['记录压力、载荷与效率。', 'Record pressure, load and efficiency.'], ['继续降低直到流动恶化。', 'Continue until the flow degrades.']], '工程师需要的是可预测的工作窗口，而不是只在一个高度出现的峰值。', 'Engineers need a predictable operating window, not a peak at one height.'),
    ],
    decisions: [l('用更多翼片换取高升力，还是用更简单结构换取低质量和高可靠性。', 'Trade more elements for high load, or simpler construction for low mass and reliability.'), l('在前轴响应、直线阻力、前轮尾流与冷却进气之间分配气流资源。', 'Allocate flow among front response, drag, wheel wake and cooling entry.'), l('设定能够覆盖制动俯仰、侧倾和不同车速的气动工作窗口。', 'Set an aero window covering braking pitch, roll and speed range.')],
    validation: [l('CFD 必须做网格、湍流模型和边界条件独立性检查，并与风洞或赛道数据相关。', 'CFD requires mesh, turbulence-model and boundary-condition checks, then correlation to tunnel or track data.'), l('用压力测点、测力天平、滑行试验或悬架位移反算气动载荷。', 'Use pressure taps, balances, coast-down or suspension displacement to estimate aero load.')],
    diagnostics: [
      d('高速前轴抓地突然下降', 'Sudden high-speed front grip loss', '驾驶员报告高速弯中前轮推向弯外，低速却正常。', 'The driver reports high-speed understeer while low-speed balance is normal.', [['检查翼片破损、橡胶附着和左右角度。', 'Inspect flap damage, rubber debris and left-right angle.'], ['比较前悬架高度与气动图谱。', 'Compare front ride height with the aero map.'], ['核对压力测点和前轴位移。', 'Check pressure taps and front displacement.']], '区分几何损伤、失速和姿态超出工作窗口，再决定修复或调校。', 'Separate damage, stall and out-of-window attitude before repair or setup change.'),
      d('直线速度异常降低', 'Unexpected top-speed loss', '圈速数据显示高速段加速度变差，但电机功率正常。', 'High-speed acceleration is worse while motor power is normal.', [['比较迎角与旧设定。', 'Compare angle with baseline.'], ['检查翼面污染和装配间隙。', 'Inspect contamination and slot gaps.'], ['用滑行数据估计阻力变化。', 'Estimate drag change from coast-down data.']], '若下压力没有对应收益，应降低无效迎角或恢复正确间隙。', 'If load did not improve, remove ineffective angle or restore correct gaps.'),
    ],
    references: [NASA, FSG, { title: 'SAE — Aerodynamics for Formula SAE', url: 'https://saemobilus.sae.org/papers/aerodynamics-formula-sae-a-numerical-wind-tunnel-track-study-2006-01-0808' }],
  },
  'rear-wing': {
    labKind: 'wing',
    overview: l('尾翼管理后轴高速载荷和整车压力中心。它既要利用经过驾驶舱和车身后的非均匀来流，又必须避免用过多阻力换取不可用的峰值下压力。', 'The rear wing manages high-speed rear load and the vehicle centre of pressure. It operates in non-uniform flow from the cockpit and body, and must avoid buying unusable peak load with excessive drag.'),
    subcomponents: [l('主翼片', 'Main plane'), l('襟翼', 'Flap'), l('端板', 'Endplate'), l('翼尖涡区域', 'Tip-vortex region'), l('支架', 'Pylons'), l('迎角调节孔位', 'Angle adjusters')],
    concepts: [l('有限翼展会产生翼尖涡和诱导阻力，端板用于限制高低压区的横向泄漏。', 'Finite span creates tip vortices and induced drag; endplates limit pressure leakage.'), l('尾翼来流受驾驶员、座舱防护和车身尾流影响，因此孤立翼型数据不能直接代表装车表现。', 'Cockpit and body wake alter rear-wing inflow, so isolated airfoil data does not equal installed performance.'), l('尾翼与前翼、底板共同决定压力中心；只调尾翼可能破坏全速域平衡。', 'Rear wing, front wing and floor set the centre of pressure; rear-only tuning can damage balance across speed.')],
    formulas: [f('尾翼下压力', 'Rear load', 'Fzr = ½ρV²Sr·CLr', 'Sr 为参考面积；CL,r,↓ 为取正值且包含尾流与支架干扰的装车下压力系数', 'Sr is reference area; CL,r,↓ is the positive installed downforce coefficient including wake and mount interference', '系数与参考面积的定义必须成对记录，不能把孤立翼型系数直接用于装车载荷。', 'Coefficient and reference area must be recorded as a pair; isolated-airfoil coefficients cannot directly predict installed load.'), f('气动效率', 'Aero efficiency', 'ηa = |CL| / CD', 'CL、CD 必须采用同一参考面积与同一装车工况', 'CL and CD must use the same reference area and installed condition', '效率不是圈速本身，还必须与赛道速度分布、气动平衡和动力限制结合。', 'Efficiency is not lap time; combine it with track speed distribution, aero balance and power limits.'), f('俯仰力矩', 'Pitch moment', 'My = Fzf·af − Fzr·ar', 'Fzf、Fzr 均取向下为正；af、ar 为重心到前后压力中心的正力臂；本式规定前轴项为正俯仰矩', 'Fzf and Fzr are positive downward; af and ar are positive CG-to-centre-of-pressure arms; the front term is defined as positive pitch moment', '必须先声明坐标和力矩正方向；相同总下压力也会因分布不同产生不同操稳。', 'Declare coordinate and moment signs first; identical total load can produce different handling when distributed differently.')],
    experiments: [e('尾翼设定图', 'Rear-wing map', '怎样找到适合当前赛道的角度？', 'How do you select angle for a track?', [['扫描迎角并记录载荷与阻力。', 'Sweep angle and record load and drag.'], ['查看直线时间和高速弯极限。', 'Inspect straight time and fast-corner limit.'], ['选择总圈时最优点而非最大 CL 点。', 'Choose minimum lap time, not maximum CL.']], '最优设定由赛道决定，通常不在任何单项指标的极值。', 'The optimum is track-dependent and rarely a single-metric maximum.'), e('气动平衡联调', 'Aero-balance matching', '增加尾翼后前翼需要怎样配合？', 'What front change follows more rear wing?', [['提高尾翼角度。', 'Increase rear angle.'], ['观察压力中心后移。', 'Observe rearward centre-of-pressure shift.'], ['逐步调整前翼恢复目标平衡。', 'Adjust the front wing to recover target balance.']], '前后翼应按整车压力中心联合设定。', 'Front and rear devices must be set by whole-car centre of pressure.')],
    decisions: [l('选择单翼、多段翼或更大翼展时同时考虑质量、刚度、规则空间和效率。', 'Choose element count and span with mass, stiffness, rule volume and efficiency together.'), l('支架应在可接受变形下传递气动载荷，避免动态迎角漂移。', 'Pylons must carry aero loads with acceptable deflection to prevent dynamic angle drift.'), l('根据赛道速度分布选择下压力档位，而不是复制另一辆车的角度。', 'Select load level from track speed distribution, not another car’s angle.')],
    validation: [l('进行装车 CFD/风洞扫描，包含驾驶员、车轮旋转和移动地面。', 'Run installed CFD/tunnel sweeps including driver, rotating wheels and moving ground.'), l('用支架应变、后悬架位移和最高车速交叉验证载荷与阻力。', 'Cross-check pylon strain, rear displacement and top speed.')],
    diagnostics: [d('高速车尾不稳定', 'High-speed rear instability', '高速转向中偏航增益突然增大。', 'Yaw gain rises abruptly in fast turns.', [['检查翼片失速和支架变形。', 'Check wing stall and pylon deflection.'], ['核对后轴高度与侧倾。', 'Check rear ride height and roll.'], ['比较尾翼压力与后悬架载荷。', 'Compare wing pressure and rear suspension load.']], '若载荷随姿态突降，需要扩大气动工作窗口，而不仅是继续加角度。', 'If load collapses with attitude, widen the aero window instead of adding angle.'), d('左右后轮温度差扩大', 'Growing rear tyre temperature split', '直线设定正常，但高速弯后左右后胎温差异常。', 'Straight-line setup looks normal but rear tyre temperatures diverge after fast corners.', [['测量左右翼面角度。', 'Measure left-right wing angle.'], ['检查端板和支架损伤。', 'Inspect endplate and pylon damage.'], ['核对横风与车身高度。', 'Check crosswind and ride height.']], '排除气动不对称后再调整机械平衡。', 'Eliminate aero asymmetry before changing mechanical balance.')],
    references: [NASA, FSG, { title: 'SAE — Formula SAE Aero Package Design', url: 'https://saemobilus.sae.org/papers/race-car-aerodynamics-design-process-aerodynamic-package-2012-chalmers-formula-sae-car-2013-01-0797' }],
  },
  floor: {
    labKind: 'floor',
    overview: l('底板和扩散器把车辆与地面之间的空间变成受控流道。它们通常具有较高气动效率，但对离地高度、俯仰、侧倾、密封涡和轮胎尾流极其敏感。', 'The floor and diffuser turn the gap to the road into a controlled flow passage. They can be efficient but are highly sensitive to ride height, pitch, roll, sealing vortices and tyre wake.'),
    subcomponents: [l('底板入口', 'Floor inlet'), l('低压通道', 'Low-pressure tunnel'), l('边缘密封区域', 'Edge-sealing region'), l('扩散器坡面', 'Diffuser ramp'), l('分流片', 'Strakes'), l('出口压力恢复区', 'Pressure-recovery exit')],
    concepts: [l('流道收缩会提高局部速度并降低静压，但真实粘性流动还受边界层和涡结构控制。', 'Passage contraction increases local speed and lowers static pressure, while real viscous flow is governed by boundary layers and vortices.'), l('扩散器通过逐步增大面积恢复压力；角度过大或来流质量差会发生分离。', 'The diffuser recovers pressure through area expansion; too much angle or poor inflow causes separation.'), l('最低车高不一定产生最大可用下压力，触底和流动崩溃会使载荷非线性下降。', 'The lowest ride height does not guarantee usable peak load; contact and flow collapse create nonlinear loss.')],
    formulas: [f('连续关系', 'Continuity', 'ṁ = ρA·V', 'A 为选定流管的截面积；V 为截面质量平均速度；只有同一流管且无泄漏时质量流量才守恒', 'A is selected stream-tube area; V is mass-averaged section speed; mass flow is conserved only for the same stream tube without leakage', '底板两侧泄漏、轮胎尾流和三维流动会改变有效流管，不能只凭几何收缩比预测速度。', 'Side leakage, tyre wake and three-dimensional flow alter the effective stream tube, so geometry contraction alone cannot predict speed.'), f('简化能量关系', 'Simplified energy relation', 'p + ½ρV² ≈ constant', '仅是沿同一流线、稳态、近似不可压、无轴功且粘性损失可忽略时的伯努利教学关系', 'Bernoulli teaching relation only along one streamline for steady, approximately incompressible flow with no shaft work and negligible viscous loss', '真实底板载荷不能靠此式单独预测，必须用含边界层、湍流、分离和移动地面的模型或试验验证。', 'This equation alone cannot predict real floor load; boundary layer, turbulence, separation and moving-ground effects require modelling or test correlation.'), f('压力系数', 'Pressure coefficient', 'Cp = (p − p∞) / (½ρV∞²)', 'p∞、V∞ 为同一试验工况的自由来流参考；Cp 的符号遵循静压差定义', 'p∞ and V∞ are free-stream references for the same condition; Cp sign follows the static-pressure-difference definition', '负 Cp 表示局部静压低于自由来流，但总下压力仍需对整个表面压力与剪切积分。', 'Negative Cp means local static pressure below free stream, but total load still requires pressure and shear integration over all surfaces.')],
    experiments: [e('车高扫描', 'Ride-height sweep', '下压力为何先增加后下降？', 'Why does load rise and then collapse?', [['从高车高逐步降低。', 'Lower ride height from a high baseline.'], ['记录最低压力和总下压力。', 'Record minimum pressure and total load.'], ['识别触底或流动分离点。', 'Identify contact or separation onset.']], '曲线应存在工作窗口和峰值，而非单调关系。', 'The curve should show an operating window and peak, not monotonic behaviour.'), e('俯仰与侧倾', 'Pitch and roll', '制动和转弯怎样改变底板密封？', 'How do braking and cornering change floor sealing?', [['分别施加俯仰和侧倾。', 'Apply pitch and roll separately.'], ['观察左右通道 Cp 和出口流动。', 'Observe left-right Cp and exit flow.'], ['再组合两种姿态。', 'Combine both attitudes.']], '组合姿态可能产生单边失速和气动偏航力矩。', 'Combined attitude can cause one-sided stall and aero yaw moment.')],
    decisions: [l('在峰值下压力与姿态鲁棒性之间取舍。', 'Trade peak load against attitude robustness.'), l('扩散角、通道长度和出口面积必须与边界层状态匹配。', 'Match ramp angle, length and exit area to boundary-layer condition.'), l('机械悬架刚度需要服务于底板工作窗口，同时保留轮胎机械抓地。', 'Suspension stiffness must support the floor window without sacrificing mechanical grip.')],
    validation: [l('用车高扫描 CFD、移动地面风洞和压力耙验证压力恢复。', 'Validate recovery with ride-height CFD, moving-ground tunnel and pressure rake.'), l('赛道上联合分析车高传感器、速度、纵横向加速度与圈速。', 'Correlate ride-height sensors, speed, accelerations and lap time on track.')],
    diagnostics: [d('高速弹跳或载荷振荡', 'High-speed heave oscillation', '高速直道车高和垂向加速度出现周期振荡。', 'Ride height and vertical acceleration oscillate on straights.', [['检查车高是否穿越气动峰值。', 'Check whether ride height crosses the aero peak.'], ['比较阻尼和底板载荷斜率。', 'Compare damping with floor load gradient.'], ['检查触底痕迹。', 'Inspect contact marks.']], '需要联合调整气动图谱、弹簧/阻尼和最低车高，而不是只加硬弹簧。', 'Tune aero map, springs/dampers and minimum height together, not stiffness alone.'), d('单侧下压力丢失', 'One-sided load loss', '高速长弯中车辆突然增加方向盘角度。', 'Steering demand rises suddenly in a long fast corner.', [['检查侧倾与底板边缘损伤。', 'Check roll and floor-edge damage.'], ['比较左右压力。', 'Compare left-right pressure.'], ['检查轮胎尾流和分流片。', 'Inspect tyre wake and strakes.']], '识别单边分离或密封破坏后修复几何并扩大侧倾窗口。', 'Identify one-sided separation or sealing loss, repair geometry and widen the roll window.')],
    references: [FSG, { title: 'SAE — Ride Height Dependency of a Multichannel Diffuser', url: 'https://saemobilus.sae.org/papers/aerodynamic-analysis-ride-height-dependency-a-high-performance-vehicle-equipped-a-multichannel-diffuser-ground-effect-2023-01-5064' }, NASA],
  },
  nose: {
    labKind: 'impact',
    overview: l('鼻锥与吸能盒需要在有限行程内以可控方式压溃，吸收车辆动能并限制传入生存舱的平均与峰值减速度，同时还承担前翼安装和气流整形任务。', 'The nose and impact attenuator must crush predictably within limited stroke, absorb kinetic energy and limit average and peak deceleration into the survival cell, while also mounting the front wing and shaping flow.'),
    subcomponents: [l('鼻锥外壳', 'Nose fairing'), l('吸能芯体', 'Crush core'), l('防侵入板', 'Anti-intrusion plate'), l('前隔板连接', 'Front-bulkhead joint'), l('前翼安装点', 'Front-wing mount'), l('触发与压溃结构', 'Crush triggers')],
    concepts: [l('安全目标不是“越硬越好”，而是在允许的行程中把能量以受控载荷吸收。', 'Safety is not maximum stiffness; energy must be absorbed at controlled load over available stroke.'), l('平均减速度决定总体伤害风险，短时峰值、侵入和连接失效同样关键。', 'Average deceleration matters, but short peaks, intrusion and joint failure are also critical.'), l('有限元预测必须由代表性材料和完整安装边界的物理碰撞试验验证。', 'FE prediction requires physical impact validation with representative materials and mounting boundaries.')],
    formulas: [f('碰撞动能', 'Impact energy', 'Ek = ½mV²', 'm 为规则定义的移动测试质量；V 为撞击前相对速度', 'm is the rule-defined moving test mass; V is pre-impact relative speed', '速度增加 10% 会让能量增加约 21%；具体试验质量、边界和方向必须按适用规则定义。', 'A 10% speed increase raises energy about 21%; test mass, boundary and direction must follow the applicable rule definition.'), f('吸能', 'Energy absorption', 'Eabs = ∫ F(x) dx', 'F(x) 为压溃方向的反力；x 为同一方向的压溃位移；曲线积分包含峰值与平台', 'F(x) is reaction force along crush direction; x is collinear crush displacement; the integral includes peak and plateau', '吸能相同不代表乘员载荷相同，初始峰值、脉冲形状、偏轴加载和侵入量都必须检查。', 'Equal absorbed energy does not imply equal occupant loading; initial peak, pulse shape, off-axis load and intrusion must be checked.'), f('全行程平均减速度', 'Full-stroke mean deceleration', 'ā = Eabs / (m·s)', 's 为有效压溃行程；该式给出能量等效平均值，不是峰值或时间历程', 's is effective crush stroke; this is an energy-equivalent mean, not peak or time history', '更长受控行程通常降低平均值，但峰值加速度和乘员响应仍需由力—位移与加速度—时间数据验证。', 'Longer controlled stroke often lowers the mean, but peak acceleration and occupant response still require force-displacement and acceleration-time validation.')],
    experiments: [e('压溃行程设计', 'Crush-stroke design', '给定质量和速度，需要多长行程？', 'How much stroke is required?', [['设置质量和撞击速度。', 'Set mass and impact speed.'], ['选择允许平均载荷。', 'Choose allowable mean load.'], ['观察所需行程和峰值裕量。', 'Observe required stroke and peak margin.']], '行程、平均载荷与材料平台应同时满足，单独满足能量不够。', 'Stroke, mean load and material plateau must all work; energy alone is insufficient.'), e('材料曲线比较', 'Material-curve comparison', '泡沫、蜂窝与复合压溃有何差异？', 'How do foam, honeycomb and composite crush differ?', [['选择三种力—位移曲线。', 'Select three force-displacement curves.'], ['保持吸收能量相同。', 'Hold absorbed energy constant.'], ['比较峰值、质量和稳定性。', 'Compare peak, mass and stability.']], '最轻方案若峰值过高或压溃不稳定仍不可接受。', 'The lightest solution is unacceptable if the peak is high or crush is unstable.')],
    decisions: [l('选择标准吸能盒或自研结构时权衡开发风险、质量和包装。', 'Trade standard attenuator versus custom design in risk, mass and packaging.'), l('让非压溃物体、传感器和前翼安装不阻碍吸能路径。', 'Keep non-crushable items, sensors and wing mounts out of the crush path.'), l('连接设计必须把载荷扩散到前隔板而不产生局部穿透。', 'Spread load into the bulkhead without local penetration.')],
    validation: [l('提交力—位移、能量、平均/峰值减速度和试验后结构状态。', 'Document force-displacement, energy, mean/peak deceleration and post-test condition.'), l('核对完整安装夹具、质量、速度、采样率和传感器校准。', 'Verify fixture, mass, speed, sample rate and sensor calibration.')],
    diagnostics: [d('试验初始峰值过高', 'Excessive initial peak', '能量满足要求，但碰撞刚开始加速度尖峰过大。', 'Energy is sufficient, but the initial acceleration spike is excessive.', [['检查触发槽和首层几何。', 'Inspect crush triggers and first-stage geometry.'], ['核对传感器滤波。', 'Verify sensor filtering.'], ['检查夹具刚度与间隙。', 'Inspect fixture stiffness and clearances.']], '优化触发结构并复核测量链，不能用过度滤波掩盖真实峰值。', 'Improve triggers and verify measurement; do not hide a real peak with filtering.'), d('压溃偏斜', 'Off-axis crush', '试件向一侧折叠并提前触及刚性部件。', 'The specimen folds sideways and reaches a rigid object early.', [['检查材料和壁厚对称性。', 'Check material and wall symmetry.'], ['检查安装垂直度。', 'Check mounting alignment.'], ['查看局部屈曲起点。', 'Locate initial buckling.']], '改善导向和触发对称性，并在整车边界下重新验证。', 'Improve guidance and trigger symmetry, then revalidate with vehicle-representative boundaries.')],
    references: [FSG, { title: 'SAE — Formula SAE Impact Attenuator Design', url: 'https://saemobilus.sae.org/articles/design-simulation-a-formula-sae-impact-attenuator-05-15-03-0018' }],
  },
  monocoque: {
    labKind: 'structure',
    overview: l('单体壳是悬架、气动、电池和驾驶员安全系统的共同载荷平台。工程设计的核心是以最低可制造质量获得足够的全局扭转刚度、局部硬点刚度、碰撞防护和耐久性。', 'The monocoque is the shared load platform for suspension, aero, accumulator and driver safety. Design seeks sufficient global torsion, local hardpoint stiffness, crash protection and durability at manufacturable low mass.'),
    subcomponents: [l('碳纤维面板', 'Carbon skins'), l('蜂窝或泡沫芯材', 'Honeycomb or foam core'), l('前后隔板', 'Front and rear bulkheads'), l('悬架硬点嵌件', 'Suspension hardpoint inserts'), l('侧面防护面板', 'Side-impact panels'), l('胶接与机械连接', 'Bonded and mechanical joints')],
    concepts: [l('全局扭转刚度必须高到让悬架调校可预测，但无限提高会增加质量而收益递减。', 'Global torsional stiffness must make suspension tuning predictable, but unlimited stiffness adds mass with diminishing return.'), l('复合材料是各向异性的，纤维方向、铺层顺序、芯材和胶接共同决定刚度与失效模式。', 'Composites are anisotropic; fibre direction, stacking sequence, core and bonds determine stiffness and failure.'), l('硬点附近的局部承压、剥离、芯材压溃和载荷扩散往往比理想面板强度更关键。', 'Bearing, peel, core crush and load spreading near hardpoints can govern over ideal panel strength.')],
    formulas: [f('扭转刚度', 'Torsional stiffness', 'Kt = T / θ', 'T 是施加扭矩；θ 是前后截面的相对扭转角', 'T is applied torque; θ is relative twist', '目标应与轮端/防倾刚度比较，确保车架柔度不会主导载荷分配。', 'Compare the target with wheel and roll stiffness so chassis compliance does not dominate load distribution.'), f('弯曲应力', 'Bending stress', 'σ = M·y / I', 'M 弯矩；y 到中性轴距离；I 截面二次矩', 'M moment; y distance from neutral axis; I second moment', '增大截面高度通常比单纯加厚更有效，但会受包装限制。', 'Increasing section depth is often more efficient than adding thickness, but packaging limits it.'), f('安全系数', 'Factor of safety', 'n = allowable / applied', 'allowable 必须来自代表性材料试验并考虑环境与制造缺陷', 'Allowable must come from representative tests and include environment and manufacturing defects', '复合结构不能只用一个金属式屈服安全系数描述所有失效。', 'One metal-style yield factor cannot describe every composite failure mode.')],
    experiments: [e('扭转台架', 'Torsion rig', '车架刚度怎样影响轮端载荷？', 'How does chassis stiffness affect wheel load?', [['固定后轴硬点并在前轴施加反向轮载。', 'Fix rear hardpoints and apply opposite front wheel loads.'], ['记录扭矩与角度。', 'Record torque and twist.'], ['改变车架刚度观察载荷分配。', 'Change stiffness and observe load distribution.']], '线性区斜率给出刚度，滞回和非线性提示连接或损伤。', 'Linear slope gives stiffness; hysteresis and nonlinearity indicate joints or damage.'), e('铺层设计', 'Laminate design', '纤维方向怎样改变性能？', 'How does fibre direction change performance?', [['保持面密度相同。', 'Hold areal mass constant.'], ['改变 0/±45/90 度比例。', 'Change 0/±45/90 proportions.'], ['比较扭转、弯曲和局部剪切。', 'Compare torsion, bending and local shear.']], '单一方向最强不等于整车载荷下最优，应由载荷路径决定铺层。', 'Strength in one direction is not whole-car optimum; load paths must set the layup.')],
    decisions: [l('确定车架刚度目标时要与悬架、轮胎和整车质量共同优化。', 'Optimise stiffness target with suspension, tyres and vehicle mass.'), l('嵌件与胶接必须实现渐进载荷扩散并允许制造和检查。', 'Inserts and bonds need progressive load spreading plus manufacturability and inspection.'), l('定义可追溯的材料批次、固化过程、试片和无损检测计划。', 'Define traceable material batches, cure process, coupons and NDT plan.')],
    validation: [l('先做材料拉伸、面板弯曲与剪切，再验证子结构、硬点和整车扭转。', 'Test material, panel bending/shear, then substructures, hardpoints and full chassis torsion.'), l('用实测边界条件修正有限元，并报告网格、接触和材料敏感性。', 'Correlate FE with measured boundaries and report mesh, contact and material sensitivity.')],
    diagnostics: [d('调校响应左右不一致', 'Asymmetric setup response', '相同防倾杆调整在左右弯产生不同效果。', 'The same anti-roll adjustment behaves differently left and right.', [['测量车架扭转与硬点位置。', 'Measure torsion and hardpoint position.'], ['检查胶接和嵌件。', 'Inspect bonds and inserts.'], ['做四轮称重和对角刚度检查。', 'Perform corner-weight and diagonal stiffness checks.']], '先排除车架/硬点柔度与损伤，再判断悬架设定。', 'Eliminate chassis/hardpoint compliance or damage before judging setup.'), d('表面完好但刚度下降', 'Stiffness loss without visible damage', '事故后外观正常，扭转台架斜率却降低。', 'After an incident the surface looks normal but torsion slope falls.', [['超声或敲击检查分层。', 'Use ultrasound or tap testing for delamination.'], ['检查芯材脱粘和嵌件周围。', 'Inspect core disbond and inserts.'], ['比较滞回曲线。', 'Compare hysteresis curves.']], '复合材料内部损伤可能不可见，必须依据 NDT 和结构试验决定返修或报废。', 'Hidden composite damage requires NDT and structural evidence for repair or retirement.')],
    references: [FSG, { title: 'SAE — Carbon Fibre Monocoque Design', url: 'https://saemobilus.sae.org/articles/design-analysis-simulation-automotive-carbon-fiber-monocoque-chassis-2014-01-1052' }, { title: 'Cal Poly — FSAE Chassis Torsional Stiffness', url: 'https://digitalcommons.calpoly.edu/theses/1692/' }],
  },
  halo: {
    labKind: 'protection',
    overview: l('本车将驾驶员头部周围的结构统一称为座舱防护结构。大学生方程式赛事的主线应学习主/前防滚架、支撑、头枕、安全带和生存空间；F1 头部保护环仅作为更高载荷等级的对比案例。', 'The car groups structures around the driver’s head as cockpit protection. The Formula Student core covers main/front roll hoops, bracing, head restraint, harness and survival space; the F1 Halo is an advanced comparison only.'),
    subcomponents: [l('主防滚架', 'Main roll hoop'), l('前防滚架', 'Front roll hoop'), l('防滚架支撑', 'Roll-hoop bracing'), l('头部保护包络', 'Head-protection envelope'), l('头枕与座椅', 'Head restraint and seat'), l('安全带安装点', 'Harness anchors')],
    concepts: [l('结构的首要任务是事故中保持驾驶员生存空间并把载荷传入主结构。', 'The primary task is preserving survival space and transferring accident loads into the primary structure.'), l('保护结构必须同时满足强度、刚度、视野、逃生、驾驶姿态和空气动力学约束。', 'Protection must satisfy strength, stiffness, visibility, egress, ergonomics and aero constraints.'), l('任何防护杆件都不能脱离安装边界单独评估；接头和车架局部刚度决定真实能力。', 'No protective member can be assessed without its mounting boundary; joints and local chassis stiffness govern capacity.')],
    formulas: [f('名义应力', 'Nominal stress', 'σ = F / A', 'F 为轴向载荷；A 为有效承载面积', 'F axial load; A effective load area', '只适合初步估算，弯曲、连接和屈曲必须单独分析。', 'This is preliminary only; bending, joints and buckling need separate analysis.'), f('欧拉屈曲', 'Euler buckling', 'Pcr = π²EI / (KL)²', 'E 弹性模量；I 截面惯性矩；K 有效长度系数；L 长度', 'E modulus; I second moment; K effective-length factor; L length', '细长支撑常由屈曲而不是材料压缩强度控制。', 'Slender braces may be governed by buckling rather than compressive strength.'), f('安全裕量', 'Margin of safety', 'MoS = allowable / applied − 1', 'allowable 应含材料、工艺、连接和规则规定的折减', 'Allowable includes material, process, joint and rule knock-downs', '正裕量不等于完成验证，仍需检查变形、生存空间和多方向载荷。', 'Positive margin is not full validation; deformation, survival space and multidirectional loads remain.')],
    experiments: [e('多方向载荷', 'Multi-direction load', '哪个方向最危险？', 'Which direction is critical?', [['分别施加纵向、横向和垂向载荷。', 'Apply longitudinal, lateral and vertical loads.'], ['观察应力、位移和接头反力。', 'Observe stress, displacement and joint reactions.'], ['组合载荷寻找最低裕量。', 'Combine loads and find the lowest margin.']], '最危险工况可能由连接变形或屈曲决定，而非最大单轴载荷。', 'The critical case may be joint deformation or buckling, not the largest single-axis force.'), e('驾驶员包络', 'Driver envelope', '结构强度合格是否就足够？', 'Is strength compliance enough?', [['切换不同身材驾驶员。', 'Switch driver sizes.'], ['检查头部、头枕、视野和逃生路径。', 'Check head envelope, restraint, view and egress.'], ['叠加载荷变形。', 'Overlay loaded deformation.']], '保护空间必须在变形后仍有效，同时驾驶员能按规则快速离车。', 'Protection must remain effective after deformation while allowing compliant egress.')],
    decisions: [l('确定材料与截面时同时考虑屈曲、焊接/胶接、质量和安装空间。', 'Choose material and section for buckling, joints, mass and space.'), l('把头枕、安全带和座椅视为同一约束系统设计。', 'Design head restraint, harness and seat as one restraint system.'), l('明确 Formula Student 与 F1 防护规则差异，避免错误照搬。', 'Keep Formula Student and F1 requirements distinct; do not copy blindly.')],
    validation: [l('用规则载荷工况验证结构、接头、变形和驾驶员包络。', 'Validate structure, joints, deformation and driver envelope under rule load cases.'), l('做座舱模板、驾驶员逃生、头枕与安全带安装检查。', 'Run cockpit template, egress, head-restraint and harness checks.')],
    diagnostics: [d('支撑接头出现裂纹', 'Cracked brace joint', '赛后检查发现焊趾或胶接边缘裂纹。', 'Post-run inspection finds cracking at a weld toe or bond edge.', [['检查载荷路径和局部弯矩。', 'Inspect load path and local moment.'], ['做渗透/超声检查。', 'Perform dye penetrant or ultrasound.'], ['复核热影响区或胶层工艺。', 'Review heat-affected zone or bond process.']], '必须查明局部刚度突变和工艺根因，不能只在裂纹上覆盖补强。', 'Find the stiffness discontinuity and process root cause; do not patch over the crack.'), d('驾驶员头部接近保护边界', 'Head near protection boundary', '更高驾驶员佩戴头盔后接近规定包络。', 'A taller helmeted driver approaches the required envelope.', [['检查座椅位置和头枕厚度。', 'Check seat position and head-restraint thickness.'], ['验证正常驾驶姿态。', 'Verify normal driving posture.'], ['进行逃生测试。', 'Perform egress test.']], '通过座舱布置满足全体驾驶员，而不是要求驾驶员采用不可持续姿势。', 'Fix cockpit layout for all drivers rather than forcing an unsustainable posture.')],
    references: [FSG, FIA],
  },
  tires: {
    labKind: 'tire',
    overview: l('轮胎是赛车唯一与地面交换纵向力、横向力和支承载荷的部件，也是整车最强的非线性来源。它的抓地力取决于法向载荷、滑移、温度、胎压、路面与橡胶状态；工程师必须把瞬态响应、热窗口和磨耗一起考虑，而不能只追求单个峰值。', 'Tyres are the car’s only interface for longitudinal force, lateral force and support load, and its strongest nonlinearity. Grip depends on normal load, slip, temperature, pressure, surface and rubber condition; engineers must balance transient response, thermal window and wear rather than chase one peak value.'),
    subcomponents: [l('胎面与胶料', 'Tread and compound'), l('带束层与胎体', 'Belt and carcass'), l('胎圈', 'Bead'), l('内衬与气腔', 'Liner and air cavity'), l('轮辋', 'Rim'), l('温度与压力传感', 'Temperature and pressure sensing')],
    concepts: [l('轮胎力随滑移先增加后饱和；峰值附近的斜率已经很小，因此驾驶和控制系统需要留出稳定裕量。', 'Tyre force rises with slip and then saturates; slope is already small near the peak, so driving and control need stability margin.'), l('轮胎具有载荷敏感性：法向载荷翻倍时可用摩擦力通常少于翻倍，因此横向载荷转移会降低整轴总抓地力。', 'Tyres are load-sensitive: doubling normal load normally gives less than double force, so lateral load transfer reduces total axle grip.'), l('胎压决定胎体刚度与接地形状，温度改变胶料黏弹性；冷态压力必须用热态目标和赛段能量反推。', 'Pressure sets carcass stiffness and footprint shape while temperature changes compound viscoelasticity; cold pressure must be derived from hot targets and stint energy.')],
    formulas: [f('纵向滑移率', 'Longitudinal slip ratio', 'κ = (Rω − Vx) / max(|Rω|, |Vx|)', 'R 为有效滚动半径；ω 为轮速；Vx 为轮胎坐标系纵向轮心速度；本页规定驱动为正', 'R effective rolling radius; ω wheel speed; Vx wheel-centre longitudinal speed in tyre axes; this page defines drive as positive', '不同轮胎模型可能采用不同分母与符号；低速区还必须设置速度阈值以避免数值发散。', 'Tyre models may use different denominators and signs; low-speed logic also needs a velocity threshold to avoid divergence.'), f('侧偏角', 'Slip angle', 'α = atan2(Vy, |Vx|) − δ', 'Vx、Vy 先在车体坐标表示，δ 为车轮相对车体转角；本页以“速度方向减车轮指向”为正负定义', 'Vx and Vy are first expressed in vehicle axes and δ is wheel heading relative to body; this page defines sign as velocity direction minus wheel heading', '文献常见相反符号，因此与轮胎力方向、坐标系和测试数据对接前必须统一约定。', 'The opposite sign is common in literature, so coordinate, force and test-data conventions must be aligned before use.'), f('摩擦椭圆近似', 'Friction-ellipse approximation', '(Fx / Fx,max)² + (Fy / Fy,max)² ≤ 1', 'Fx、Fy 为同一轮胎坐标系的纵横向力；极限随载荷、滑移、外倾、温度与路面变化', 'Fx and Fy are in the same tyre axes; limits vary with load, slip, camber, temperature and surface', '这是合力能力的教学包络，不是通用轮胎本构模型；真实组合滑移需用试验图谱标定。', 'This is a teaching envelope, not a universal tyre constitutive model; real combined slip requires test-map calibration.')],
    experiments: [e('滑移扫描', 'Slip sweep', '最大制动力出现在锁死前还是锁死后？', 'Does maximum braking force occur before or after lock-up?', [['固定载荷、温度和胎压。', 'Hold load, temperature and pressure.'], ['从零逐步增加负滑移率。', 'Increase negative slip progressively.'], ['记录纵向力与轮胎功率损失。', 'Record longitudinal force and tyre power loss.']], '力在有限滑移处达到峰值，完全锁死通常越过峰值并失去转向能力。', 'Force peaks at finite slip; full lock-up normally passes the peak and removes steering authority.'), e('载荷转移', 'Load transfer', '把同样总载荷从均匀分配变为偏载会怎样？', 'What happens when the same total load becomes uneven?', [['保持两轮总法向载荷不变。', 'Hold total normal load on two tyres.'], ['逐步增加内外轮载荷差。', 'Increase inside/outside load difference.'], ['比较两轮横向力之和。', 'Compare the sum of lateral forces.']], '因为载荷敏感性，偏载越大，总横向能力通常越低，这正是控制侧倾刚度分配的重要原因。', 'Because of load sensitivity, greater imbalance normally reduces total lateral capacity; this drives roll-stiffness distribution decisions.')],
    decisions: [l('用轮胎试验数据建立载荷、侧偏、外倾、温度和压力的联合模型，并记录适用范围。', 'Build a combined load, slip, camber, temperature and pressure model from tyre-test data and record its validity range.'), l('将热态胎压、胎面内中外温度与圈速阶段关联，而不是用单次停车读数下结论。', 'Relate hot pressure and inner/middle/outer tread temperature to lap phase rather than relying on one pit reading.'), l('悬架几何、空气动力平衡和制动控制都必须围绕轮胎工作窗口协同设计。', 'Suspension geometry, aero balance and brake control must be co-designed around the tyre window.')],
    validation: [l('在轮胎台或可信数据集中验证纯纵向、纯横向、联合滑移、外倾与载荷扫描。', 'Validate pure longitudinal, pure lateral, combined slip, camber and load sweeps on a rig or trusted dataset.'), l('赛道上同步记录压力、轮速、温度、载荷代理量与驾驶输入，进行模型残差分析。', 'Log pressure, wheel speed, temperature, load proxies and driver inputs synchronously on track and analyse model residuals.')],
    diagnostics: [d('外侧胎肩过热', 'Outer shoulder overheats', '连续弯后外侧温度显著高于中部和内侧，并伴随推头。', 'After sustained corners the outer shoulder is much hotter than centre and inner tread, with understeer.', [['核对动态外倾与侧倾。', 'Check dynamic camber and roll.'], ['检查热态压力与温度测量时刻。', 'Check hot pressure and measurement timing.'], ['比较左右弯和不同速度弯。', 'Compare left/right and different-speed corners.']], '若高载荷弯持续压外肩，增加合适负外倾或控制侧倾；若中部也偏热，先检查压力。', 'If high-load corners overwork the outer shoulder, add suitable negative camber or control roll; if the centre is also hot, inspect pressure first.'), d('制动轮速振荡', 'Oscillating wheel speed under braking', '临界制动时单轮滑移在峰值两侧快速往复。', 'One wheel oscillates across the peak-slip region under threshold braking.', [['检查路面颠簸与轮速信号。', 'Inspect bumps and wheel-speed signal.'], ['比较阻尼、轮胎垂向载荷与制动压力。', 'Compare damping, vertical load and brake pressure.'], ['检查控制器延迟或驾驶踏板调制。', 'Check controller delay or pedal modulation.']], '先区分真实轮跳与信号噪声，再调整阻尼、制动平衡或控制带宽。', 'Separate real wheel hop from signal noise before changing damping, brake balance or control bandwidth.')],
    references: [RCVD, FSG, { title: 'Calspan — Tire Research Facility', url: 'https://www.calspan.com/automotive/tire-performance-testing' }],
  },
  brakes: {
    labKind: 'brake',
    overview: l('制动系统把驾驶员踏板输入转化为四轮可控摩擦力，并把车辆动能主要转化为制动盘、制动片和空气中的热。赛车制动设计同时受法规双回路、踏板人机、液压比例、轮胎极限、空气动力载荷迁移、热容量、冷却与可靠性约束。', 'The brake system converts pedal input into controllable tyre forces and turns vehicle kinetic energy mainly into heat in discs, pads and air. Race brake design is constrained by dual-circuit rules, pedal ergonomics, hydraulic ratio, tyre limits, aero load migration, thermal capacity, cooling and reliability.'),
    subcomponents: [l('踏板与平衡杆', 'Pedal and balance bar'), l('双主缸', 'Dual master cylinders'), l('管路与制动液', 'Lines and brake fluid'), l('卡钳与活塞', 'Caliper and pistons'), l('制动盘与钟形座', 'Disc and bell'), l('制动片与冷却风道', 'Pads and cooling ducts')],
    concepts: [l('制动平衡必须匹配减速时的动态轴荷；前轮过早锁死损失转向，后轮过早锁死会迅速降低方向稳定性。', 'Brake balance must follow dynamic axle load; early front lock loses steering, while early rear lock rapidly reduces directional stability.'), l('单次制动由热容量主导，连续制动由散热能力主导；最高温度、温度梯度和热循环共同决定寿命。', 'Heat capacity governs one stop, cooling governs repeated stops; peak temperature, gradients and thermal cycles jointly determine life.'), l('踏板行程不仅由液体压缩决定，还包含管路膨胀、卡钳与支架变形、制动片压缩和盘面跳动回推。', 'Pedal travel includes line expansion, caliper and mount compliance, pad compression and knock-back, not just fluid compression.')],
    formulas: [f('理想主缸压力', 'Ideal master-cylinder pressure', 'p = Fpedal · Rp / Am', 'Rp 为踏板力机械比；Am 为主缸有效面积；本式忽略摩擦、助力、管路柔度与前后平衡机构差异', 'Rp pedal-force mechanical ratio; Am effective master-cylinder area; the equation neglects friction, assistance, line compliance and balance-bar differences', '同样踏板力下，小主缸提高压力但增加行程；双主缸系统必须分别计算前后回路。', 'A smaller master cylinder raises pressure but adds travel; dual-master systems require separate front and rear calculations.'), f('车轮制动矩', 'Wheel brake torque', 'Tb = μpad · p · Ap · Re · N', 'Ap 定义为作用在单侧制动片上的活塞总面积；Re 为有效摩擦半径；N=2 计入盘的两侧摩擦面', 'Ap is total piston area acting on one pad side; Re is effective friction radius; N=2 accounts for the two disc friction faces', '必须保持活塞面积与摩擦面计数定义一致，避免对置活塞卡钳重复乘二；摩擦系数还随温度、压力和速度变化。', 'Keep piston-area and friction-face definitions consistent to avoid double-counting opposed pistons; friction also varies with temperature, pressure and speed.'), f('制动能量', 'Braking energy', 'E = ½m(V1² − V2²)', 'm 为车辆等效平动质量；若需高精度，应加入旋转部件等效惯量及回收制动分担', 'm is equivalent translational mass; higher accuracy includes rotating inertia and regenerative-braking share', '该式给出车辆动能变化，不等于单个制动盘吸收的热量；前后分配、空气阻力和回收能量必须另计。', 'This is vehicle kinetic-energy change, not heat in one disc; axle split, aerodynamic drag and regeneration must be allocated separately.')],
    experiments: [e('平衡杆扫描', 'Brake-bias sweep', '前后制动力怎样决定稳定性和停车距离？', 'How does front/rear force split set stability and stopping distance?', [['设定轮胎、轴距和重心。', 'Set tyres, wheelbase and centre of gravity.'], ['从偏前逐步移向偏后。', 'Sweep from front-heavy toward rear-heavy.'], ['观察锁止顺序、减速度和偏航裕量。', 'Observe lock sequence, deceleration and yaw margin.']], '最佳区域让前后轮接近同时利用极限，但保留后轴稳定裕量并覆盖载荷与路面变化。', 'The best region uses both axles near their limits while retaining rear stability margin across load and surface variation.'), e('重复制动热衰退', 'Repeated-stop fade', '为什么第一脚正常而第五脚变长？', 'Why is the first stop normal but the fifth pedal is long?', [['输入连续高速制动事件。', 'Apply repeated high-speed stops.'], ['改变盘质量、风量与间隔。', 'Change disc mass, airflow and interval.'], ['跟踪盘温、片温和液温。', 'Track disc, pad and fluid temperature.']], '盘片摩擦衰退改变所需压力，液体沸腾或系统柔度增加会加长踏板；二者症状相似但证据不同。', 'Pad/disc fade raises required pressure, while boiling or compliance lengthens the pedal; symptoms overlap but evidence differs.')],
    decisions: [l('从轮胎可用力和动态轴荷反推车轮制动矩，再设计主缸、卡钳、盘径与踏板比。', 'Derive wheel torque from tyre force and dynamic axle load before sizing master cylinders, calipers, discs and pedal ratio.'), l('为最高能量事件和完整耐久赛分别建立瞬态与稳态热模型。', 'Build transient and steady thermal models for the highest-energy event and full endurance run.'), l('设置可检查的双回路、机械限位、防泄漏布置与赛前排气流程。', 'Implement inspectable dual circuits, mechanical stops, leak-resistant routing and pre-run bleeding procedures.')],
    validation: [l('测量踏板力—压力—卡钳力—车轮矩完整传递链，并记录滞回。', 'Measure the full pedal-force to pressure, clamp-force and wheel-torque chain including hysteresis.'), l('进行低速功能、渐进锁止、高能量单次制动和重复热循环测试。', 'Run low-speed function, progressive lock, high-energy stop and repeated thermal-cycle tests.')],
    diagnostics: [d('踏板逐圈变长', 'Pedal lengthens each lap', '制动力仍存在，但踏板接合点逐步下降。', 'Braking remains, but the pedal engagement point progressively drops.', [['检查制动液温度与含水。', 'Check fluid temperature and moisture.'], ['检查盘面跳动和轮毂轴承间隙。', 'Check disc runout and hub bearing play.'], ['检查泄漏、软管膨胀与排气。', 'Inspect leaks, hose expansion and bleeding.']], '若冷却后恢复且无泄漏，重点排查液体沸腾或热回推；更换液体前仍要修正热源和机械原因。', 'If it recovers when cool without leakage, investigate boiling or thermal knock-back; correct the thermal/mechanical cause as well as fluid.'), d('入弯后轴不稳定', 'Rear instability on entry', '直线重刹尚可，但带转向减速时车尾突然活跃。', 'Straight braking is acceptable, but the rear becomes suddenly active while trail braking.', [['检查机械与再生制动总平衡。', 'Check total mechanical and regenerative balance.'], ['比较前后轮滑移与轴荷。', 'Compare axle slip and load.'], ['检查后轮左右压力与悬架顺从。', 'Check left/right rear pressure and suspension compliance.']], '增加后轴稳定裕量并校正左右一致性；不要只靠驾驶员减小踏板力掩盖系统问题。', 'Add rear stability margin and correct side-to-side consistency; do not mask a system fault with driver adaptation.')],
    references: [FSG, { title: 'AP Racing — Brake System Technical Information', url: 'https://apracing.com/race-car/brake-calipers/technical-information' }, RCVD],
  },
  'front-suspension': {
    labKind: 'suspension',
    overview: l('前悬架决定转向轮的运动轨迹、轮胎姿态和前轴载荷响应。它要在有限空间内同时处理轮跳、侧倾、俯仰、转向、制动力、空气动力载荷与路面冲击，并把几何目标转化成刚度足够、可制造和可调的连杆与摇臂系统。', 'Front suspension sets steered-wheel paths, tyre attitude and front-axle load response. In limited space it must handle heave, roll, pitch, steer, braking, aero load and road impact, translating geometry targets into stiff, manufacturable and adjustable links and rockers.'),
    subcomponents: [l('上下控制臂', 'Upper and lower control arms'), l('转向节与轮毂', 'Upright and hub'), l('推杆或拉杆', 'Pushrod or pullrod'), l('摇臂与弹簧阻尼器', 'Rocker, spring and damper'), l('防倾杆', 'Anti-roll bar'), l('球铰与硬点', 'Rod ends and hardpoints')],
    concepts: [l('外倾增益、主销轴线、后倾和拖距共同决定轮胎姿态、转向力矩和回正；几何指标不能互相孤立优化。', 'Camber gain, kingpin axis, caster and trail jointly determine tyre attitude, steering torque and return; geometry targets cannot be optimised independently.'), l('运动比把轮端位移与弹簧、阻尼器和防倾杆联系起来，并以平方关系影响轮端刚度。', 'Motion ratio connects wheel motion to spring, damper and anti-roll bar and affects wheel stiffness through a square relation.'), l('顺从转向和衬套/连杆变形在高制动与高下压力时可能超过静态几何变化，必须纳入整车模型。', 'Compliance steer and link deformation under braking and downforce can exceed static geometry changes and must enter the vehicle model.')],
    formulas: [f('轮端刚度', 'Wheel rate', 'kw = ks · MR²', 'MR = 弹簧位移 / 轮端位移；ks 为弹簧刚度', 'MR = spring travel / wheel travel; ks spring rate', '运动比沿行程变化会形成渐增或渐减轮端刚度。', 'A changing motion ratio creates rising- or falling-rate wheel stiffness.'), f('固有频率', 'Natural frequency', 'fn = (1 / 2π) · √(kw / ms)', 'ms 为该轮支承的簧载质量；初算忽略轮胎与阻尼', 'ms supported sprung mass at that corner; first estimate neglects tyre and damping', '频率用于比较平台响应，不等同于圈速目标；轮胎刚度与空气动力会改变实际模态。', 'Frequency compares platform response, not lap-time directly; tyre stiffness and aero modify real modes.'), f('阻尼比', 'Damping ratio', 'ζ = c / (2√(kw · ms))', 'c 为等效轮端阻尼系数', 'c equivalent damping at the wheel', '阻尼器具有速度相关和压缩/回弹不对称特性，单一 ζ 只用于局部线性理解。', 'Dampers are velocity-dependent and asymmetric; one ζ is only a local linear view.')],
    experiments: [e('外倾曲线', 'Camber curve', '车身侧倾时外侧轮如何保持接地？', 'How does the outside tyre retain contact during roll?', [['改变上下控制臂硬点。', 'Change control-arm hardpoints.'], ['扫描轮跳与车身侧倾。', 'Sweep wheel travel and body roll.'], ['记录外倾、轮距和侧倾中心。', 'Record camber, track and roll centre.']], '更多外倾增益可补偿侧倾，但过大可能损害制动接地、直线磨耗与几何稳定性。', 'More camber gain can offset roll, but too much harms braking footprint, straight wear and geometric stability.'), e('路肩输入', 'Kerb input', '弹簧与阻尼怎样控制轮胎贴地？', 'How do spring and damping keep the tyre in contact?', [['施加单轮台阶或正弦路面。', 'Apply a one-wheel step or sine road input.'], ['扫描弹簧和高速压缩阻尼。', 'Sweep spring and high-speed compression damping.'], ['比较轮胎载荷波动与车身加速度。', 'Compare tyre-load variation and body acceleration.']], '过硬会让载荷波动增大，过软会耗尽行程或破坏平台；最佳值取决于路面与空气动力敏感度。', 'Too stiff increases load variation; too soft consumes travel or loses platform control. Optimum depends on surface and aero sensitivity.')],
    decisions: [l('从轮胎外倾需求、空气动力平台和载荷工况定义几何包络，再确定硬点。', 'Define geometry envelope from tyre camber need, aero platform and load cases before fixing hardpoints.'), l('把弹簧、防倾杆、轮胎与车架共同组成的整车滚转刚度分配到前后轴。', 'Allocate total roll stiffness from springs, bars, tyres and chassis across the axles.'), l('对连杆屈曲、球铰角度、摇臂轴承和硬点局部刚度进行载荷路径验证。', 'Validate link buckling, rod-end articulation, rocker bearings and local hardpoint stiffness.')],
    validation: [l('用运动学与顺从性台架测量前束、外倾、主销参数和轮端刚度随行程/载荷的变化。', 'Use a K&C rig to measure toe, camber, steering-axis parameters and wheel stiffness versus travel and load.'), l('在路面输入和赛道数据中关联阻尼器位移、轮胎载荷代理量、方向盘与车身运动。', 'Correlate damper travel, tyre-load proxies, steering and body motion over rig and track inputs.')],
    diagnostics: [d('制动时前束突变', 'Toe changes under braking', '静态前束正确，但重刹时方向不稳且左右轮滑移不同。', 'Static toe is correct, but heavy braking is unstable with different left/right slip.', [['检查控制臂和转向拉杆顺从。', 'Inspect control-arm and tie-rod compliance.'], ['测量轮毂轴承与球铰间隙。', 'Measure hub-bearing and joint play.'], ['对比制动力下的动态前束。', 'Compare dynamic toe under brake force.']], '修正柔度或载荷路径并重新做 K&C；静态调前束不能消除载荷下的顺从转向。', 'Correct compliance or load path and repeat K&C; static toe cannot remove load-induced compliance steer.'), d('单轮连续触底', 'One corner repeatedly bottoms', '高速弯或路肩后只有一个前角出现行程极限痕迹。', 'Only one front corner shows travel-limit evidence after fast corners or kerbs.', [['核对弹簧、预载与车高。', 'Check spring, preload and ride height.'], ['检查摇臂比与阻尼器气压。', 'Inspect rocker ratio and damper gas pressure.'], ['比较下压力与防倾杆载荷。', 'Compare downforce and anti-roll-bar load.']], '先排除装配和左右差异，再用行程预算调整弹簧、缓冲块或平台目标。', 'Eliminate assembly asymmetry before changing springs, bump stops or platform target using a travel budget.')],
    references: [RCVD, FSG, { title: 'OptimumG — Suspension Kinematics and Compliance', url: 'https://optimumg.com/' }],
  },
  'rear-suspension': {
    labKind: 'suspension',
    overview: l('后悬架控制驱动轮姿态、牵引、后轴侧向能力和空气动力平台。除了与前悬架相同的轮跳与侧倾问题，它还必须处理驱动扭矩、半轴几何、差速器布置和动力系统质量，使车辆在出弯和极限瞬态中既有抓地又可预测。', 'Rear suspension controls driven-wheel attitude, traction, rear lateral capacity and aero platform. Beyond front-suspension heave and roll duties, it handles drive torque, half-shaft geometry, differential packaging and powertrain mass so corner exit and limit transients remain grippy and predictable.'),
    subcomponents: [l('上下控制臂', 'Upper and lower control arms'), l('后立柱与轮毂', 'Rear upright and hub'), l('推杆/拉杆与摇臂', 'Push/pull rod and rocker'), l('弹簧阻尼器', 'Spring and damper'), l('后防倾杆', 'Rear anti-roll bar'), l('半轴与等速节', 'Half-shafts and CV joints')],
    concepts: [l('后轴前束随压缩和驱动力变化会显著影响极限稳定性；压缩时轻微前束增加通常稳定，但会增加阻力与温度。', 'Rear toe change with bump and drive force strongly affects limit stability; modest toe-in in bump is often stabilising but adds drag and temperature.'), l('抗蹲几何能通过连杆力分担俯仰，但过高会带来轮胎载荷突变、顶升和路面顺应性下降。', 'Anti-squat geometry shares pitch load through links, but too much causes abrupt tyre load, jacking and poorer road compliance.'), l('后滚转刚度增加通常提高车辆旋转能力，却也因轮胎载荷敏感性降低后轴总抓地。', 'Increasing rear roll stiffness often improves rotation but reduces total rear grip through tyre load sensitivity.')],
    formulas: [f('轮端刚度', 'Wheel rate', 'kw = ks · MR²', 'MR 为弹簧位移与轮端位移之比；ks 为弹簧切线刚度', 'MR is spring-travel to wheel-travel ratio; ks is spring tangent rate', '运动比和非线性弹簧都可能随行程变化，因此应在完整后轮行程上计算切线轮端刚度。', 'Motion ratio and nonlinear spring rate can vary with travel, so tangent wheel rate should be evaluated through full rear travel.'), f('后轴弹性载荷转移', 'Rear elastic load transfer', 'ΔFz,rear,el ≈ (Kφ,rear / Kφ,total) · ms·ay·hr / tr', 'Kφ 为弹性滚转刚度；ms 为簧载质量；hr 为簧载重心到滚转轴的等效力臂；tr 为后轮距', 'Kφ elastic roll stiffness; ms sprung mass; hr effective sprung-CG-to-roll-axis arm; tr rear track', '这是后轴弹性分量的简化分配式；总载荷转移还必须加入几何滚转中心、簧下质量、前后不同轮距和轮胎柔度。', 'This is a simplified rear elastic component; total transfer also includes geometric roll-centre, unsprung-mass, unequal-track and tyre-compliance effects.'), f('半轴角速度功率', 'Half-shaft power', 'P = Tshaft · ωshaft', 'Tshaft 与 ωshaft 必须取同一截面、同一时刻且符号约定一致', 'Tshaft and ωshaft must refer to the same section and instant with a consistent sign convention', '等速节角度和悬架行程会影响损失、温度与寿命；瞬时高功率也不等于持续热负荷。', 'CV angle and suspension travel affect loss, temperature and life; high instantaneous power is not continuous thermal load.')],
    experiments: [e('后防倾杆扫描', 'Rear anti-roll sweep', '增加后滚转刚度为什么更容易转向？', 'Why can more rear roll stiffness make the car rotate?', [['保持总横向加速度相同。', 'Hold total lateral acceleration.'], ['逐步增加后防倾杆刚度。', 'Increase rear bar stiffness.'], ['观察内外轮载荷与前后轴余量。', 'Observe inside/outside loads and axle margins.']], '后轴载荷差增加后，后轮总横向余量下降，车辆更愿意旋转；过量会导致突然过度转向。', 'Greater rear load difference reduces total rear lateral margin and promotes rotation; too much creates abrupt oversteer.'), e('抗蹲扫描', 'Anti-squat sweep', '几何能否免费消除加速抬头？', 'Can geometry remove acceleration pitch for free?', [['改变侧视图瞬心高度。', 'Change side-view instant-centre height.'], ['施加相同驱动轮力。', 'Apply the same driven-wheel force.'], ['比较车身俯仰、轮胎载荷瞬态和连杆力。', 'Compare pitch, tyre-load transient and link force.']], '抗蹲减少弹簧压缩，却把力更直接传给车架与轮胎；它改变路径而不是消除载荷转移。', 'Anti-squat reduces spring compression but sends force more directly into chassis and tyre; it redirects rather than removes load transfer.')],
    decisions: [l('以出弯牵引、极限稳定和空气动力车高共同定义后轴前束、外倾与滚转刚度。', 'Set rear toe, camber and roll stiffness from corner-exit traction, limit stability and aero ride height together.'), l('检查半轴在全行程与转角中的等速节角度、插入量和干涉。', 'Check CV angle, plunge and interference over full travel and steering.'), l('用驱动、制动、侧向和路肩组合载荷设计连杆与硬点。', 'Design links and hardpoints for combined drive, brake, lateral and kerb loads.')],
    validation: [l('K&C 验证后轮前束、外倾、轮端刚度和驱动/制动力顺从。', 'Use K&C to validate rear toe, camber, wheel rate and drive/brake compliance.'), l('赛道关联轮速差、油门/扭矩、阻尼器行程、偏航率和轮胎温度。', 'Correlate wheel-speed difference, throttle/torque, damper travel, yaw rate and tyre temperature on track.')],
    diagnostics: [d('出弯单侧轮跳', 'One-wheel hop on exit', '大扭矩出弯时内后轮轮速和阻尼器速度周期振荡。', 'The inside rear wheel speed and damper velocity oscillate under high torque on exit.', [['同步检查轮速、阻尼器和扭矩。', 'Synchronise wheel speed, damper and torque.'], ['检查轮胎载荷、防倾杆和差速设定。', 'Inspect tyre load, anti-roll bar and differential setting.'], ['检查半轴和衬套/硬点柔度。', 'Inspect half-shaft and joint/hardpoint compliance.']], '在区分轮胎黏滑与结构共振后，协调阻尼、滚转刚度、差速与扭矩斜率。', 'After separating tyre stick-slip from structural resonance, coordinate damping, roll stiffness, differential and torque ramp.'), d('高速后轴漂移', 'Rear axle wanders at speed', '直线高速时方向需要持续修正，低速检查正常。', 'Continuous steering correction is needed at high speed although low-speed checks are normal.', [['测量下压力下的动态前束。', 'Measure dynamic toe under downforce.'], ['检查车高与底板失速。', 'Check ride height and floor stall.'], ['检查轮毂轴承、硬点和轮胎压力。', 'Inspect bearings, hardpoints and tyre pressure.']], '优先排查空气动力载荷下的顺从前束和平台变化，再处理静态定位。', 'Prioritise compliance toe and platform change under aero load before static alignment.')],
    references: [RCVD, FSG],
  },
  steering: {
    labKind: 'steering',
    overview: l('转向系统把驾驶员的角度和力矩输入传到前轮，同时把轮胎自对准力矩、路面冲击和抓地状态反馈给驾驶员。它由几何、传动比、刚度、间隙、人机和安全约束共同决定；目标是精确、线性、低摩擦并在全行程无干涉。', 'The steering system transmits driver angle and torque to the front wheels while returning tyre self-aligning torque, road impact and grip information. Geometry, ratio, stiffness, backlash, ergonomics and safety jointly set its behaviour; the target is precise, linear, low-friction and interference-free through full travel.'),
    subcomponents: [l('方向盘与快拆', 'Steering wheel and quick release'), l('转向柱与万向节', 'Column and universal joints'), l('齿条齿轮', 'Rack and pinion'), l('转向拉杆', 'Tie rods'), l('转向臂', 'Steering arms'), l('限位与支承轴承', 'Stops and support bearings')],
    concepts: [l('阿克曼几何让内轮在低速小半径转弯时具有更大转角，但高速轮胎侧偏和载荷会改变最佳关系。', 'Ackermann gives the inside wheel more angle in tight low-speed turns, but tyre slip and load alter the high-speed optimum.'), l('机械拖距、主销偏距与轮胎气动拖距共同产生方向盘力矩和回正，也会把制动力不对称反馈到驾驶员。', 'Mechanical trail, scrub radius and pneumatic trail create steering torque and return, and feed brake-force asymmetry back to the driver.'), l('悬架跳动引起的非指令前束称为 bump steer；很小的几何误差也可能在高速形成明显偏航输入。', 'Uncommanded toe from suspension travel is bump steer; tiny geometry errors can create significant yaw input at speed.')],
    formulas: [f('理想阿克曼关系', 'Ideal Ackermann relation', 'cot(δo) − cot(δi) = t / L', 'δo、δi 为外、内轮绝对转角；t 为前轮距；L 为轴距；两轮假定无侧偏并指向同一瞬心', 'δo and δi are absolute outer/inner angles; t is front track; L wheelbase; both tyres are assumed zero-slip and point to one instantaneous centre', '这是低速几何基准；高速最佳转角差还取决于轮胎载荷敏感性、外倾、顺从性和目标侧偏角。', 'This is a low-speed geometric reference; high-speed optimum also depends on tyre load sensitivity, camber, compliance and target slip angles.'), f('平均转向比', 'Average steering ratio', 'is = Δθwheel / Δδroadwheel', 'θwheel 为方向盘转角；δroadwheel 为所声明的平均车轮转角；有限差分给出区间平均值', 'θwheel steering-wheel angle; δroadwheel is the declared average road-wheel angle; finite differences give a range average', '非线性齿条或转向臂会使瞬时比随行程变化，因此必须同时检查角度—齿条—车轮完整曲线。', 'A nonlinear rack or steering arm varies instantaneous ratio with travel, so the full steering-wheel/rack/road-wheel map must also be checked.'), f('小齿轮扭矩', 'Pinion torque', 'Tpinion ≈ Frack · rp', 'Frack 为齿条轴向力；rp 为小齿轮节圆半径；理想式忽略啮合、密封和轴承损失', 'Frack rack axial force; rp pinion pitch radius; the ideal relation neglects mesh, seal and bearing losses', '这是小齿轮轴扭矩，不是“齿条力矩”；驾驶员方向盘扭矩还需通过转向柱传动比和效率换算。', 'This is pinion-shaft torque, not rack torque; driver steering-wheel torque still requires column ratio and efficiency.')],
    experiments: [e('阿克曼扫描', 'Ackermann sweep', '内外轮转角差怎样影响低速与高速？', 'How does inner/outer angle split affect low and high speed?', [['设定轴距、轮距和转弯半径。', 'Set wheelbase, track and corner radius.'], ['改变转向臂交点。', 'Change steering-arm convergence.'], ['比较几何误差与轮胎侧偏需求。', 'Compare geometric error and tyre slip demand.']], '理想阿克曼适合低速基准，高速最优值需结合轮胎载荷敏感性与侧偏刚度。', 'Ideal Ackermann is a low-speed baseline; high-speed optimum needs tyre load sensitivity and cornering stiffness.'), e('Bump steer', 'Bump steer', '直线压缩悬架为什么会让车转向？', 'Why can straight suspension compression steer the car?', [['锁定方向盘。', 'Lock the steering wheel.'], ['扫描左右轮跳与车身升沉。', 'Sweep individual bump and body heave.'], ['记录前束变化和等效偏航输入。', 'Record toe change and equivalent yaw input.']], '拉杆内外点相对控制臂瞬心的位置决定曲线；应在真实顺从和车高范围内验证。', 'Tie-rod location relative to control-arm instant centres sets the curve; validate over real compliance and ride-height range.')],
    decisions: [l('从最大横向加速度、驾驶员力矩和手部动作范围确定转向比与方向盘尺寸。', 'Set steering ratio and wheel size from peak lateral acceleration, driver torque and hand-motion range.'), l('将阿克曼、bump steer、主销偏距、拖距与包装作为同一几何优化问题。', 'Optimise Ackermann, bump steer, scrub radius, trail and packaging as one geometry problem.'), l('所有连接必须有可靠防松、机械限位和在悬架全行程下的间隙证明。', 'All connections need positive retention, mechanical stops and clearance evidence through full suspension travel.')],
    validation: [l('台架测量方向盘角—齿条位移—左右轮角、力矩、摩擦、间隙和滞回。', 'Bench-measure wheel angle, rack travel, road-wheel angles, torque, friction, backlash and hysteresis.'), l('K&C 和赛道验证 bump steer、制动回馈、回正与高速小输入响应。', 'Validate bump steer, brake feedback, return and high-speed small-input response on K&C and track.')],
    diagnostics: [d('方向盘中心漂移', 'Steering centre drifts', '几圈后直线方向盘位置改变，但定位初始值正常。', 'Straight-ahead wheel position changes after several laps although initial alignment is correct.', [['标记并检查快拆、花键和拉杆锁紧。', 'Witness-mark quick release, splines and tie-rod locks.'], ['测量温态前束和轮毂间隙。', 'Measure hot toe and hub play.'], ['检查齿条安装与车架柔度。', 'Inspect rack mounting and chassis compliance.']], '任何机械滑移必须立即停驶；若无滑移，再定位热变形或顺从前束来源。', 'Stop immediately for any mechanical slip; otherwise locate thermal deformation or compliance-toe source.'), d('左右转向力不对称', 'Asymmetric steering effort', '相同速度和半径下，一个方向明显更重。', 'One direction is noticeably heavier at the same speed and radius.', [['检查主销、后倾、胎压与角重。', 'Check kingpin geometry, caster, pressure and corner weights.'], ['测量齿条摩擦和万向节相位。', 'Measure rack friction and universal-joint phasing.'], ['比较左右轮胎温度和制动拖滞。', 'Compare tyre temperature and brake drag.']], '用力矩分解区分轮胎、几何、摩擦和制动来源，避免用不对称定位抵消故障。', 'Separate tyre, geometry, friction and brake contributions; do not cancel a fault with asymmetric alignment.')],
    references: [RCVD, FSG],
  },
  battery: {
    labKind: 'battery',
    overview: l('高压蓄电池系统储存整车推进能量，并在功率、温度、电压和绝缘边界内向逆变器供电。它不仅是电芯集合，还包括模块结构、母排、保险、接触器、预充、绝缘监测、BMS、冷却和防火封装；任何性能优化都必须以可验证的电气安全为前提。', 'The high-voltage accumulator stores propulsion energy and feeds the inverter within power, temperature, voltage and insulation limits. It is more than cells: modules, busbars, fuse, contactors, precharge, insulation monitoring, BMS, cooling and fire-resistant enclosure form one safety system.'),
    subcomponents: [l('电芯与模块', 'Cells and modules'), l('母排与保险', 'Busbars and fuse'), l('主接触器与预充', 'Main contactors and precharge'), l('BMS/AMS', 'BMS/AMS'), l('绝缘监测器', 'Insulation monitor'), l('封装与冷却板', 'Enclosure and cooling plate')],
    concepts: [l('串联数量决定电压，电芯并联和容量决定电流与能量；最弱电芯会限制整个串联链。', 'Series count sets voltage while parallel capacity sets current and energy; the weakest cell limits the series string.'), l('电芯内阻随 SOC、温度和老化变化，高功率时的端电压下降与 I²R 发热会共同触发降额。', 'Cell resistance varies with SOC, temperature and ageing; voltage sag and I²R heat jointly trigger derating at high power.'), l('预充用电阻缓慢给逆变器直流母线电容充电，避免主接触器闭合时出现破坏性浪涌。', 'Precharge slowly fills inverter DC-link capacitance through a resistor, avoiding destructive inrush when main contactors close.')],
    formulas: [f('母线电能', 'DC-bus electrical energy', 'E = ∫ V(t)·I(t) dt', 'V 为包端电压；I 为包电流；必须声明充放电正负号并同步采样', 'V pack-terminal voltage; I pack current; charge/discharge sign and synchronized sampling must be declared', '积分得到的是所选电气边界的母线能量，不等于额定 Ah，也不等于电芯化学能变化。', 'The integral gives bus energy at the chosen electrical boundary, not rated Ah or cell chemical-energy change.'), f('库仑计量 SOC', 'Coulomb-counted SOC', 'SOC = SOC0 − (1 / Qn)∫ I(t) dt', 'Qn 与积分必须单位一致：若 Qn 用 Ah 且时间用秒，积分结果需除以 3600；本页规定放电电流为正', 'Qn and the integral need consistent units: with Qn in Ah and time in seconds, divide the integral by 3600; this page takes discharge current as positive', '传感器偏置会持续累积，仍需用静置电压、状态模型或可追溯满充事件校正漂移。', 'Sensor offset accumulates continuously, so rest voltage, state models or traceable full-charge events are needed to correct drift.'), f('不可逆欧姆发热', 'Irreversible ohmic heating', 'Q̇loss ≈ I²Rint', 'Rint 为给定温度、SOC、时间尺度和老化状态下的等效直流内阻', 'Rint is equivalent DC resistance at a stated temperature, SOC, time scale and ageing state', '该式只估算欧姆项，不是电池总发热；总热量还可能包含熵热、反应极化以及母排和连接件损耗。', 'This estimates only the ohmic term, not total battery heat; entropic heat, reaction polarization, busbar and interconnect losses may also contribute.')],
    experiments: [e('功率降额地图', 'Power-derating map', '相同油门请求为什么在低 SOC 或高温时输出不同？', 'Why does the same pedal request produce different output at low SOC or high temperature?', [['扫描 SOC 与最高电芯温度。', 'Sweep SOC and maximum cell temperature.'], ['施加相同功率请求。', 'Apply the same power request.'], ['观察电压下限、电流限值与可用功率。', 'Observe voltage floor, current limit and available power.']], '控制器取电芯电压、温度、接触器与绝缘约束的最严格限制，功率边界应平滑可预测。', 'The controller applies the tightest cell-voltage, temperature, contactor and insulation constraint; boundaries should be smooth and predictable.'), e('预充过程', 'Precharge sequence', '多大的电阻能兼顾时间和器件应力？', 'What resistance balances time and component stress?', [['设定母线电容与包电压。', 'Set DC-link capacitance and pack voltage.'], ['改变预充电阻。', 'Change precharge resistance.'], ['跟踪母线电压、电阻功率和闭合判据。', 'Track bus voltage, resistor power and closure threshold.']], '时间常数约为 RC；过小电阻浪涌大，过大则超时并让电阻积热。', 'The time constant is about RC; too little resistance causes inrush, too much causes timeout and resistor heating.')],
    decisions: [l('以耐久赛能量、峰值功率、最低电压与热裕量共同确定串并联拓扑。', 'Set series/parallel topology from endurance energy, peak power, minimum voltage and thermal margin.'), l('为每个电芯测量、接触器状态、绝缘故障和冷却故障定义独立安全响应。', 'Define independent safety responses for cell measurements, contactor state, insulation and cooling faults.'), l('封装设计必须同时覆盖振动、碰撞、爬电距离、电气间隙、维护互锁与泄压。', 'Enclosure design must cover vibration, crash, creepage, clearance, service interlock and venting.')],
    validation: [l('从电芯脉冲与容量测试扩展到模块热循环、振动、绝缘和整包故障注入。', 'Progress from cell pulse/capacity tests to module thermal cycling, vibration, insulation and pack fault injection.'), l('验证预充、断电、急停、绝缘故障、过温、欠压和传感器断线的确定性状态转换。', 'Validate deterministic state transitions for precharge, shutdown, emergency stop, insulation fault, overtemperature, undervoltage and open sensors.')],
    diagnostics: [d('加速时单体欠压', 'Cell undervoltage under acceleration', '静置电压正常，但大电流时一个串联组首先跌破阈值。', 'Rest voltage is normal, but one series group crosses the low limit first under high current.', [['比较各组电压降和温度。', 'Compare group voltage sag and temperature.'], ['核对采样线与连接电阻。', 'Check sense wiring and connection resistance.'], ['做受控脉冲内阻测试。', 'Run a controlled pulse-resistance test.']], '区分真实弱电芯、母排高阻和采样错误；在证据明确前保持功率降额。', 'Separate a weak cell, high-resistance joint and sensing error; keep derating until evidence is clear.'), d('预充超时', 'Precharge timeout', '母线电压上升后停在包电压以下，主接触器不闭合。', 'Bus voltage rises then stalls below pack voltage and main contactors remain open.', [['检查母线是否有异常负载或短路。', 'Check abnormal load or short on the bus.'], ['测量电阻、母线电容与电压传感。', 'Measure resistor, bus capacitance and voltage sensing.'], ['核对接触器辅助触点。', 'Check contactor auxiliary feedback.']], '禁止绕过预充强制闭合；定位泄漏负载、错误参数或失效器件后重新验证。', 'Never bypass precharge to force closure; locate leakage load, bad parameter or failed component and revalidate.')],
    references: [FSG, NREL, { title: 'NLR — Battery Lifespan Research', url: 'https://www.nlr.gov/transportation/battery-lifespan' }, BOSCH],
  },
  inverter: {
    labKind: 'inverter',
    overview: l('逆变器把电池直流电转换成幅值、频率和相位可控的三相交流，并通过电流闭环精确控制电机转矩。它同时承担开关调制、栅极驱动、直流母线管理、过流/过压保护、温度估算与再生能量回送，是电驱系统动态响应和效率的核心。', 'The inverter converts battery DC into controlled three-phase AC and regulates motor torque through current loops. Switching modulation, gate drive, DC-link management, overcurrent/overvoltage protection, temperature estimation and regenerative energy return make it central to powertrain response and efficiency.'),
    subcomponents: [l('功率模块', 'Power module'), l('栅极驱动', 'Gate drivers'), l('直流母线电容', 'DC-link capacitor'), l('电流与电压传感', 'Current and voltage sensing'), l('控制板与 FOC', 'Controller and FOC'), l('冷却底板', 'Cooling baseplate')],
    concepts: [l('PWM 用高速开关的平均值合成目标相电压；更高开关频率改善电流纹波，却增加开关损耗。', 'PWM synthesises phase voltage through high-speed switching averages; higher frequency reduces current ripple but raises switching loss.'), l('磁场定向控制把三相电流变换到转子坐标系，分别控制产生磁通的 d 轴和产生转矩的 q 轴。', 'Field-oriented control transforms three-phase current into rotor coordinates and controls flux-producing d-axis and torque-producing q-axis components.'), l('再生制动时功率流向电池；当电池不允许接收或母线电压升高时，逆变器必须立即限制负转矩。', 'During regeneration power flows to the battery; if charge acceptance is limited or bus voltage rises, negative torque must be curtailed immediately.')],
    formulas: [f('效率', 'Efficiency', 'ηinv = Pac,out / Pdc,in', '输入输出必须在同一稳态窗口测量并包含辅助功耗定义', 'Input and output must share a steady window with auxiliary-power scope defined', '高效率百分比仍可能对应数千瓦热量，冷却应按绝对损耗设计。', 'A high percentage can still mean kilowatts of heat; cooling is sized by absolute loss.'), f('开关损耗近似', 'Switching-loss estimate', 'Psw ≈ fsw · (Eon + Eoff) · Nswitch', '开通/关断能量随电压、电流和结温变化', 'Turn-on/off energy varies with voltage, current and junction temperature', '它解释了为何提高开关频率不能没有代价。', 'It explains why raising switching frequency is not free.'), f('电角频率', 'Electrical frequency', 'fe = p · nm / 60', 'p 为极对数；nm 为机械转速 rpm', 'p pole pairs; nm mechanical speed in rpm', '高速时控制采样、PWM 和位置估算必须保留足够带宽。', 'At high speed, control sampling, PWM and position estimation need sufficient bandwidth.')],
    experiments: [e('开关频率权衡', 'Switching-frequency trade-off', '频率越高是否总是越好？', 'Is a higher switching frequency always better?', [['保持转矩和转速不变。', 'Hold torque and speed.'], ['扫描 PWM 频率。', 'Sweep PWM frequency.'], ['比较电流纹波、开关损耗和结温。', 'Compare current ripple, switching loss and junction temperature.']], '纹波下降但开关热增加，最优点取决于电机电感、声学、效率和冷却。', 'Ripple falls but switching heat rises; optimum depends on motor inductance, acoustics, efficiency and cooling.'), e('再生限幅', 'Regeneration limiting', '满电或冷电池时制动感觉怎样保持一致？', 'How is braking kept consistent with a full or cold battery?', [['改变电池可接收功率。', 'Change battery charge acceptance.'], ['输入相同负转矩请求。', 'Request the same negative torque.'], ['观察母线电压与机械制动补偿。', 'Observe bus voltage and mechanical-brake compensation.']], '电驱负转矩必须受母线和电池约束，整车控制应平滑协调机械制动。', 'Electric negative torque must obey bus and battery constraints, with smooth vehicle-level mechanical-brake coordination.')],
    decisions: [l('用整车转矩—转速任务循环确定功率器件、电流余量、母线电容与冷却。', 'Use the vehicle torque-speed duty cycle to size devices, current margin, DC-link capacitance and cooling.'), l('硬件过流/短路保护必须独立于软件，并定义安全关断后的电机与母线状态。', 'Hardware overcurrent/short-circuit protection must be independent of software, with safe post-shutdown motor and bus states.'), l('控制器限值应与电池、电机和轮胎实时能力取最严格边界。', 'Controller limits should use the tightest real-time battery, motor and tyre boundary.')],
    validation: [l('台架绘制完整转矩—转速效率与温升地图，并覆盖低电压和高温边界。', 'Map efficiency and temperature over the torque-speed plane including low-voltage and high-temperature boundaries.'), l('进行传感器偏置、位置丢失、过流、冷却中断、通信超时和再生拒绝故障注入。', 'Inject sensor bias, position loss, overcurrent, cooling interruption, communication timeout and regen-rejection faults.')],
    diagnostics: [d('高转速转矩脉动', 'Torque ripple at high speed', '低速平顺，高速弱磁区出现周期性电流和转矩波动。', 'Operation is smooth at low speed but current and torque oscillate in field weakening.', [['检查转子角度质量与延迟。', 'Check rotor-angle quality and delay.'], ['检查电压饱和与电流环带宽。', 'Inspect voltage saturation and current-loop bandwidth.'], ['比较母线纹波和 PWM 余量。', 'Compare bus ripple and PWM margin.']], '校正角度、解耦和饱和处理；不能只用更强滤波掩盖控制相位问题。', 'Correct angle, decoupling and saturation handling; stronger filtering must not hide a control-phase fault.'), d('功率模块过温', 'Power module overheats', '相同机械功率下逆变器温度比历史数据上升更快。', 'Inverter temperature rises faster than historical data at the same mechanical power.', [['分解导通与开关损耗估算。', 'Separate conduction and switching estimates.'], ['检查冷却流量、界面与温度传感。', 'Inspect coolant flow, interface and sensing.'], ['核对相电流偏置和 PWM 频率。', 'Check phase-current offset and PWM frequency.']], '确认是真实热阻/损耗增加还是传感偏差，再按结温裕量降额。', 'Confirm increased thermal resistance/loss versus sensor bias, then derate by junction-temperature margin.')],
    references: [BOSCH, { title: 'Texas Instruments — Field-Oriented Control', url: 'https://www.ti.com/document-viewer/lit/html/SSZT667/GUID-6111C505-D59E-4F93-BADC-5ABE7021CE1C' }, NREL],
  },
  motor: {
    labKind: 'motor',
    overview: l('牵引电机把逆变器提供的电磁功率转换为轴端转矩和转速。赛车关注的不只是峰值功率，还包括扭矩—转速包络、连续热能力、效率地图、弱磁区、转子机械安全、位置传感和与减速比的系统匹配。', 'The traction motor converts inverter electromagnetic power into shaft torque and speed. Racing design concerns not only peak power but the torque-speed envelope, continuous thermal capacity, efficiency map, field weakening, rotor mechanical safety, position sensing and system gearing.'),
    subcomponents: [l('定子铁芯与绕组', 'Stator core and windings'), l('转子与永磁体', 'Rotor and magnets'), l('轴与轴承', 'Shaft and bearings'), l('旋变/编码器', 'Resolver or encoder'), l('壳体与冷却套', 'Housing and cooling jacket'), l('高压相线', 'High-voltage phase leads')],
    concepts: [l('基速以下通常受电流/转矩限制，基速以上受电压限制并通过负 d 轴电流弱磁，转矩随转速下降。', 'Below base speed the motor is normally current/torque-limited; above it voltage limits require negative d-axis field weakening and torque falls with speed.'), l('峰值能力只持续短时间；铜损、铁损、转子损耗和冷却热阻决定连续能力。', 'Peak capability is time-limited; copper, iron and rotor losses plus cooling thermal resistance set continuous performance.'), l('减速比同时改变轮上力、最高车速、电机工作点与效率，不能在电机选型之后才决定。', 'Gear ratio changes wheel force, top speed, motor operating point and efficiency, and cannot be chosen after motor selection.')],
    formulas: [f('机械功率', 'Mechanical power', 'Pmech = T · ω', 'T 为轴转矩；ω 为机械角速度', 'T shaft torque; ω mechanical angular speed', '同一功率下低速需要大转矩，高速需要大转速；器件限制不同。', 'The same power needs high torque at low speed and high speed at low torque; component limits differ.'), f('轮上牵引力', 'Wheel tractive force', 'Fx = Tmotor · ig · ηg / Rtire', 'ig 为总减速比；ηg 传动效率；Rtire 轮胎半径', 'ig total ratio; ηg drivetrain efficiency; Rtire tyre radius', '最终可用力还受轮胎附着和载荷限制。', 'Usable force remains limited by tyre grip and load.'), f('铜损', 'Copper loss', 'Pcu = 3 · Irms² · Rphase', '相电阻随绕组温度升高', 'Phase resistance rises with winding temperature', '低速大转矩区常由铜损主导，高速还要考虑铁损与风阻。', 'Copper often dominates low-speed high-torque operation; iron and windage grow at speed.')],
    experiments: [e('减速比选择', 'Gear-ratio selection', '更大的减速比一定让车更快吗？', 'Does a larger ratio always make the car faster?', [['设定电机包络与轮胎半径。', 'Set motor envelope and tyre radius.'], ['扫描总减速比。', 'Sweep total ratio.'], ['比较加速度、最高车速和效率分布。', 'Compare acceleration, top speed and efficiency distribution.']], '大速比提高低速轮上力但更早触及最高转速；最佳值取决于赛道速度分布和附着。', 'A larger ratio raises low-speed wheel force but reaches speed limit sooner; optimum depends on track speed distribution and grip.'), e('热持续能力', 'Thermal endurance', '峰值转矩能保持多久？', 'How long can peak torque be sustained?', [['输入耐久赛转矩—转速时间序列。', 'Apply an endurance torque-speed trace.'], ['改变冷却与初始温度。', 'Change cooling and initial temperature.'], ['跟踪绕组、转子和冷却液温度。', 'Track winding, rotor and coolant temperatures.']], '短暂峰值由电流和磁体限制，持续输出最终由热容量与散热达到的温度边界决定。', 'Short peaks are set by current and magnets; sustained output is eventually bounded by thermal capacity and heat rejection.')],
    decisions: [l('用整圈/耐久赛工作点而非单个峰值选择电机和减速比。', 'Select motor and ratio from full-lap/endurance operating points, not one peak.'), l('建立绕组、转子、轴承和冷却液多节点热模型并校准。', 'Build and calibrate a multi-node winding, rotor, bearing and coolant thermal model.'), l('验证最高转速下转子应力、轴承寿命、磁体保持和位置传感容错。', 'Validate rotor stress, bearing life, magnet retention and position-sensor tolerance at maximum speed.')],
    validation: [l('测功机覆盖正负转矩、完整转速、效率、温升和降额边界。', 'Dynamometer testing should cover positive/negative torque, full speed, efficiency, temperature rise and derating boundaries.'), l('将电机扭矩估算与轮端测功、车辆加速度和直流功率做能量一致性检查。', 'Cross-check estimated torque with wheel dynamometry, vehicle acceleration and DC power for energy consistency.')],
    diagnostics: [d('低速有力、高速无力', 'Strong low speed, weak high speed', '电流未超限但进入高速后转矩比模型下降更快。', 'Current is within limit, but torque falls faster than the model at high speed.', [['检查母线电压和电压利用率。', 'Check DC voltage and voltage utilisation.'], ['核对弱磁电流与转子角度。', 'Check field-weakening current and rotor angle.'], ['检查相电阻、磁链与温度参数。', 'Inspect phase resistance, flux and temperature parameters.']], '定位电压饱和、参数失配或电池压降，再修正控制与模型；不要盲目提高电流限值。', 'Locate voltage saturation, parameter mismatch or battery sag before correcting control/model; do not blindly raise current.'), d('轴承温度单独升高', 'Bearing temperature rises alone', '绕组和冷却液正常，但轴承附近温度与振动逐圈上升。', 'Windings and coolant are normal, but bearing-zone temperature and vibration rise each lap.', [['分析振动频谱与转速阶次。', 'Analyse vibration spectrum and speed orders.'], ['检查轴向/径向载荷与对中。', 'Check axial/radial load and alignment.'], ['检查润滑、密封与电蚀。', 'Inspect lubrication, seals and electrical erosion.']], '按机械故障处理并限制转速，确认对中、预载或电流回路问题后更换受损件。', 'Treat as a mechanical fault and limit speed; correct alignment, preload or current path before replacing damage.')],
    references: [BOSCH, NREL, { title: 'Oak Ridge National Laboratory — Electric Vehicle Research', url: 'https://www.ornl.gov/research-highlight/electric-vehicle-research-ornl' }],
  },
  differential: {
    labKind: 'differential',
    overview: l('差速器允许左右驱动轮在转弯时具有不同转速，同时决定可传递扭矩和由驱动产生的偏航特性。开放式、限滑与主动扭矩分配方案在牵引、转向、能耗、热、质量和规则复杂度之间取舍；设定必须与轮胎载荷和驾驶员扭矩请求联动。', 'The differential allows driven wheels to rotate at different speeds while setting transferable torque and drive-induced yaw behaviour. Open, limited-slip and active torque-vectoring solutions trade traction, rotation, energy, heat, mass and rules complexity and must be coordinated with tyre loads and driver torque request.'),
    subcomponents: [l('主减速齿轮', 'Final-drive gears'), l('差速齿轮组', 'Differential gears'), l('限滑摩擦片/斜坡', 'LSD plates and ramps'), l('输出法兰', 'Output flanges'), l('轴承与壳体', 'Bearings and housing'), l('润滑与温度监测', 'Lubrication and temperature sensing')],
    concepts: [l('开放式差速器两侧扭矩近似相等，因此低附着内轮会限制整轴可用驱动力。', 'An open differential gives nearly equal side torque, so a low-grip inside wheel limits axle drive force.'), l('锁止提高低载轮扭矩利用，却在转弯时抵抗轮速差并改变车辆入弯、过弯和出弯平衡。', 'Locking improves low-load-wheel torque use but resists wheel-speed difference and changes entry, mid-corner and exit balance.'), l('扭矩矢量通过左右轮力差直接产生偏航力矩，但必须受总功率、轮胎摩擦圆和稳定性监控限制。', 'Torque vectoring creates yaw moment through left/right force difference, bounded by total power, tyre friction ellipses and stability supervision.')],
    formulas: [f('差速运动学', 'Differential kinematics', 'ωcarrier = (ωL + ωR) / 2', '适用于对称锥齿轮差速器的基本关系', 'Basic relation for a symmetric bevel-gear differential', '转弯时内外轮速度不同，而壳体速度是平均值。', 'Inside and outside speeds differ in a corner while carrier speed is their average.'), f('扭矩偏置比', 'Torque-bias ratio', 'TBR = Thigh / Tlow', 'Thigh、Tlow 为高低扭矩侧输出', 'Thigh and Tlow are high- and low-torque outputs', 'TBR 描述能力上限，不代表所有工况都恒定达到该比值。', 'TBR is a capability limit, not a constant achieved in every condition.'), f('差动偏航力矩', 'Differential yaw moment', 'Mz ≈ (Fx,R − Fx,L) · t / 2', 't 为驱动轮距；Fx 为左右纵向力', 't driven track; Fx left/right longitudinal force', '该力矩与轮胎侧向力共同作用，过快变化会让车辆难以预测。', 'This acts with lateral tyre forces; rapid changes can make the car unpredictable.')],
    experiments: [e('锁止比例扫描', 'Locking sweep', '更多锁止怎样改变出弯？', 'How does more locking change corner exit?', [['设定内外轮载荷和摩擦系数。', 'Set inside/outside load and friction.'], ['逐步增加预载或扭矩偏置。', 'Increase preload or torque bias.'], ['观察轮速差、总驱动力和偏航力矩。', 'Observe speed difference, total traction and yaw moment.']], '适量锁止利用外轮余量，过多会拖拽轮胎、增加推头或诱发突然过度转向。', 'Moderate locking uses outside-wheel margin; too much scrubs tyres, adds understeer or provokes abrupt oversteer.'), e('抬轮工况', 'Inside-wheel unload', '内轮接近离地时开放差速器为何失去驱动？', 'Why does an open differential lose drive as the inside wheel unloads?', [['逐步降低内轮法向载荷。', 'Reduce inside-wheel normal load.'], ['比较开放式与限滑输出。', 'Compare open and limited-slip outputs.'], ['检查两轮摩擦圆余量。', 'Inspect both tyre friction margins.']], '开放式受低附着侧扭矩限制；限滑能转移更多扭矩，但不能创造轮胎法向载荷。', 'The open unit is torque-limited by the low-grip side; LSD transfers more torque but cannot create tyre normal load.')],
    decisions: [l('根据赛道低速弯、内轮卸载、轮胎和后悬架特性选择差速方案。', 'Choose the differential from low-speed corners, inside-wheel unload, tyres and rear suspension.'), l('把加速锁止、减速锁止、预载和控制斜率分开标定。', 'Calibrate power locking, coast locking, preload and control rate separately.'), l('齿轮、摩擦片、轴承与润滑要按耐久任务循环和冲击扭矩设计。', 'Size gears, plates, bearings and lubrication for endurance duty and torque shock.')],
    validation: [l('差速台架测量转速差、输入扭矩、左右输出、效率、温度和滞回。', 'Differential rig testing should measure speed difference, input torque, side outputs, efficiency, temperature and hysteresis.'), l('赛道同步轮速、驱动扭矩、方向盘、偏航率和油温，按弯道阶段分析。', 'Synchronise wheel speed, drive torque, steering, yaw rate and oil temperature on track by corner phase.')],
    diagnostics: [d('出弯内轮空转', 'Inside wheel spins on exit', '油门增加后内轮轮速跃升，但车辆纵向加速度没有同步增加。', 'Inside-wheel speed jumps with pedal while vehicle acceleration does not.', [['核对内轮载荷和轮胎状态。', 'Check inside-wheel load and tyre state.'], ['测量差速预载/锁止与油温。', 'Measure differential preload/locking and oil temperature.'], ['检查扭矩请求斜率。', 'Inspect torque-request ramp.']], '同时处理轮端载荷、差速锁止和扭矩斜率；单纯增加锁止可能损害过弯平衡。', 'Coordinate wheel load, differential locking and torque ramp; simply adding lock may hurt corner balance.'), d('热态锁止特性漂移', 'Locking changes when hot', '冷车平顺，耐久后转弯拖拽或单轮打滑明显变化。', 'Cold behaviour is smooth, but corner drag or wheelspin changes after endurance running.', [['记录差速油温与轮速差。', 'Log oil temperature and speed difference.'], ['检查摩擦片磨耗和预载。', 'Inspect plate wear and preload.'], ['验证润滑油黏度与污染。', 'Verify lubricant viscosity and contamination.']], '用温度相关台架曲线校正设定，并修复磨耗或润滑根因。', 'Correct settings with temperature-dependent rig curves and fix wear or lubrication root causes.')],
    references: [RCVD, BOSCH],
  },
  cooling: {
    labKind: 'cooling',
    overview: l('热管理系统把电池、逆变器和电机产生的损耗传到冷却液，再通过换热器排向环境。它决定连续功率而非只决定是否过热；工程师需要同时管理热源、流量分配、压降、泵功、散热器风量、气泡排除和传感器位置。', 'Thermal management moves battery, inverter and motor losses into coolant and rejects them to ambient through heat exchangers. It sets continuous power, not merely overheat prevention; engineers manage heat sources, flow split, pressure drop, pump power, radiator airflow, deaeration and sensor location together.'),
    subcomponents: [l('冷却板与水套', 'Cold plates and jackets'), l('电动水泵', 'Electric pump'), l('散热器', 'Radiator'), l('膨胀/除气罐', 'Expansion and deaeration tank'), l('管路与节流', 'Hoses and restrictions'), l('温压流量传感器', 'Temperature, pressure and flow sensors')],
    concepts: [l('温度由热源功率和总热阻共同决定；提高流量只降低其中对流部分，不能修复接触界面或散热器风量不足。', 'Temperature is set by heat rate and total thermal resistance; more flow only reduces convection and cannot fix interface or radiator-airflow limits.'), l('并联支路会按各自压降分配流量，阻力很小的支路可能抢走需要冷却部件的流量。', 'Parallel branches split flow by pressure drop; a low-resistance branch can steal flow from the component that needs it.'), l('泵和散热器应在整车真实风量与管路曲线上匹配工作点，而不是只比较额定最大流量。', 'Pump and radiator must be matched at the real vehicle airflow and system-curve operating point, not by maximum rated flow.')],
    formulas: [f('冷却液稳态带热', 'Steady coolant heat transport', 'Q̇ = ṁ · cp · ΔT', 'ṁ 为质量流量；cp 为测试温区内比热；ΔT 为同一支路同步测得的温差', 'ṁ mass flow; cp specific heat over the test range; ΔT synchronized temperature difference on the same branch', '这是稳态焓差；瞬态时还需计入冷却液、管路和部件储热，过小温差也可能意味着热没有进入冷却液。', 'This is a steady enthalpy difference; transients include stored energy in coolant, plumbing and components, and a small rise may mean heat is not entering the coolant.'), f('节点间等效热阻', 'Node-to-node thermal resistance', 'Rth = ΔT / Q̇', 'ΔT 必须对应明确且相同的温度节点，例如结温到冷却液参考温度；Q̇ 为穿过该路径的稳态热流', 'ΔT must use explicit matching nodes, such as junction to coolant reference; Q̇ is steady heat flow through that path', '跨不同参考节点或不同流量条件的热阻不能直接比较；分段热阻用于定位界面、冷板和空气侧瓶颈。', 'Thermal resistance across different reference nodes or flow conditions cannot be compared directly; segmented values localize interface, cold-plate and air-side bottlenecks.'), f('泵轴输入功率', 'Pump-shaft input power', 'Ppump = Δp · qv / ηpump', 'Δp 为泵工作点压升；qv 为同一工作点体积流量；ηpump 为泵液压效率', 'Δp pump pressure rise; qv volumetric flow at the same operating point; ηpump pump hydraulic efficiency', '该式得到泵轴输入而非电池侧功率；后者还需计入电机和驱动器效率，并用泵曲线与系统曲线确定工作点。', 'This gives pump-shaft input, not battery-side power; the latter includes motor and drive efficiency, and the operating point comes from pump and system curves.')],
    experiments: [e('流量扫描', 'Flow sweep', '加大泵速何时不再有效？', 'When does more pump speed stop helping?', [['固定热源与环境风量。', 'Hold heat load and ambient airflow.'], ['逐步提高泵速。', 'Increase pump speed.'], ['比较部件温度、压降与泵功。', 'Compare component temperature, pressure drop and pump power.']], '开始时对流热阻下降明显，随后界面或空气侧成为瓶颈，继续加泵收益很小。', 'Initially convective resistance falls; later interface or air side dominates and added pumping gives little benefit.'), e('散热器风量', 'Radiator airflow', '低速和高速为何有不同热平衡？', 'Why do low and high vehicle speeds have different thermal balance?', [['保持电驱损耗相同。', 'Hold powertrain loss constant.'], ['改变车速、风扇与风道泄漏。', 'Change speed, fan and duct leakage.'], ['观察冷却液稳态温度。', 'Observe steady coolant temperature.']], '散热器有效风量和进气温度决定空气侧能力；密封风道常比增大散热器面积更有效。', 'Effective radiator airflow and inlet temperature set air-side capability; sealing ducts can outperform added core area.')],
    decisions: [l('从完整任务循环的各部件损耗建立热预算和最高环境温度边界。', 'Build a heat budget from component losses over the full duty cycle and maximum ambient.'), l('用系统压降曲线与泵曲线求工作点，并对并联支路做流量平衡。', 'Find operating point from system and pump curves and balance parallel branches.'), l('布置高点除气、维护排液、泄漏隔离与不被热浸泡误导的传感器。', 'Provide high-point deaeration, service draining, leak isolation and sensors resistant to heat-soak bias.')],
    validation: [l('台架逐级测量热源功率、壁温、进出口温度、流量、压降与环境风量。', 'Measure heat rate, wall temperature, inlet/outlet temperatures, flow, pressure drop and ambient airflow by stage on a rig.'), l('进行低速高负荷、停驶热浸泡、高温环境、部分堵塞和泵失效降额测试。', 'Test low-speed high-load, hot soak, hot ambient, partial blockage and pump-failure derating.')],
    diagnostics: [d('泵速高但流量低', 'High pump speed, low flow', '泵指令和电流上升，流量却低于历史值且温度增高。', 'Pump command and current rise, but flow is below history and temperature increases.', [['检查气锁、液位和泵入口。', 'Check air lock, level and pump inlet.'], ['比较支路压差和阀/节流。', 'Compare branch pressure and restrictions.'], ['检查过滤器、软管塌陷与转向。', 'Inspect filter, hose collapse and pump direction.']], '先恢复灌注与排气，再定位堵塞或泵损伤；不要用更高转速长期气蚀。', 'Restore fill and deaeration before finding blockage or pump damage; do not sustain cavitation with more speed.'), d('一个部件热、回水不热', 'Hot component, cool return', '逆变器或电机温度快速升高，但该支路冷却液温升很小。', 'Inverter or motor temperature rises rapidly while branch coolant rise stays small.', [['核对温度与流量传感器。', 'Verify temperature and flow sensors.'], ['检查界面材料和冷板接触。', 'Inspect interface material and cold-plate contact.'], ['排查支路旁通或局部气泡。', 'Check bypass and trapped air.']], '这通常指向热未进入冷却液或支路无真实流量，而不是散热器总能力不足。', 'This often means heat is not entering coolant or the branch lacks real flow, not insufficient total radiator capacity.')],
    references: [BOSCH, NREL, { title: 'NASA — Thermal Control Handbook', url: 'https://ntrs.nasa.gov/' }],
  },
  ecu: {
    labKind: 'control',
    overview: l('车辆控制器把驾驶员输入、传感器状态和各子系统能力组合成安全的扭矩、制动与冷却指令。它的核心不是某一个算法，而是确定性的状态机、信号合理性、限值仲裁、实时通信、故障降级和可追溯标定，使车辆在正常与故障条件下都可预测。', 'The vehicle controller combines driver input, sensor state and subsystem capability into safe torque, braking and cooling commands. Its core is not one algorithm but deterministic state machines, plausibility, limit arbitration, real-time communication, fault degradation and traceable calibration.'),
    subcomponents: [l('实时处理器', 'Real-time processor'), l('模拟/数字输入', 'Analogue and digital inputs'), l('CAN 网络', 'CAN network'), l('扭矩仲裁', 'Torque arbitration'), l('安全状态机', 'Safety state machine'), l('标定与日志', 'Calibration and logging')],
    concepts: [l('扭矩指令通常是驾驶员请求与电池、逆变器、电机、轮胎和安全限值中的最小允许值。', 'Torque command is commonly the minimum permitted by driver request and battery, inverter, motor, tyre and safety limits.'), l('双通道踏板、制动与油门同时动作等合理性检查要在规定时间内触发独立、确定的安全响应。', 'Plausibility checks for dual pedal channels and simultaneous brake/throttle must trigger independent deterministic safety responses within defined time.'), l('状态机明确关机、预充、待命、可行驶、降额和故障锁存之间的唯一合法转换，避免隐含状态。', 'A state machine defines the only legal transitions among off, precharge, standby, drive, derate and latched fault, avoiding hidden states.')],
    formulas: [f('一阶离散低通', 'First-order discrete low-pass', 'y[k] = y[k−1] + α(x[k] − y[k−1])', '0<α≤1，且 α 必须由采样周期与目标连续时间常数/截止频率一致地离散化', '0<α≤1 and α must be discretized consistently from sample period and target continuous time constant/cutoff', '滤波降低噪声也增加相位延迟；采样周期改变时不能沿用同一 α，安全阈值也必须考虑延迟。', 'Filtering reduces noise but adds phase delay; the same α cannot be reused after sample-period changes, and safety thresholds must account for delay.'), f('扭矩斜率限制', 'Torque slew limit', '|Tcmd[k] − Tcmd[k−1]| ≤ Ṫmax · Δt', 'Ṫmax 为正常增扭或减扭速率限制；Δt 为实际执行间隔，正负方向可设置不同限值', 'Ṫmax is normal positive or negative torque-rate limit; Δt is actual execution interval and directions may use different limits', '斜率限制改善抓地与可预测性，但安全切断必须走不受正常缓降约束的高优先级路径。', 'Slew limiting improves grip and predictability, but safety shutdown requires a higher-priority path not delayed by the normal ramp.'), f('周期任务需求利用率', 'Periodic-task demand utilisation', 'U = Σ(Ci / Ti)', 'Ci 为已覆盖最坏路径的执行时间上界；Ti 为任务周期；各项必须在同一处理器资源上', 'Ci is an execution-time upper bound covering worst paths; Ti task period; all terms must share the same processor resource', 'U<1 只是必要的容量检查，不是可调度性证明；还需结合调度算法检查截止期、阻塞、中断、抖动和共享资源。', 'U<1 is only a necessary capacity check, not schedulability proof; deadlines, blocking, interrupts, jitter and shared resources must be checked for the scheduler.')],
    experiments: [e('限值仲裁', 'Limit arbitration', '多个系统同时降额时最终扭矩怎样决定？', 'How is final torque set when several systems derate?', [['设定驾驶员请求。', 'Set driver request.'], ['分别降低电池、电机和轮胎限值。', 'Reduce battery, motor and tyre limits.'], ['观察最终限值、来源与恢复斜率。', 'Observe final limit, source and recovery ramp.']], '最严格限值获胜，并应记录来源；恢复通常要有滞回和斜率，避免边界抖动。', 'The tightest limit wins and its source is logged; recovery needs hysteresis and ramping to avoid chatter.'), e('传感器故障注入', 'Sensor fault injection', '一个信号卡死时系统应该继续还是停机？', 'Should the system continue or stop when a signal freezes?', [['选择踏板、温度或轮速信号。', 'Choose pedal, temperature or wheel-speed signal.'], ['注入越界、卡死或漂移。', 'Inject out-of-range, stuck or drifting behaviour.'], ['检查检测时间、替代值和驾驶状态。', 'Check detection time, substitute value and drive state.']], '响应取决于危害：扭矩相关踏板故障需快速安全切断，冗余温度故障可在保守降额下返场。', 'Response follows hazard: torque-pedal faults need rapid safe shutdown; a redundant temperature fault may allow conservative limp-home.')],
    decisions: [l('先做危害分析和状态/接口定义，再写控制代码与标定。', 'Perform hazard analysis and state/interface definition before control code and calibration.'), l('每个限值必须有物理来源、单位、更新周期、优先级、滞回和日志标识。', 'Every limit needs a physical source, unit, update rate, priority, hysteresis and log identifier.'), l('把软件版本、参数集、车辆配置与测试结果绑定，保证可复现。', 'Bind software version, parameter set, vehicle configuration and test result for reproducibility.')],
    validation: [l('模型在环、软件在环、硬件在环后再进入低压、悬空轮、低速与赛道分阶段测试。', 'Progress from model-, software- and hardware-in-loop to low-voltage, wheels-up, low-speed and track tests.'), l('覆盖边界值、通信丢包、任务超时、复位、传感器组合故障和断电恢复。', 'Cover boundaries, dropped messages, task overruns, resets, combined sensor faults and power-cycle recovery.')],
    diagnostics: [d('扭矩偶发瞬断', 'Intermittent torque cut', '没有持续故障灯，但加速中扭矩短暂归零后恢复。', 'Torque briefly falls to zero during acceleration and recovers without a persistent lamp.', [['查看限值来源与状态机事件日志。', 'Inspect limit-source and state-machine event logs.'], ['检查 CAN 超时和传感器合理性计数。', 'Check CAN timeouts and plausibility counters.'], ['关联供电电压与任务执行时间。', 'Correlate supply voltage and task execution time.']], '用首次触发事件而非最终连锁报警找根因，修复通信、供电或阈值后重放验证。', 'Use the first triggering event rather than cascading alarms to find root cause, then replay after fixing communications, supply or thresholds.'), d('降额边界来回跳变', 'Derate boundary chatters', '温度接近阈值时可用功率每秒上下变化，车辆顿挫。', 'Available power oscillates each second as temperature approaches a threshold.', [['检查测量噪声与滤波延迟。', 'Inspect noise and filter delay.'], ['检查限值曲线连续性、滞回和恢复斜率。', 'Check continuity, hysteresis and recovery ramp.'], ['验证多限值切换逻辑。', 'Validate switching among multiple limits.']], '使用连续限值、合适滞回和受控恢复，同时保留快速越界保护。', 'Use continuous limits, suitable hysteresis and controlled recovery while retaining fast out-of-bounds protection.')],
    references: [FSG, BOSCH, { title: 'MISRA — Automotive Software Guidelines', url: 'https://misra.org.uk/' }],
  },
  sensors: {
    labKind: 'telemetry',
    overview: l('传感器与遥测把赛车行为变成可验证的工程证据。完整测量链包括物理量、传感器、安装、供电、调理、采样、时间同步、标定、单位、传输、存储和分析；如果任何一环不可信，漂亮的曲线也可能得出错误结论。', 'Sensors and telemetry turn vehicle behaviour into verifiable engineering evidence. The chain spans measurand, sensor, mounting, power, conditioning, sampling, synchronisation, calibration, units, transport, storage and analysis; a beautiful plot can still mislead if any link is untrusted.'),
    subcomponents: [l('轮速与位置传感', 'Speed and position sensing'), l('压力与温度传感', 'Pressure and temperature sensing'), l('IMU 与 GPS', 'IMU and GPS'), l('应变与载荷测量', 'Strain and load measurement'), l('数据记录器/CAN', 'Logger and CAN'), l('遥测链路与分析软件', 'Telemetry link and analysis software')],
    concepts: [l('精度、分辨率、重复性、带宽和延迟描述不同性质；高分辨率并不等于高准确度。', 'Accuracy, resolution, repeatability, bandwidth and latency are different; high resolution is not high accuracy.'), l('不同采样率的信号必须共享可信时间基准；几毫秒错位就可能颠倒制动压力与减速度的因果判断。', 'Signals at different rates need a trusted time base; milliseconds of offset can reverse causal interpretation of brake pressure and deceleration.'), l('反混叠滤波必须发生在降采样之前，否则高频能量会伪装成低频现象，事后数字滤波无法恢复。', 'Anti-alias filtering must precede downsampling; otherwise high-frequency energy masquerades as low-frequency behaviour and cannot be repaired later.')],
    formulas: [f('线性标定', 'Linear calibration', 'y = a·x + b', 'x 为被测物理量、y 为传感器输出；a 为灵敏度、b 为零点；方向必须与标定数据定义一致', 'x is measurand and y sensor output; a is sensitivity and b offset; direction must match the calibration-data definition', '两点可求增益和零点，但至少需要多点升降程检查线性、迟滞、重复性、温漂和有效量程。', 'Two points determine gain and offset, but multipoint up/down sweeps are needed for linearity, hysteresis, repeatability, thermal drift and valid range.'), f('奈奎斯特必要条件', 'Nyquist necessary condition', 'fs > 2·fmax', 'fs 为采样率；fmax 为需要无混叠保留的最高有效频率；信号必须在采样前带限', 'fs sample rate; fmax highest relevant frequency to preserve without aliasing; the signal must be band-limited before sampling', '大于两倍只是理想必要条件，不是完整设计；模拟抗混叠滤波器需要过渡带，采样率通常要明显更高。', 'Above twice is only an ideal necessary condition, not a complete design; an analog anti-alias filter needs transition band, so sampling is usually substantially faster.'), f('独立标准不确定度合成', 'Independent standard-uncertainty combination', 'uc = √(u1² + u2² + …)', 'ui 必须是以同一单位表示且独立或已去相关的标准不确定度分量', 'ui must be standard-uncertainty components in common units that are independent or decorrelated', '相关来源必须加入协方差项；扩展不确定度还需选择覆盖因子，不能把所有误差上限直接平方和。', 'Correlated sources require covariance terms; expanded uncertainty also needs a coverage factor, and arbitrary error limits cannot simply be root-sum-squared.')],
    experiments: [e('采样与混叠', 'Sampling and aliasing', '高速振动为什么会显示成慢波？', 'Why can fast vibration appear as a slow wave?', [['生成频率逐步升高的真实信号。', 'Generate a rising-frequency true signal.'], ['改变采样率与模拟低通。', 'Change sample rate and analogue low-pass filter.'], ['比较时域与频谱。', 'Compare time trace and spectrum.']], '超过奈奎斯特的能量折叠到低频；提高采样或先做模拟滤波才能避免。', 'Energy above Nyquist folds into low frequencies; avoid it by raising sampling or analogue filtering first.'), e('通道时间对齐', 'Channel synchronisation', '10 ms 偏移会怎样改变制动分析？', 'How does a 10 ms offset change brake analysis?', [['使用同一制动事件的压力和减速度。', 'Use pressure and acceleration from one stop.'], ['逐步偏移一个通道。', 'Shift one channel progressively.'], ['计算响应延迟和制动增益。', 'Calculate response delay and brake gain.']], '小偏移会制造虚假的迟滞或预响应，必须用公共时钟、触发或相关事件验证同步。', 'Small offsets create false lag or anticipation; verify synchronisation with a common clock, trigger or correlated event.')],
    decisions: [l('每个通道建立量程、带宽、采样率、单位、标定、允许误差和用途表。', 'Create a channel table with range, bandwidth, sample rate, unit, calibration, tolerance and purpose.'), l('传感器安装要控制结构共振、热传导、接地回路、屏蔽和线束应变。', 'Sensor installation must control structural resonance, thermal conduction, ground loops, shielding and harness strain.'), l('在数据文件中保存软件版本、车辆配置、通道字典、时间源和标定版本。', 'Store software version, vehicle configuration, channel dictionary, time source and calibration version with data.')],
    validation: [l('进行零点、已知载荷、多点标定、端到端注入和跨设备时间同步测试。', 'Perform zero, known-load, multipoint calibration, end-to-end injection and cross-device synchronisation tests.'), l('每次赛前自动检查合理范围、卡死、噪声、丢包、单位和采样频率。', 'Automatically check range, stuck values, noise, packet loss, units and sample rate before every run.')],
    diagnostics: [d('曲线平滑但物理上不可能', 'Smooth but impossible trace', '载荷信号无噪声，却在车辆静止时随转向同步变化。', 'A load signal is noise-free but changes with steering while the car is stationary.', [['检查通道映射、单位和 CAN 字节序。', 'Check channel mapping, units and CAN endianness.'], ['检查共地、串扰和供电。', 'Inspect grounding, crosstalk and supply.'], ['施加独立已知输入。', 'Apply an independent known input.']], '平滑不代表正确；用端到端注入确认通道身份并修复电气耦合或解码。', 'Smooth does not mean correct; confirm channel identity end-to-end and fix coupling or decoding.'), d('两个系统事件无法对齐', 'Events do not align across loggers', 'ECU 的扭矩切断比独立记录器的故障信号早或晚几十毫秒。', 'ECU torque cut leads or lags the independent logger fault by tens of milliseconds.', [['比较时钟源、漂移和启动偏移。', 'Compare clock sources, drift and start offsets.'], ['寻找共同的硬件边沿事件。', 'Find a shared hardware-edge event.'], ['检查 CAN 网关缓存和重采样。', 'Inspect gateway buffering and resampling.']], '建立统一时间基准或记录同步脉冲，并在分析中应用可追溯的时间校正。', 'Establish a common time base or log sync pulses and apply traceable time correction in analysis.')],
    references: [BOSCH, { title: 'NI — Data Acquisition Fundamentals', url: 'https://www.ni.com/docs/en-US/bundle/ni-daqmx/page/data-acquisition-fundamentals.html' }, { title: 'NIST — Measurement Uncertainty', url: 'https://www.nist.gov/pml/nist-technical-note-1297' }],
  },
}
