import type { Course, CourseId } from './data'
import type { Locale } from './i18n'

type CourseText = Pick<Course, 'title' | 'subtitle' | 'description' | 'parts' | 'task' | 'question' | 'options' | 'answer'>
type LocalCourse = Record<Locale, CourseText>
const c = (zh: CourseText, en: CourseText): LocalCourse => ({ zh, en })

const COURSES: Record<CourseId, LocalCourse> = {
  orientation: c(
    { title:'进入顶级单座赛车', subtitle:'从驾驶员生存空间建立整车地图', description:'先确认这是一辆由驾驶员坐在生存舱内操纵的全尺寸单座赛车，再建立安全、控制、气动、底盘、混动与数据系统的层级。', parts:['monocoque','halo','steering'], task:'依次隔离生存舱、头部保护环与驾驶控制，找到座椅、安全带、头盔、方向盘和踏板。', question:'驾驶员在赛车中的受保护空间主要由哪组系统共同建立？', options:['涂装与轮辋','生存舱、约束系统、头部保护环与防滚结构','只有尾翼','只有电池壳体'], answer:1 },
    { title:'Enter the grand prix single-seater', subtitle:'Build the car map from the driver survival volume', description:'First confirm this is a full-scale driver-operated single-seater, then map safety, controls, aero, chassis, hybrid and data systems.', parts:['monocoque','halo','steering'], task:'Isolate survival cell, Halo and driver controls; find seat, harness, helmet, wheel and pedals.', question:'Which set primarily creates the protected driver volume?', options:['Livery and rims','Survival cell, restraints, Halo and roll structures','Rear wing only','Battery enclosure only'], answer:1 }),
  forces: c(
    { title:'载荷路径与动态平台', subtitle:'让每一股力都有来路和去向', description:'把轮胎、悬架、单体壳和地面效应载荷放在同一受力图中，理解高速载荷如何改变机械与气动平台。', parts:['tires','front-suspension','floor'], task:'切换制动与转弯场景，追踪轮胎力经悬架进入单体壳，并观察底板离地高度。', question:'高速时气动下压力增加后，哪一项最需要同步检查？', options:['网页标题','轮胎载荷与车身姿态是否仍在工作窗口','驾驶员姓名颜色','设置弹窗宽度'], answer:1 },
    { title:'Load paths and dynamic platform', subtitle:'Give every force an origin and destination', description:'Place tire, suspension, chassis and ground-effect loads in one free-body model and see how speed changes mechanical and aero platforms.', parts:['tires','front-suspension','floor'], task:'Use braking and cornering modes; trace tire loads into the cell and inspect floor clearance.', question:'As aero load rises with speed, what must be checked with it?', options:['Page title','Tire load and vehicle attitude remain inside the operating window','Driver-name colour','Settings width'], answer:1 }),
  tires: c(
    { title:'18英寸轮胎与抓地预算', subtitle:'把载荷、滑移和热状态连起来', description:'用载荷敏感性、纵向滑移、侧偏角、胎压和多层温度理解一圈中的抓地能力。', parts:['tires','front-suspension','rear-suspension'], task:'在高速转弯中比较内外轮载荷、外倾和轮胎温度，再切换制动观察组合滑移。', question:'为什么横向载荷转移通常降低一根车轴的总抓地？', options:['因为轮胎具有载荷敏感性','因为轮辋变成方形','因为空气密度归零','因为方向盘停止记录'], answer:0 },
    { title:'18-inch tires and grip budget', subtitle:'Connect load, slip and thermal state', description:'Use load sensitivity, slip ratio, slip angle, pressure and layered temperature to understand grip through a lap.', parts:['tires','front-suspension','rear-suspension'], task:'Compare inside/outside load, camber and temperature in a fast corner, then inspect combined slip under braking.', question:'Why does lateral load transfer normally reduce combined axle grip?', options:['Because tires are load-sensitive','Because rims become square','Because air density becomes zero','Because the steering wheel stops logging'], answer:0 }),
  braking: c(
    { title:'碳碳制动与能量回收', subtitle:'把热制动和电回收混成一个踏板响应', description:'理解碳碳材料温度窗口、动态制动平衡、后轴线控制动和 MGU-K 回收如何共同形成稳定减速度。', parts:['brakes','motor','battery'], task:'进入重制动场景，先看制动盘温度，再追踪后轴回收能量进入高压电池。', question:'当 MGU-K 回收扭矩突然降低时，线控制动应该怎样响应？', options:['保持摩擦扭矩不变造成总扭矩下降','连续增加后轴摩擦制动以填补缺口','打开主动尾翼作为唯一制动','切断前轮'], answer:1 },
    { title:'Carbon braking and regeneration', subtitle:'Blend heat braking and electrical recovery into one pedal response', description:'Connect carbon temperature window, dynamic balance, rear brake-by-wire and MGU-K regeneration into stable deceleration.', parts:['brakes','motor','battery'], task:'Use braking mode; inspect disc temperature, then trace rear-axle recovered energy into the HV battery.', question:'If MGU-K regenerative torque suddenly falls, how should brake-by-wire respond?', options:['Hold friction torque and accept a total-torque drop','Increase rear friction torque continuously to fill the gap','Use the active wing as the only brake','Disconnect the front wheels'], answer:1 }),
  suspension: c(
    { title:'悬架、转向与气动平台', subtitle:'同时服务轮胎和底板', description:'从硬点、摇臂、第三弹性元件和后束角顺从理解轮心路径、驾驶反馈与底板姿态。', parts:['front-suspension','rear-suspension','steering'], task:'分层拆开前后悬架，分别找出控制臂、推/拉杆、摇臂、阻尼器、齿条和半轴。', question:'为什么不能无限提高悬架刚度来稳定底板？', options:['过高刚度会增加轮胎载荷波动并降低路面跟随','因为刚度只影响涂装','因为阻尼器没有速度','因为车手不使用方向盘'], answer:0 },
    { title:'Suspension, steering and aero platform', subtitle:'Serve tire and floor together', description:'Use hardpoints, rockers, heave elements and rear-toe compliance to connect wheel path, driver feedback and underfloor attitude.', parts:['front-suspension','rear-suspension','steering'], task:'Explode both suspensions and identify arms, push/pull rods, rockers, dampers, rack and halfshafts.', question:'Why not increase suspension stiffness without limit to stabilize the floor?', options:['Excess stiffness increases tire-load variation and hurts road following','Stiffness changes livery only','Dampers have no velocity','The driver does not use steering'], answer:0 }),
  aero: c(
    { title:'主动空气动力学与地面效应', subtitle:'管理高载、低阻与转换过程', description:'沿主动前翼、文丘里底板和主动尾翼建立气动链，重点分析平衡随速度、姿态和翼面状态的变化。', parts:['front-wing','floor','rear-wing'], task:'进入气流场景并切换加速状态，观察前后活动翼角度与底板流道，再用分层拆解检查耦合。', question:'主动前后翼为什么必须协调转换？', options:['为了保持转换期间气动平衡可控','只是为了灯光同步','因为底板没有气流','为了改变燃料化学成分'], answer:0 },
    { title:'Active aerodynamics and ground effect', subtitle:'Manage high load, low drag and transition', description:'Build the aero chain from active front wing through Venturi floor to active rear wing, focusing on balance across speed, attitude and device state.', parts:['front-wing','floor','rear-wing'], task:'Use airflow and acceleration states, inspect flap angle and floor tunnels, then explode the coupled devices.', question:'Why must front and rear active wings transition coherently?', options:['To keep aerodynamic balance controlled during transition','Only to synchronize lights','Because the floor has no flow','To change fuel chemistry'], answer:0 }),
  powertrain: c(
    { title:'V6涡轮混动与热管理', subtitle:'把燃料、电能和热约束转化为整圈性能', description:'沿燃料到 V6 曲轴、MGU-K、电池、逆变器、变速箱与多回路冷却追踪功率，并建立 SOC 与温度的整圈记忆。', parts:['motor','inverter','battery','differential','cooling'], task:'进入全力加速，依次点击动力单元、功率电子、能量存储、变速箱和冷却系统，并说明每次能量形式变化。', question:'2026 概念动力单元的正确组成是什么？', options:['纯电机且没有驾驶员','1.6 L 涡轮 V6 与高功率 MGU-K，且不再使用 MGU-H','蒸汽机和皮带','只有普通公路车电池'], answer:1 },
    { title:'V6 turbo hybrid and thermal management', subtitle:'Turn fuel, electricity and thermal limits into lap performance', description:'Trace power through V6 crank, MGU-K, battery, inverter, gearbox and multiple cooling loops, building a lap-scale view of SOC and temperature.', parts:['motor','inverter','battery','differential','cooling'], task:'Use acceleration mode and click power unit, electronics, store, transmission and cooling in energy-flow order.', question:'What correctly describes the 2026 concept power unit?', options:['A driverless pure electric motor','A 1.6 L turbo V6 plus high-power MGU-K, without MGU-H','A steam engine and belt','Only a road-car battery'], answer:1 }),
  integration: c(
    { title:'整车控制、数据与比赛工程', subtitle:'从传感证据到单圈决策', description:'用标准控制单元、遥测、驾驶输入和整车模型连接气动、轮胎、制动、混动与可靠性，形成可复现的工程决策。', parts:['ecu','sensors','front-wing','brakes','motor'], task:'运行加速、制动、转弯和气流场景，选择一个工程问题并列出输入信号、计算模型、验证证据和安全边界。', question:'顶级赛车整车调校的核心方法是什么？', options:['让每个峰值数字都最大','用同步数据和模型管理系统取舍，并通过试验验证','只相信一圈主观感受','复制另一支车队无法获得的标定'], answer:1 },
    { title:'Vehicle control, data and race engineering', subtitle:'From sensor evidence to lap decisions', description:'Use standard control, telemetry, driver input and whole-car models to connect aero, tires, brakes, hybrid power and reliability into reproducible decisions.', parts:['ecu','sensors','front-wing','brakes','motor'], task:'Run acceleration, braking, cornering and airflow; choose one question and state signals, model, evidence and safety limits.', question:'What is the core method of top-level race-car setup?', options:['Maximize every peak number','Manage system trade-offs with synchronized data and models, then validate by test','Trust one subjective lap only','Copy unavailable calibration from another team'], answer:1 }),
}

export const getGrandPrixCourse = (base: Course, locale: Locale): Course => ({ ...base, ...COURSES[base.id][locale] })
