import type { PartId } from './data'
import type { EngineeringLesson, LocalText } from './engineeringData'
import type { SubassemblyFact } from './componentWorkshopData'

const l = (zh: string, en: string): LocalText => ({ zh, en })
type Detail = { position: LocalText; role: LocalText; principle: LocalText; plain: LocalText }
const d = (pz: string, pe: string, rz: string, re: string, iz: string, ie: string, az: string, ae: string): Detail => ({
  position: l(pz, pe), role: l(rz, re), principle: l(iz, ie), plain: l(az, ae),
})

/**
 * Hand-authored explanations for every Grand Prix subassembly. These are kept
 * separate from the student-car facts because the architecture, operating
 * envelope and regulatory assumptions are different.
 */
const DETAILS: Record<PartId, readonly Detail[]> = {
  'front-wing': [
    d('主翼横跨鼻锥前下方，是前翼最靠近赛道、也是其余翼片的气动基准。','The mainplane spans below the nose and is the wing’s lowest surface and aerodynamic datum.','建立基础前轴下压力并给上游气流定向。','It establishes baseline front-axle load and conditions upstream flow.','压力差产生载荷，前缘半径和离地高度决定附着与失速裕量。','Pressure difference creates load; leading-edge radius and ground clearance set attachment and stall margin.','它像整套前翼的地基，位置一变，后面的翼片都会换一种工作环境。','It is the foundation of the wing; move it and every downstream element sees a different flow.'),
    d('左右活动襟翼位于主翼上方并分置鼻锥两侧，可围绕规定轴线改变姿态。','The left and right active flaps sit above the mainplane on either side of the nose and rotate about defined axes.','在允许状态间改变前轴载荷和阻力，并保持左右同步。','They change front-axle load and drag between permitted states while remaining synchronized.','襟翼角改变环量与压力恢复；间隙和重叠量控制缝翼射流能否维持附着。','Flap angle changes circulation and pressure recovery; gap and overlap govern slot-jet attachment.','它们像飞机襟翼，但调节目标是整车气动平衡，而不是单独追求最大下压力。','They resemble aircraft flaps, but their target is whole-car balance rather than isolated peak load.'),
    d('端板与翼尖位于前翼左右外缘，紧邻前轮前方的强三维流场。','Endplates and tips occupy the outer edges immediately ahead of the front tyres in strongly three-dimensional flow.','约束翼端泄漏、抑制传统外洗，并配合 2026 规定的内洗式前轮尾流控制。','They limit tip leakage, suppress traditional outwash and support the 2026 in-washing front-wheel wake-control concept.','上下表面压差会卷成翼尖涡；曲率、间隙与局部合法性共同决定涡系。','Pressure difference rolls into tip vortices; curvature, gaps and legality determine the vortex system.','它们像河道导流墙，既不能让高低压过早串通，也要把脏空气引到合适方向。','They act like river guide walls, limiting pressure leakage while steering disturbed air.'),
    d('作动器和连杆收纳在鼻锥或翼片附近，通过短载荷路径连接左右活动面。','Actuators and linkages are packaged near the nose or flap with short load paths to both movable surfaces.','把控制命令变成受限角位移，并在故障时进入规定安全状态。','They turn commands into bounded angular motion and enter a defined safe state after faults.','执行器推力经杠杆臂转成铰链力矩；刚度、回差、锁止和失效检测决定动态精度。','Actuator force becomes hinge torque through a lever arm; stiffness, backlash, latching and fault detection set accuracy.','它是前翼的肌肉和关节，既要动得快，也必须卡在正确且可验证的位置。','It is the wing’s muscle and joint: fast movement matters, but verified positioning matters more.'),
    d('鼻锥安装与载荷接头位于前翼中心，将气动和路肩载荷传入鼻锥及前舱壁。','Nose mounts and load joints sit at wing centre and carry aero and kerb loads into the nose and front bulkhead.','定位整套前翼并建立可拆卸而重复的结构基准。','They locate the complete wing and provide a removable, repeatable structural datum.','接头同时承受弯矩、剪力和扭矩；局部层合、紧固预紧与间隙决定疲劳寿命。','The joint carries bending, shear and torsion; laminate, preload and clearance control fatigue life.','它像相机的卡口，拆装要快，但每次装回都必须保持同一位置和刚度。','It is like a camera bayonet: quick to remove, yet repeatable in position and stiffness.'),
    d('位置传感器位于铰链或作动器，压力孔分布在关键翼面并通过细管连接采集单元。','Position sensors sit at hinges or actuators; pressure taps occupy critical surfaces and feed acquisition lines.','确认活动面实际状态，并用压力分布验证模型和失速边界。','They confirm actual flap state and use pressure distribution to validate models and stall boundaries.','冗余位置必须一致；压力测量还需校正管路延迟、温度和参考静压。','Redundant positions must agree; pressure data require correction for tubing lag, temperature and reference static pressure.','它们是前翼的尺子和听诊器：一个量动作，一个判断气流是否健康。','They are the wing’s ruler and stethoscope: one measures motion, the other diagnoses flow.'),
  ],
  'rear-wing': [
    d('主翼横跨赛车尾部并由中央区域支撑，位于扩散器出口上方。','The mainplane spans the car tail above the diffuser exit and is supported near the centre.','建立后轴基础下压力，并为活动上襟翼提供稳定来流和结构基座。','It supplies baseline rear load and a stable aerodynamic and structural base for the active flap.','弯度、迎角和展弦比决定环量；与尾流和扩散器的耦合使单件风洞数据不能代表整车。','Camber, incidence and aspect ratio set circulation; wake and diffuser coupling make isolated data incomplete.','它像后轴上方的固定书脊，活动页可以翻动，但整本书的形状由它奠定。','It is the fixed spine above the rear axle: the moving page depends on it.'),
    d('活动上襟翼位于主翼后上方，通过左右铰链和规定间隙形成第二翼段。','The movable upper flap sits aft and above the mainplane, forming a second element through hinges and a regulated gap.','在弯道状态增加载荷，在直道状态降低阻力并维持可控平衡迁移。','It adds cornering load and reduces straight-line drag while controlling balance migration.','开度同时改变环量、缝隙流和尾流偏转；瞬态不对称会直接形成偏航力矩。','Opening changes circulation, slot flow and wake deflection; transient asymmetry directly creates yaw moment.','它像可开合的百叶窗，左右必须一起动，否则高速时赛车会被推向一侧。','It behaves like a high-load louvre; left-right mismatch can push the car sideways at speed.'),
    d('端板与翼尖包围后翼外缘，处在后轮尾流与自由流交界处。','Endplates and tips bound the rear wing where rear-tyre wake meets the free stream.','限制跨压泄漏、控制翼尖涡，并帮助活动翼在全宽范围内保持可预测。','They limit pressure leakage, control tip vortices and keep active-wing behaviour predictable across the span.','边界层、轮胎尾流与翼尖涡相互作用，局部几何变化可能改变失速从哪里开始。','Boundary layers, tyre wake and tip vortices interact, so local geometry can move stall onset.','它们是后翼两端的围栏，既关住压差，也决定涡从哪里、以多大强度离开。','They are end fences that retain pressure difference and determine where vortices leave.'),
    d('双支柱从变速箱或后部承载结构伸向翼面，避开高敏感气流区并传递全部翼载。','Twin supports rise from the gearbox or rear structure to the wing, carrying load while avoiding sensitive flow.','把下压力、阻力和振动载荷送入后部壳体，同时保持翼面姿态。','They transfer downforce, drag and vibration into the rear casing while holding wing attitude.','支柱需要校核弯扭耦合、模态和接头局部应力；过软会让气动角度随速度漂移。','Supports require bending-torsion, modal and joint-stress checks; excessive flexibility changes incidence with speed.','它们像桥墩，不只是托住重量，还要让整座桥在风里不扭、不抖。','They are bridge piers that must resist twist and vibration, not merely hold weight.'),
    d('作动器、锁止和回位机构安装在翼面中央或支柱内，直接连接活动襟翼。','The actuator, latch and return mechanism are housed centrally or within supports and connect to the movable flap.','按命令切换状态，并在断电、卡滞或位置不一致时限制危险运动。','They switch states on command and bound hazardous motion after power loss, jam or disagreement.','铰链力矩随动压快速增长；机械止挡、锁止能力和故障回位必须覆盖最大载荷。','Hinge torque rises with dynamic pressure; stops, latch capacity and fail-safe return must cover maximum load.','它像高速列车的车门机构，动作只是第一步，锁得住和知道锁住才算完成。','It is like a high-speed train door: motion is only step one; secure and verified locking completes the job.'),
    d('位置、载荷和振动传感器布置在铰链、作动器、支柱根部及翼面局部。','Position, load and vibration sensors are placed at hinges, actuators, support roots and selected wing locations.','监控状态一致性、结构载荷和颤振征兆，为控制与寿命管理提供证据。','They monitor state agreement, structural load and flutter precursors for control and life management.','多源信号要做时间同步与合理性比较；频谱峰值可揭示松动、共振或气动激励。','Sources require time alignment and plausibility checks; spectral peaks expose looseness, resonance or aero forcing.','它们让工程师知道后翼不仅“已经打开”，还知道它是否承受了预期载荷并保持稳定。','They reveal not only that the wing moved, but whether it carried expected load stably.'),
  ],
  floor: [
    d('底板入口位于前轮之后、地板最前端，前缘定义进入车底的质量流与边界层状态。','Floor inlets sit behind the front wheels at the floor leading edge, setting underbody mass flow and boundary-layer state.','把受前翼和前轮影响的气流整形成左右通道可用的入口条件。','They condition front-wing- and tyre-disturbed flow for the left and right tunnels.','入口面积、唇口曲率和偏航共同决定是否分离；局部峰值吸力不等于稳定的总载荷。','Area, lip curvature and yaw set separation; a suction peak does not guarantee stable total load.','它像水泵入口，入口吃不到干净流量，后面的文丘里通道再漂亮也发挥不出来。','It is a pump inlet: poor inflow starves even an excellent downstream tunnel.'),
    d('左右文丘里通道沿单体壳两侧向后延伸，是地效载荷的主要流道。','Twin Venturi tunnels run rearward beside the survival cell and form the primary ground-effect passages.','用收缩与扩张改变速度和静压，在大面积底板上产生向下的净载荷。','They use contraction and expansion to change velocity and static pressure over a large load-producing area.','连续性和能量关系解释趋势，但真实流动还受黏性、三维涡、边界层和轮胎尾流控制。','Continuity and energy relations show trends, while viscosity, 3-D vortices, boundary layers and tyre wake govern reality.','它们像倒置的两条喉管，把车底空气加速，再把低压均匀铺在底板上。','They are twin inverted nozzles that accelerate underfloor air and spread low pressure over the floor.'),
    d('喉部位于通道最窄、最靠近地面的区域，随俯仰和起伏经历最大的间隙变化。','The throats are the narrowest, lowest tunnel regions and see the largest clearance changes with pitch and heave.','形成最高局部速度和最低压力，但必须保留防堵塞、触底和失速的窗口。','They create peak speed and low pressure while retaining margin against choking, contact and stall.','间隙太小会使边界层占比增大、质量流下降甚至分离；载荷因此不会无限随车高降低。','Too little gap thickens relative boundary layers, reduces mass flow and can separate; load does not rise indefinitely.','它像捏紧的软管：适度变窄会加速，捏得过头反而没流量。','It is like pinching a hose: some restriction accelerates flow, too much starves it.'),
    d('边缘涡几何沿底板外缘布置，处在车底低压区与外界高压空气之间。','Edge-vortex geometry runs along the floor perimeter between low-pressure underbody flow and higher-pressure ambient air.','建立空气动力密封，减缓侧向泄漏并提高偏航和车高变化下的稳定性。','It creates aerodynamic sealing, limiting lateral leakage and improving robustness to yaw and ride-height change.','锐边和曲率生成有组织涡结构；涡破裂或轮胎喷流侵入会让底板载荷突然下降。','Edges and curvature generate organized vortices; breakdown or tyre-squirt intrusion can collapse floor load.','它像没有实体门的气流门帘，用旋转的空气把车底低压区围起来。','It is an air curtain with no solid wall, using rotating flow to fence the low-pressure region.'),
    d('扩散器位于后轴前后并向尾部抬升，分流片把宽通道划成受控子流道。','The diffuser rises around and behind the rear axle; strakes divide the broad exit into controlled passages.','逐步减速车底流、恢复静压并把质量流稳定排入尾流。','It decelerates underfloor flow, recovers static pressure and discharges mass flow stably into the wake.','扩张角过大或入口畸变会造成分离；后翼和车尾低压可帮助抽吸，但也形成强耦合。','Excess expansion or distorted inflow separates; rear-wing and base suction can help extraction but create strong coupling.','它像喇叭口，负责把高速气流温和地放大出口，而不是突然把它撞进外界。','It is a diffuser nozzle that expands high-speed flow gently instead of dumping it abruptly.'),
    d('磨损板沿车辆中心线布置，离地传感器和检查点位于规定测量区域。','The plank runs on the car centreline, with ride-height sensing and inspection points at defined locations.','提供合法性与触底证据，并量化底板真实工作高度和动态平台。','It supplies legality and grounding evidence while quantifying actual floor height and platform motion.','磨耗积分了赛道接触历史；激光、位移或压力代理必须与结构挠度和传感器基准区分。','Wear integrates contact history; laser, displacement or pressure proxies must be separated from structural deflection and datum error.','它是底板的黑匣子和磨损尺：赛后表面会记录赛车是否长期跑得过低。','It is the floor’s black box and wear gauge, recording whether the car ran too low.'),
  ],
  nose: [
    d('外部鼻锥位于单体壳最前端并包覆碰撞结构，外表面同时连接前翼来流。','The external nose fairing covers the frontal crash structure and shapes flow toward the front wing.','提供低阻整流、可拆维修外壳和满足几何边界的外形。','It provides low-drag fairing, serviceable skin and a shape within geometric limits.','表面压力和横风决定气动载荷；外壳可很轻，但不能干扰碰撞结构的压溃路径。','Surface pressure and yaw set aero loads; the light fairing must not disrupt the crash structure’s crush path.','它是安全梁外面的空气外套，既要顺滑，也不能妨碍里面按计划吸能。','It is an aerodynamic coat over a safety beam: smooth outside, unobstructive during crush.'),
    d('前部碰撞结构沿车辆中心线从前舱壁向前伸出，位于鼻锥内部。','The frontal impact structure projects forward from the front bulkhead along the centreline inside the nose.','在规定碰撞中以可控压溃吸收动能，并限制传给生存舱的峰值载荷。','It crushes progressively in prescribed impacts, absorbing energy and limiting peak load into the survival cell.','吸收能量等于力—位移曲线面积；峰值、平均力、稳定折叠和剩余侵入必须同时满足。','Absorbed energy is the force-displacement area; peak, mean force, stable folding and residual intrusion all matter.','它像精心设计的纸吸管，必须一层层折叠，而不是太硬撞停或突然断掉。','It is a carefully engineered crush tube that folds progressively rather than stopping rigidly or snapping.'),
    d('防侵入界面位于碰撞结构根部和前舱壁，紧邻驾驶员脚部前方。','The anti-intrusion interface lies at the crash-structure root and front bulkhead, just ahead of the driver’s feet.','阻止失效碎片或载荷路径穿入生存空间，并把冲击分散进单体壳。','It prevents failed structure or load paths entering the survival space and spreads impact into the monocoque.','局部压溃、冲切和紧固件拉脱需要联合校核；高刚度不应制造新的脆性薄弱环。','Local crushing, punching and fastener pull-out require combined checks; stiffness must not create a brittle weak link.','它是安全舱前门，碰撞结构可以牺牲，但这道门不能被捅穿。','It is the survival cell’s front door: the crash structure may sacrifice itself, but the door must not be pierced.'),
    d('前翼安装接头位于鼻锥下部或侧面，把可拆前翼定位到鼻部结构。','Front-wing joints sit low or laterally on the nose and locate the removable wing to the nose structure.','传递气动、路肩与维修载荷，并保证换件后几何重复性。','They carry aero, kerb and service loads while preserving geometry after replacement.','接头刚度影响翼面实际迎角；销孔间隙、预紧和损伤必须在快速换件后可检查。','Joint stiffness affects actual incidence; hole clearance, preload and damage need rapid post-change inspection.','它像赛车前端的精密插座，既要承载，也要让新前翼插上后仍指向同一方向。','It is a precision front socket that carries load and restores alignment after a wing change.'),
    d('压溃触发和分段结构沿碰撞结构长度布置，常通过铺层、截面或局部弱化定义。','Crush triggers and segments are distributed along the impact structure through laminate, section or local weakening.','让破坏从预定位置开始，并维持接近目标的平均吸能力。','They initiate failure at intended locations and sustain near-target mean energy absorption.','触发太强会产生高峰值，太弱会早期失稳；制造偏差和斜向撞击需要鲁棒性验证。','Triggers that are too strong spike load; too weak buckle early, so manufacturing scatter and oblique impact require robustness.','它们像包装盒上的折痕，告诉结构从哪里开始、按什么顺序压扁。','They are engineered crease lines telling the structure where and how to fold.'),
    d('应变片与加速度计靠近关键载荷路径，目视和无损检查区覆盖接头及可能压溃位置。','Strain gauges and accelerometers sit near critical load paths; inspection zones cover joints and likely crush regions.','记录碰撞或异常路肩事件，并帮助判断外观完好下的内部损伤。','They record impact or severe kerb events and help reveal hidden damage beneath an intact exterior.','峰值加速度需高采样率与防混叠；复材分层还需超声等无损方法而非只看表面。','Peak acceleration needs high-rate anti-aliased sampling; composite delamination needs NDT such as ultrasound, not visual checks alone.','它们像撞击后的行车记录仪和体检设备，告诉工程师鼻锥是否还能安全使用。','They are the impact recorder and medical scan used to decide whether the nose remains safe.'),
  ],
  monocoque: [
    d('碳纤维承载蒙皮形成生存舱内外表面，围绕驾驶员和主要系统构成闭合壳体。','Carbon load-bearing skins form the inner and outer survival-cell surfaces around driver and major systems.','承受弯曲、扭转、剪切与局部撞击，并维持驾驶员保护空间。','They carry bending, torsion, shear and local impact while preserving the protected driver volume.','纤维方向决定各向异性刚度和强度；载荷必须沿连续铺层越过开口与接头。','Fibre orientation sets anisotropic stiffness and strength; continuous load paths must bridge openings and joints.','它像把骨架和皮肤合成一体的蛋壳，轻薄，却靠纤维方向承担整车载荷。','It is a shell combining skeleton and skin, light yet strong through directed fibres.'),
    d('蜂窝夹芯位于内外蒙皮之间，局部实心填充布置在螺栓、锚点和高压区域。','Honeycomb core lies between skins, with solid inserts at bolts, anchors and concentrated-load zones.','以很小质量拉开蒙皮、提高弯曲刚度，并防止局部屈曲。','It separates skins to raise bending stiffness at low mass and prevents local buckling.','夹芯主要传递横向剪切；进水、脱粘和填充边缘应力会削弱夹层协同。','The core mainly carries transverse shear; moisture, debonding and insert-edge stress degrade sandwich action.','它像纸板箱中间的瓦楞层，把两张薄皮撑开后就变成很硬的板。','It is the corrugation in cardboard: separating two thin skins makes a stiff panel.'),
    d('前后舱壁横向封闭单体壳，连接鼻部、悬架、动力单元及其他高载荷接口。','Front and rear bulkheads close the monocoque and connect nose, suspension, power unit and other high-load interfaces.','分配集中载荷并保持闭合截面抗扭，防止壳体被局部压塌。','They distribute concentrated loads, maintain torsionally closed sections and resist local collapse.','舱壁—蒙皮接头的剪流连续性比单块板峰值强度更关键；开孔会重分配载荷。','Shear-flow continuity at bulkhead-skin joints matters more than isolated panel strength; openings redistribute load.','它们像船舱隔板，把薄壳分成多个坚固盒子，并给悬架和动力系统提供墙面。','They are ship bulkheads that form stiff boxes and mounting walls.'),
    d('定制座椅贴合驾驶员躯干，臀点定义在法规、视野、踏板和重心共同约束的位置。','The custom seat fits the driver; hip point is set by rules, visibility, pedals and centre-of-gravity constraints.','分散身体载荷、稳定驾驶姿态，并建立可重复的人机与质量基准。','It spreads body load, stabilizes posture and establishes repeatable ergonomic and mass references.','支撑面应避免局部高压；姿态改变会同时影响头部包络、操纵范围和整车重心。','Support must avoid pressure concentrations; posture affects head envelope, control reach and vehicle CG.','它不是舒适座椅，而是一副量身定做的承载模具，把车手固定在精确位置。','It is not a comfort chair but a fitted load-bearing mould locating the driver precisely.'),
    d('六点安全带跨过肩部、骨盆和双腿并锚固在单体壳强化点。','The six-point harness crosses shoulders, pelvis and legs and anchors to reinforced monocoque points.','在减速度中约束躯干、防止潜滑，并把载荷导入可承受区域。','It restrains the torso, prevents submarining and routes deceleration load into strong body regions.','带角、预紧、伸长和锚点方向决定载荷分布；错误走带会把力集中到软组织。','Belt angles, preload, elongation and anchor direction set load distribution; poor routing concentrates force in soft tissue.','它像把车手和安全舱绑成一个整体的六条受力路径，每一条方向都不能随便。','It is six deliberate load paths tying driver to survival cell; none may be routed casually.'),
    d('头枕包围头盔后侧和两侧，侧防护与检查区沿座舱上缘及高能撞击区域布置。','Headrest surrounds the helmet rear and sides; side protection and inspection zones line cockpit edges and high-energy impact areas.','限制头部相对运动、吸收局部能量并维护侧向侵入边界。','They limit head motion, absorb local energy and preserve lateral intrusion boundaries.','泡沫刚度和厚度必须匹配撞击脉冲；复材下方损伤需要周期性无损检查。','Foam stiffness and thickness must match impact pulses; hidden composite damage needs periodic NDT.','它像头盔周围的缓冲护城河，既留出正常运动，又不让撞击位移失控。','It is a buffer moat around the helmet, allowing normal motion while limiting impact travel.'),
  ],
  halo: [
    d('中央支柱位于驾驶员视线前方，从前安装点向上连接头部保护环。','The central pillar rises in front of the driver from the forward mount into the head-protection ring.','把正面和斜向物体载荷分流到前安装点，同时尽量减小视线遮挡。','It diverts frontal and oblique object loads into the front mount while minimizing visual obstruction.','截面、材料和曲率决定屈曲与塑性变形；视线适应不能替代强度验证。','Section, material and curvature govern buckling and plastic response; visual adaptation does not replace strength proof.','它像头盔前方的一根极强桥柱，细到能看过去，强到能把载荷引开。','It is a very strong bridge pier ahead of the helmet: narrow for sight, strong for load diversion.'),
    d('左右环臂从中央汇合处分向驾驶员两侧并延伸到后安装点。','The left and right hoop arms split from the centre and run around the driver to rear mounts.','在头盔上方和两侧形成连续阻挡路径，应对大物体、轮对和翻滚接触。','They form a continuous barrier above and beside the helmet against large objects, wheels and rollover contact.','弯曲构件会同时承受轴力、弯矩和扭矩；几何连续性避免在转折处形成薄弱铰点。','Curved members carry axial force, bending and torsion; geometric continuity avoids weak hinge points at bends.','它像绕过头部的门框，把可能撞向车手的路径导到座舱两侧。','It is a door frame around the head that redirects incoming paths to the cockpit sides.'),
    d('三处安装点分别位于座舱前方和驾驶员后侧，周围单体壳具有专门局部强化。','Three mounts lie ahead of and behind the driver, each surrounded by dedicated monocoque reinforcement.','把头部保护环载荷扩散进生存舱，避免连接点先于构件失效。','They spread Halo load into the survival cell so attachments do not fail before the member.','螺栓、嵌件和复材的承压、拉脱及分层必须按多方向组合载荷校核。','Bolts, inserts and composite require bearing, pull-out and delamination checks under combined directions.','最强的门框也需要强墙；安装点就是把载荷真正送进安全舱的墙角。','Even the strongest frame needs strong walls; the mounts deliver load into the survival cell.'),
    d('主防滚结构位于驾驶员头部后上方，通常与进气结构和单体壳后部集成。','The primary roll structure sits above and behind the driver, often integrated with intake and rear monocoque structure.','在翻滚中支撑车辆，并与其他结构建立不侵入头部的保护线。','It supports the car in rollover and forms a non-intrusion protection line with other structures.','结构需抵抗多方向集中载荷且限制挠度；载荷路径要避开进气空腔等弱区。','It must resist multi-direction concentrated loads with limited deflection and route around intake cavities.','它像赛车翻过来后的最高承重点，让地面先压结构而不是头盔。','It is the highest rollover bearing point, keeping ground load off the helmet.'),
    d('次防滚结构位于座舱前方，与主结构共同定义头盔上方的几何保护线。','The secondary roll structure lies ahead of the cockpit and defines a helmet clearance line with the primary structure.','为不同翻滚姿态提供第二支点，并约束驾驶员头部必须位于的安全包络。','It provides a second support for rollover attitudes and bounds the permitted head envelope.','静态几何检查必须考虑车手姿态、头盔尺寸和结构挠度，而不是只连两条理论直线。','Geometry checks include posture, helmet size and structural deflection, not just ideal lines.','它和后方主防滚结构像两座桥塔，中间连出的线必须始终高过车手。','Together with the rear structure it forms two towers whose clearance line stays above the driver.'),
    d('头盔和头枕位于三维保护包络内部，包络还考虑车手运动、救援和设备公差。','Helmet and headrest remain inside a 3-D protected envelope that includes driver motion, rescue and equipment tolerances.','把所有结构指标转化为车手实际可用的安全空间，并限制危险接触。','It turns structural requirements into usable driver space and limits hazardous contact.','保护不能只靠某个零件；头盔、HANS、头枕、座椅、安全带和上部结构必须作为系统验证。','Protection is systemic: helmet, HANS, headrest, seat, harness and upper structures require joint validation.','它是最终要守住的“空气盒子”：所有结构存在的目的，都是不让外物进入这块空间。','It is the air box that must be preserved; every structure exists to keep hazards out of it.'),
  ],
  tires: [
    d('胎面胶料覆盖轮胎最外层并直接接触赛道，下方工作层承受反复剪切与发热。','Tread compound forms the road-contacting outer layer, with a working layer beneath undergoing cyclic shear and heating.','生成纵向与横向力，并在有限温度窗口内提供可重复摩擦。','It generates longitudinal and lateral force within a finite repeatable temperature window.','黏弹性、路面粗糙度和滑移产生摩擦与热；温度过低、过高或表面损伤都会改变峰值。','Viscoelasticity, roughness and slip create force and heat; cold, overheating or damage shifts the peak.','它是赛车唯一真正“抓住”地面的软材料，所有动力和下压力最终都要通过这一层。','It is the only soft material gripping the road; all power and downforce ultimately pass through it.'),
    d('带束层与胎体位于胎面下方，从一侧胎圈跨到另一侧形成承压骨架。','Belts and carcass lie beneath the tread and span bead to bead as the pressure-carrying skeleton.','控制轮胎轮廓、垂向刚度、侧向顺从和高速离心增长。','They control profile, vertical stiffness, lateral compliance and high-speed growth.','帘线角度、张力与橡胶剪切共同决定各向异性变形和接地印迹。','Cord angle, tension and rubber shear create anisotropic deformation and shape the contact patch.','它像充气帐篷的纤维骨架，气压负责撑开，帘线决定它往哪个方向变形。','It is a fibre skeleton in an inflatable tent: pressure expands it, cords direct deformation.'),
    d('胎圈嵌在轮胎内缘并夹持轮辋座，是气密和传力的环形界面。','The bead sits at the tyre inner edge on the rim seat, forming an annular sealing and load-transfer interface.','把驱动、制动和侧向载荷从橡胶结构传入轮辋，并防止脱圈。','It transfers drive, brake and lateral load into the rim while preventing unseating.','胎圈钢丝张力、座面几何、装配润滑与低压横载共同决定保持能力。','Bead-wire tension, seat geometry, mounting lubrication and low-pressure lateral load determine retention.','它像高压罐盖的锁边，既要密封，也要在巨大侧向力下不跳出卡槽。','It is the locking edge of a pressure vessel, sealing while resisting lateral unseating.'),
    d('18英寸轮辋位于轮胎中心；规定的环形轮罩覆盖外侧，单一中央紧固件及双重保持机构固定整个车轮。','The 18-inch rim sits at tyre centre; a mandated annular outboard disc covers its outer face, while one central fastener with dual retention secures the wheel.','支撑胎圈、传递轮端载荷，并用连续外表面管理车轮外侧气流，同时兼顾非簧载质量与制动散热。','It supports the beads, carries wheel loads and presents a continuous outer surface to the airflow while balancing unsprung mass and brake heat rejection.','轮辋承受弯曲、扭转、冲击和热梯度；中央螺母预紧力保持装配，双保持机构防止松脱后失轮，径向跳动与刚度也会影响轮胎测量。','The rim sees bending, torsion, impact and thermal gradients; centre-nut preload clamps the assembly, dual retention protects against wheel loss, and runout and stiffness affect tyre measurements.','它是轮胎、制动和悬架之间的承力转接盘；外侧像一只平整的盖子，中间只用一颗高预紧力轮母快速装拆。','It is the structural adapter between tyre, brake and suspension, with a smooth outer cover and one highly preloaded centre nut for rapid changes.'),
    d('气腔封闭在胎体和轮辋之间，气门及压力控制接口位于轮辋。','The cavity is enclosed by carcass and rim, with valve and pressure-control interface in the wheel.','用气体支撑载荷、调节刚度，并为每次运行建立可重复初始条件。','Gas supports load, tunes stiffness and establishes repeatable run-start conditions.','绝对压力随气体温度和有效体积变化；冷态设定不能直接当作热态工作压力。','Absolute pressure changes with gas temperature and effective volume; cold setting is not hot running pressure.','它像轮胎里看不见的弹簧，几圈之后变热，弹簧也会变硬。','It is an invisible pneumatic spring that stiffens as the tyre heats.'),
    d('压力传感器连接气腔，红外或表面温度测量覆盖胎面内中外区域。','Pressure sensing connects to the cavity; infrared or surface measurements cover inner, middle and outer tread zones.','监控工作窗口、泄漏、温度分布和驾驶/设定造成的能量输入。','They monitor operating window, leakage, temperature distribution and energy input from driving and setup.','表面温度响应快但不等于胎体体温；测量时间、发射率和赛后冷却必须记录。','Surface temperature responds quickly but differs from bulk carcass temperature; timing, emissivity and cool-down matter.','它们是轮胎的体温计和血压计，要结合测量时刻才知道轮胎真正处于什么状态。','They are tyre thermometer and pressure gauge; timing is essential to interpret condition.'),
  ],
  brakes: [
    d('碳碳盘安装在四个轮毂并位于轮辋内部，摩擦环与通风结构共同旋转。','Carbon-carbon discs mount to all wheel hubs inside the rims, with friction rings and ventilation rotating together.','把车辆动能转成热，并在高温窗口内提供低质量、高功率制动。','They convert vehicle kinetic energy to heat with low mass and high power in a hot operating window.','摩擦系数与温度、压力和表面状态相关；热梯度同时产生膨胀、氧化和热应力。','Friction depends on temperature, pressure and surface state; gradients drive expansion, oxidation and thermal stress.','它像能反复烧红的能量海绵，每次制动都把速度暂存为盘里的热。','It is a reusable heat sponge, storing vehicle speed as disc temperature.'),
    d('多活塞卡钳跨坐制动盘，摩擦片位于盘两侧并通过轮端支架固定。','Multi-piston calipers straddle each disc, with pads on both faces and a rigid upright mount.','把液压压力变成夹紧力，再通过有效半径形成轮端制动力矩。','They turn hydraulic pressure into clamp force and then wheel torque through effective radius.','活塞面积、摩擦系数、盘半径和卡钳刚度共同决定力矩与踏板行程。','Piston area, friction, effective radius and caliper stiffness set torque and pedal travel.','它像双手夹住旋转盘，液压决定手握多紧，盘半径决定制动力臂。','It is two hands squeezing a rotating disc: pressure sets grip, radius sets leverage.'),
    d('主缸和踏板位于驾驶员脚前，独立液压回路通往前后卡钳。','Master cylinders and pedal sit ahead of the driver, feeding independent hydraulic circuits to the calipers.','把脚力按可控比例转成前后制动压力，并保留机械液压失效路径。','They turn foot force into controlled front/rear pressure with a mechanical-hydraulic fallback path.','踏板比、主缸面积、平衡机构和系统顺从决定压力、行程和前后分配。','Pedal ratio, master-cylinder area, balance mechanism and compliance set pressure, travel and split.','它像脚下的液压放大器，但前后两路需要精确分工且不能互相拖垮。','It is a foot-operated hydraulic amplifier with two carefully separated circuits.'),
    d('后轴线控制动执行器位于后制动液压路径，与电子控制和机械安全边界相连。','The rear brake-by-wire actuator lies in the rear hydraulic path and interfaces with electronic control and mechanical safety limits.','在车手总制动需求中补偿能量回收变化，维持可预测的后轴制动力。','It compensates for changing regeneration so total rear braking follows driver demand predictably.','控制器以目标后轴力减去可用回收力求液压力；延迟、饱和和故障切换决定踏板一致性。','Control subtracts available regen from target rear force; delay, saturation and fallback govern consistency.','它像后轴制动的调音台：电机制动变多时液压变少，总音量仍要保持。','It is a rear-brake mixer: more motor braking means less hydraulic braking for the same total.'),
    d('MGU-K通过动力单元和传动系统作用于后轮，与摩擦制动在后轴汇合。','MGU-K acts on the rear wheels through the power unit and driveline, combining with friction braking at the axle.','回收部分动能为电能，同时受功率、能量、附着、SOC和温度限制。','It recovers kinetic energy electrically, bounded by power, energy, grip, SOC and temperature.','回收力矩经齿比映射到轮端；降挡、车速和电池接受能力会连续改变可用值。','Regeneration maps through gear ratio to the wheels; shifts, speed and battery acceptance continuously change availability.','它像只作用在后轮的发电机刹车，省下热量，但不能替代全部四轮摩擦制动。','It is a rear-axle generator brake that saves heat but cannot replace four-wheel friction braking.'),
    d('制动导管从车轮内侧进气并指向盘和卡钳，温度与压力传感器布置在热端和液压端。','Brake ducts feed air from inboard openings to disc and caliper; thermal and pressure sensors cover hot and hydraulic ends.','控制盘片温度并记录压力—减速度—温度链，用于热管理和故障诊断。','They manage brake temperature and record the pressure-deceleration-temperature chain for diagnosis.','风量过少会衰退，过多会增加阻力或让盘低于工作窗；传感器热辐射误差需校正。','Too little flow causes fade; too much adds drag or overcools, and radiative sensor error needs correction.','它是制动系统的风道和体检仪：既给盘降温，也证明每一脚刹车发生了什么。','It is the brake’s cooling duct and medical chart, controlling heat and documenting every stop.'),
  ],
  'front-suspension': [
    d('上控制臂连接单体壳上部硬点与前轮立柱，通常由两支杆构成三角定位。','The upper wishbone connects upper monocoque hardpoints to the front upright through a triangulated pair of members.','约束轮端横向与纵向位置，并参与定义外倾增益、主销轴线和侧倾中心。','It locates the wheel and helps define camber gain, steering axis and roll centre.','杆件以轴向拉压为主；硬点三维位置决定运动学，顺从性又会在载荷下改变理论几何。','Members mainly carry axial load; 3-D hardpoints set kinematics while compliance shifts geometry under load.','它像定位相机的上方两根支杆，长度和落点决定车轮怎样倾斜与移动。','It is the upper pair of locating rods; their lengths and anchors determine wheel motion.'),
    d('下控制臂连接单体壳较低硬点与立柱下部，跨越更大的轮端载荷路径。','The lower wishbone links lower chassis hardpoints to the upright and spans a major wheel-load path.','承受大部分横向和制动反力，并与上臂共同控制轮距、外倾和侧倾中心。','It carries much lateral and braking reaction and works with the upper arm to control track, camber and roll centre.','轴向载荷与接头偏心会产生附加弯曲；离地间隙和气动外形也限制杆件布置。','Axial load plus joint eccentricity creates secondary bending; clearance and aero shape constrain placement.','它像车轮下方的承重三脚架，既定位置，又把轮胎的力送回车身。','It is the lower load-bearing tripod, locating the wheel and returning tyre force to the chassis.'),
    d('推杆或拉杆从立柱连接到车体内摇臂，立柱同时承载轮毂、制动和转向接头。','A pushrod or pullrod links upright to an inboard rocker; the upright also carries hub, brake and steering joints.','把轮跳转换为车内弹簧行程，并汇集轮胎、制动和转向载荷。','It converts wheel travel into inboard spring motion and collects tyre, brake and steering loads.','安装比由杆件和摇臂瞬时几何决定；立柱刚度会影响外倾、轴承对中与制动拖滞。','Motion ratio follows instantaneous geometry; upright stiffness affects camber, bearing alignment and brake drag.','它是轮端的枢纽和传动杆，把路面上下运动送到车体内的弹簧。','It is the wheel hub and motion link, sending road travel to inboard springs.'),
    d('摇臂围绕车体轴承转动，扭杆沿摇臂轴线或附近安装在单体壳内。','The rocker pivots on chassis bearings, with a torsion spring mounted along or near its axis inside the monocoque.','改变位移与力的比例，并用扭杆提供主要轮跳弹性。','It transforms displacement and force while the torsion bar supplies primary wheel springing.','摇臂轮廓决定非线性安装比；扭杆刚度与有效长度、材料剪切模量和直径四次方相关。','Rocker profile sets nonlinear motion ratio; torsion stiffness follows effective length, shear modulus and diameter to the fourth power.','它像自行车曲柄带一根会扭的弹簧轴，把小轮跳变成可调的弹簧转角。','It is a crank driving a twist spring, converting wheel travel into tunable angular deflection.'),
    d('第三弹性元件和阻尼器横置或纵置在车体内，并通过摇臂接受左右轮组合运动。','The heave element and dampers are mounted inboard and receive combined left-right wheel motion through rockers.','分别控制整轴升沉平台与运动速度，稳定底板和翼面工作高度。','They control axle heave and motion rate, stabilizing floor and wing ride heights.','左右同向运动主要激励升沉支路，反向运动主要激励侧倾支路；阻尼力随速度和阀系变化。','In-phase wheels excite heave, opposite-phase wheels excite roll; damping follows velocity and valving.','它把“两个轮一起动”和“一个上一个下”分开处理，让气动平台与机械抓地各有调节。','It separates both-wheels-together from one-up-one-down motion for aero platform and mechanical grip.'),
    d('防倾机构、限位块和位移传感器布置在摇臂及弹簧支路附近，处于车内可调区域。','Roll devices, travel stops and displacement sensors sit near rockers and spring paths in an accessible inboard zone.','设定侧倾刚度、保护极限行程并测量真实悬架与空气动力平台状态。','They set roll stiffness, protect travel limits and measure actual suspension and aero-platform state.','限位接触会让刚度突变；传感器换算需使用瞬时安装比并扣除结构顺从。','Bump-stop engagement changes stiffness sharply; sensor conversion needs instantaneous motion ratio and compliance correction at each sample.','它们是悬架的防撞边界和刻度尺，告诉工程师什么时候进入第二段刚度。','They are suspension boundaries and rulers, revealing when a second stiffness regime engages.'),
  ],
  'rear-suspension': [
    d('上控制臂组连接后部壳体上方硬点与后轮立柱，并避让传动轴和气流。','The upper rear links connect high casing hardpoints to the upright while clearing driveshaft and airflow.','定位后轮外倾与束角，并传递横向、驱动和制动载荷的一部分。','They locate rear camber and toe and carry portions of lateral, drive and braking load.','后轴没有转向指令容错，微小顺从转向也会形成高速偏航；硬点和接头刚度需共同验证。','With no commanded rear steer, tiny compliance steer creates high-speed yaw; hardpoints and joint stiffness need joint validation.','它像后轮上方的导轨，必须让车轮只按设计轨迹动，不能在大扭矩下偷偷转向。','It is the rear wheel’s upper guide, preventing unintended steer under high torque.'),
    d('下控制臂组从变速箱或后部结构低位连接立柱，靠近主要轮胎力作用平面。','Lower links run from low gearbox or rear-structure hardpoints to the upright near the main tyre-force plane.','承受显著横向、纵向和千斤顶效应载荷，并建立轮端基础定位。','They carry major lateral, longitudinal and jacking loads and provide fundamental wheel location.','连杆角度决定反蹲与几何升降；壳体接头既是悬架硬点也是动力总成结构载荷入口。','Link angles set anti-squat and geometric jacking; casing joints are both suspension hardpoints and power-unit load entries.','它像把后轮系在变速箱上的下方三角架，抓地力和驱动力都从这里回到车身。','It is the lower tripod tying rear wheel to gearbox, returning grip and drive force.'),
    d('推杆或拉杆从后轮立柱绕开半轴连接车内摇臂，立柱承载轮毂和卡钳。','The rear pushrod or pullrod clears the halfshaft and links upright to an inboard rocker carrying hub and caliper loads.','把后轮跳动送入弹簧阻尼系统，并在紧凑空间中保持传动与悬架自由度。','It transmits wheel travel to spring-damper hardware while preserving driveline and suspension articulation.','运动比随行程变化；杆件屈曲、万向节角和制动反力共同限制布置。','Motion ratio varies with travel; rod buckling, joint angles and brake reaction constrain packaging.','它像穿过复杂管线的机械连杆，把车轮运动准确送到藏在车体里的弹簧。','It is a motion link threaded through dense packaging to reach hidden springs.'),
    d('摇臂、弹簧和阻尼器集中在变速箱顶部或两侧，处于高温且振动强的后部环境。','Rockers, springs and dampers cluster atop or beside the gearbox in a hot, highly vibrating rear environment.','提供后轮垂向刚度和速度相关控制，同时支持快速赛道调节。','They provide rear vertical stiffness and velocity-dependent control with rapid setup adjustment.','阻尼器油温改变黏度与阀系响应；安装刚度和热屏蔽决定标定能否保持。','Damper-oil temperature changes viscosity and valve response; mount stiffness and shielding preserve calibration.','它是后轴的弹簧与减振器机房，离排气和变速箱很近，热管理也属于悬架设计。','It is the rear axle’s spring room, close enough to exhaust and gearbox that thermal control matters.'),
    d('防倾和第三弹性元件跨接左右摇臂，用不同机械路径响应侧倾与升沉。','Roll and heave elements cross-connect left and right rockers through distinct mechanical paths.','独立调节后轴侧倾分配与气动平台升沉刚度。','They independently tune rear roll distribution and aero-platform heave stiffness.','侧倾刚度影响前后轮载荷转移分配，升沉刚度影响车高；二者仍通过几何和限位产生耦合。','Roll stiffness shifts axle load-transfer distribution; heave stiffness controls ride height, with coupling through geometry and stops.','它像把后悬架拆成两个旋钮：一个管车身歪多少，一个管整车蹲多少。','It turns rear suspension into two knobs: body roll and whole-axle heave.'),
    d('半轴横跨差速器与轮毂，束角和位移测量靠近立柱、拉杆或摇臂。','Halfshafts span differential to hubs; toe and displacement sensing sits near upright, toe link or rocker.','传递驱动力并监控扭矩作用下的束角、轮跳和接头状态。','They transmit drive torque and monitor toe, travel and joint condition under power.','等速节角度引起损失与轴向力；半轴扭转和束角顺从会改变瞬态牵引与稳定性。','CV-joint angle creates loss and plunge force; shaft twist and toe compliance alter transient traction and stability.','它们一边是传递动力的旋转轴，一边是检查后轮是否在加速时被扭偏的测量链。','They combine rotating drive shafts with the measurement chain that catches power-induced rear steer.'),
  ],
  steering: [
    d('可拆方向盘位于驾驶员双手前方，通过快速接头连接转向柱并集成显示器。','The detachable steering wheel sits at the driver’s hands, joins the column through a quick release and carries a display.','传递转向力矩、显示关键状态，并提供驾驶员可触达的控制入口。','It transmits steering torque, displays critical state and provides reachable controls.','轮缘刚度、快速接头间隙和显示可读性影响精度；拆卸能力还属于逃生与救援路径。','Rim stiffness, quick-release play and display readability affect precision; removal is also an egress and rescue requirement.','它既是方向盘，也是赛车仪表盘和主要控制台，且必须能被迅速拔下。','It is steering wheel, dashboard and main control panel, yet must release rapidly.'),
    d('换挡拨片位于轮缘背后，旋钮和按键按驾驶员手指可达区布置在面板上。','Shift paddles sit behind the rim; rotaries and buttons are placed within finger reach on the face.','让驾驶员不离开方向盘完成换挡、模式、差速和能量等指令。','They let the driver command shifts, modes, differential and energy without releasing the wheel.','控制布局需防误触并提供触觉区分；拨片行程、去抖和双侧逻辑影响响应。','Layout prevents accidental activation and provides tactile coding; paddle travel, debounce and dual-side logic set response.','它像车手手边的快捷键盘，每个控件都要在颠簸和戴手套时仍能盲操作。','It is a glove-friendly shortcut keyboard designed for blind use under vibration.'),
    d('转向柱从方向盘穿过座舱前部，万向节绕开车手腿部和结构障碍连接小齿轮。','The column runs forward from the wheel; universal joints route around legs and structure to the pinion.','传递双向力矩并在有限空间内保持低摩擦、低回差和安全变形路径。','It transmits bidirectional torque with low friction and backlash while providing a safe collapse path.','万向节相位错误会引起角速度不均；柱系模态、接头游隙和轴向入侵都需检查。','Incorrect U-joint phasing creates velocity variation; modes, joint play and axial intrusion require checks.','它像绕过障碍的传动轴，弯得了路线，但手和车轮之间不能有松旷。','It is a routed driveshaft: the path may bend, but the hand-to-wheel connection must stay tight.'),
    d('齿条和小齿轮位于前舱壁附近，横拉杆从齿条两端连接左右转向节。','Rack and pinion sit near the front bulkhead, with tie rods linking rack ends to steering arms.','把方向盘旋转变成左右车轮受控且不同的转角。','They convert wheel rotation into controlled, differing left and right road-wheel angles.','齿距、转向臂和硬点决定瞬时转向比、阿克曼与跳动转向；摩擦影响回正手感。','Pitch, steering arms and hardpoints set instantaneous ratio, Ackermann and bump steer; friction affects return feel.','它像把旋钮动作变成左右推拉的尺子，并按几何让内轮比外轮多转一点。','It turns rotation into lateral ruler motion and gives the inner wheel extra angle.'),
    d('油门和制动踏板位于脚舱，离合控制通常位于方向盘拨片并作用于起步过程。','Throttle and brake pedals occupy the footwell; clutch control is commonly on wheel paddles for launch operation.','采集车手纵向需求，并通过独立安全逻辑形成扭矩、制动力和离合指令。','They capture longitudinal demand and create torque, braking and clutch commands through independent safety logic.','双通道踏板需要相关性检查；制动踏板还保留真实液压力和行程，离合存在抓合点标定。','Dual pedal channels need correlation checks; brake retains real pressure/travel and clutch needs bite-point calibration.','它们是车手给赛车的“快、慢、起步”三种主要命令，每条命令都必须能被验证。','They are the driver’s go, stop and launch commands, each independently validated.'),
    d('位置和扭矩传感器成对布置在方向盘、柱系、齿条或踏板关键输入点。','Position and torque sensors are paired at key wheel, column, rack or pedal inputs.','确认驾驶员意图、机械系统实际响应和冗余通道一致性。','They confirm driver intent, mechanical response and redundant-channel agreement.','双通道应具有可检测的比例或方向关系；偏置漂移、卡滞和断线需要在控制周期内识别。','Dual channels need a detectable scale or direction relationship; bias drift, sticking and open circuits require timely detection.','它们像两名同时记分的裁判，读数不一致时系统不会盲目相信其中一个。','They are two scorekeepers; disagreement prevents blind trust in either reading alone.'),
  ],
  battery: [
    d('高功率电芯组成模组并封装在生存舱后部或规定保护区域的能量存储壳体内。','High-power cells form modules inside an energy-store enclosure behind the survival cell or another protected zone.','储存回收能量并在加速时以高功率向混动系统供电。','They store recovered energy and deliver high power to the hybrid system during acceleration.','端电压由SOC、温度、电流和内阻共同决定；可用功率常先受热与电压边界限制。','Terminal voltage follows SOC, temperature, current and resistance; thermal and voltage limits often cap power first.','它像能极快充放的小型水库，容量重要，但进出水速度和温度同样决定能不能用。','It is a small reservoir with very fast flow; capacity, rate and temperature all govern use.'),
    d('母排在模组之间形成低阻高流路径，熔断器和电流测量布置在主要支路或总输出端。','Busbars create low-resistance high-current paths between modules, with fusing and current sensing on key branches or output.','汇集电能、限制短路后果并提供SOC与能量计算所需电流证据。','They collect power, limit short-circuit consequences and provide current evidence for SOC and energy accounting.','焦耳热随电流平方增长；连接电阻、热循环和电磁力决定热点与疲劳。','Joule heat rises with current squared; joint resistance, thermal cycling and electromagnetic force determine hot spots and fatigue.','它像电池里的高速公路和保险闸，既要通大流量，也要在事故时迅速断开。','It is the energy store’s highway and fuse gate, carrying huge flow but opening during faults.'),
    d('主接触器和预充支路位于高压输出入口，连接电池与直流母线。','Main contactors and precharge branch sit at the high-voltage outlet between energy store and DC link.','在授权时安全接通高压，并先限制电容充电浪涌。','They safely energize high voltage and limit capacitor inrush before main connection.','预充电阻形成RC充电；母线电压达到阈值后才闭合主接触器，否则触点可能焊接。','The precharge resistor forms an RC charge; main contactors close only after a voltage threshold to avoid welding.','它像先开小水龙头把管路灌满，再打开总阀，避免一瞬间的冲击。','It opens a small fill path before the main valve to avoid a violent surge.'),
    d('电池管理单元连接每组电芯电压、温度和绝缘监测，并与整车控制器通信。','The BMS connects to cell-group voltage, temperature and insulation sensing and communicates with vehicle control.','估计SOC与功率边界、平衡单体并在异常时请求降额或隔离。','It estimates SOC and power limits, balances cells and requests derating or isolation on faults.','库仑计量会累积漂移，需要开路电压或模型校正；最弱单体决定整包可用边界。','Coulomb counting drifts and needs voltage or model correction; the weakest cell bounds the pack.','它是电池的会计和安全主管，逐节核对，不能只看整包平均值。','It is battery accountant and safety manager, auditing individual cells rather than pack averages.'),
    d('冷却板贴近模组底部或侧面，绝缘层隔开高压与壳体，泄压路径通向安全区域。','Cooling plates contact module bases or sides, insulation separates HV from enclosure, and vents lead to a safe zone.','均匀带走热量、防止触电，并在异常产气时控制压力和排放方向。','They remove heat uniformly, prevent shock and manage pressure and gas direction during abnormal events.','温差、界面热阻和流量决定单体离散；绝缘爬电距离与泄压能力属于不同安全层。','Temperature spread follows interface resistance and flow; creepage and venting are separate safety layers.','它把散热器、绝缘垫和安全泄压口放进同一个盒子，分别处理热、电和气体风险。','It combines cooling, electrical insulation and controlled venting to address three distinct hazards.'),
    d('碰撞壳体包围全部高压部件，高压互锁串联连接器、盖板和维修断开点。','The crash enclosure surrounds all HV hardware; the interlock chains connectors, covers and service disconnects.','在撞击中防侵入并在任何接口被打开时阻止高压保持接通。','It resists intrusion and prevents HV remaining energized when any protected interface opens.','结构完整性、绝缘电阻和互锁状态需要独立监控；断开命令后还要验证母线放电时间。','Structural integrity, insulation resistance and interlock state need independent monitoring; bus discharge time is verified after shutdown.','它像高压保险箱，外壳守住碰撞，门磁回路保证有人开盖时电已经切断。','It is a high-voltage safe: armour handles impact and the door loop ensures power is off when opened.'),
  ],
  inverter: [
    d('功率半导体桥臂位于逆变器功率模块内，三相输出连接MGU-K绕组。','Power semiconductor bridge legs sit in the inverter module and feed the MGU-K three-phase windings.','把直流电变成可控交流，也在回收时把交流能量送回直流母线。','They convert DC to controlled AC and return AC energy to the DC link during regeneration.','开关状态合成相电压；导通损耗与开关损耗随电流、频率、温度和器件特性变化。','Switch states synthesize phase voltage; conduction and switching losses follow current, frequency, temperature and device properties.','它像每秒开关成千上万次的高速阀门，把直流切成电机需要的三相波形。','It is a bank of ultra-fast valves chopping DC into the three-phase waveform the motor needs.'),
    d('直流母线和电容位于电池输入与功率桥之间，并尽量缩短高频电流回路。','The DC link and capacitors sit between energy-store input and bridge with a short high-frequency current loop.','稳定母线电压、吸收纹波并给开关瞬间提供局部电流。','They stabilize DC voltage, absorb ripple and supply local switching current.','寄生电感与电流变化率产生过压；电容ESR、纹波电流和温度决定寿命。','Parasitic inductance with di/dt creates overshoot; capacitor ESR, ripple current and temperature set life.','它像逆变器门口的小蓄水池，承担快速脉动，避免每次开关都冲击远处电池。','It is a local reservoir handling fast pulses so each switch event does not strike the distant battery.'),
    d('栅极驱动紧贴功率器件，快速保护通过隔离链路监测电流、电压和器件状态。','Gate drives sit next to power devices, with isolated fast protection monitoring current, voltage and device state.','以受控速度开关器件，并在短路或去饱和时微秒级关断。','They switch devices at controlled speed and shut down within microseconds on short circuit or desaturation.','开得太快增加过压和电磁干扰，太慢增加损耗；保护关断还需避免二次过压。','Too-fast switching raises overshoot and EMI, too slow raises loss; protective turn-off must avoid secondary overvoltage.','它像功率开关的神经和反射弧，正常时精确发令，短路时不等主电脑思考就先自救。','It is the switch’s nerve and reflex, acting locally before the main controller can react.'),
    d('电流和电压传感器位于直流及三相路径，转子位置采样来自旋变或等效角度传感器。','Current and voltage sensors cover DC and phase paths; rotor position comes from a resolver or equivalent angle sensor.','给转矩控制、功率计算、保护和换相提供实时状态。','They provide real-time state for torque control, power calculation, protection and commutation.','采样偏置和相位延迟会形成转矩误差；角度误差在高速弱磁区尤其敏感。','Sampling bias and phase delay create torque error; angle error is especially critical in high-speed field weakening.','它们告诉逆变器电流有多大、转子朝哪里，否则高速开关只是在盲目猜测。','They tell the inverter current magnitude and rotor angle; without them switching is guesswork.'),
    d('控制板位于屏蔽低压区域，运行电流环、转矩映射、调制及诊断软件。','The control board occupies a shielded low-voltage region and runs current loops, torque maps, modulation and diagnostics.','把整车扭矩请求转换为满足电机和电池边界的开关指令。','It converts vehicle torque demand into switching commands within motor and battery limits.','内环带宽、PWM频率和计算延迟决定动态；限幅与抗积分饱和避免边界切换失控。','Inner-loop bandwidth, PWM rate and compute delay set dynamics; saturation handling prevents loss of control at limits.','它像翻译官，把“需要多少轮上扭矩”翻成每个功率开关下一瞬间该怎么动作。','It translates requested wheel torque into the next switching action of every power device.'),
    d('冷却板直接贴合功率模块，绝缘与屏蔽围绕高压节点、低压控制和外部线束。','The cooling plate contacts power modules directly; insulation and shielding separate HV nodes, controls and harnesses.','排出损耗热、保持电气隔离并限制电磁干扰进入传感与通信。','They reject loss heat, maintain electrical isolation and contain EMI from sensing and communication.','结温由损耗和热阻网络决定；共模电压通过寄生电容耦合，需要接地和屏蔽闭合路径。','Junction temperature follows loss and thermal impedance; common-mode voltage couples through parasitic capacitance and needs closed shielding paths.','它既是逆变器的散热底座，也是把高压噪声关在盒子里的隔音墙。','It is both heat sink and acoustic wall for high-voltage electrical noise.'),
  ],
  motor: [
    d('1.6升V6内燃机纵向安装在驾驶员后方，并作为后部承载链的一部分连接单体壳与变速箱。','The 1.6-litre V6 sits longitudinally behind the driver and forms part of the load path between monocoque and gearbox.','把燃料化学能转成曲轴功率，并为整套混动动力单元提供基础扭矩。','It converts fuel energy into crankshaft power and supplies the hybrid power unit’s base torque.','四冲程燃烧的有效功受空气质量、燃料流、点火、压缩和损失制约；爆震与热负荷限制峰值。','Four-stroke output follows air mass, fuel flow, ignition, compression and losses; knock and heat bound the peak.','它是持续输出的主热机，像高效燃烧泵，但必须和电机、涡轮及能量计划共同工作。','It is the sustained-output heat engine, an efficient combustion pump coordinated with motor, turbo and energy plan.'),
    d('涡轮和压气机通过同轴布置在发动机进排气两侧，处于极高转速和温度区域。','Turbine and compressor share a shaft across intake and exhaust sides in an extreme speed and temperature zone.','用排气能量压缩进气，提高气缸空气质量和可用功率。','They use exhaust energy to compress intake air, increasing cylinder air mass and available power.','涡轮功与压气机功及轴系损失平衡；压比、流量和转速必须远离喘振、堵塞和超速边界。','Turbine power balances compressor demand and shaft loss; pressure ratio, flow and speed must avoid surge, choke and overspeed.','它像由排气驱动的高压风泵，回收本来会从排气管流走的能量。','It is an exhaust-driven high-pressure air pump recovering energy that would otherwise leave the tailpipe.'),
    d('进气从车顶入口经压气机和冷却器进入歧管，燃烧后气体经排气歧管驱动涡轮并排出。','Air travels from overhead intake through compressor and cooler to the plenum; combustion gas drives the turbine and exits.','以低损失、均匀分配和受控温度完成空气—燃烧—排气质量流链。','It carries the air-combustion-exhaust mass-flow chain with low loss, uniform distribution and controlled temperature.','脉动排气影响涡轮能量，进气温度影响密度和爆震；管长、容积与背压造成瞬态权衡。','Pulsed exhaust affects turbine energy, while intake temperature affects density and knock; lengths, volumes and backpressure trade transient response.','它是发动机的呼吸系统：吸入、压缩、降温、燃烧，再用呼出的热气推动涡轮。','It is the engine respiratory system: inhale, compress, cool, burn, then drive the turbine with hot exhaled gas.'),
    d('MGU-K与动力单元传动轴系机械连接，并通过三相高压线连接逆变器。','MGU-K is mechanically coupled to the power-unit driveline and electrically connected to the inverter by three-phase HV cables.','加速时提供电机扭矩，制动时回收后轴机械能，并受规则与系统边界约束。','It adds motor torque under acceleration and recovers rear-axle mechanical energy under braking within rule and system limits.','电磁转矩与电流相关，机械功为转矩乘角速度；转速、电压、热和能量状态共同限制可用功率。','Electromagnetic torque follows current and mechanical power is torque times speed; voltage, thermal and energy state bound output.','它是一台能瞬间换方向工作的电机：直道助推，刹车时立刻变成发电机。','It is a reversible electric machine: boost on acceleration, generator during braking.'),
    d('燃料、润滑和液压附件围绕发动机与变速箱布置，通过泵、管路和储罐形成独立回路。','Fuel, lubrication and hydraulic auxiliaries surround engine and gearbox in separate pump, line and reservoir circuits.','按受控压力输送燃料，建立油膜冷却摩擦副，并驱动作动器等辅助负载。','They meter fuel, maintain lubricating oil films and cooling, and power hydraulic actuators and auxiliaries.','流量与压降必须覆盖高横纵向加速度；气蚀、曝气、黏度和过滤状态决定可靠性。','Flow and pressure margin must survive high g; cavitation, aeration, viscosity and filtration govern reliability.','它们是动力单元的血液循环和液压肌肉，主机再强也离不开稳定供给。','They are the power unit’s circulation and hydraulic muscles; the core engine depends on stable supply.'),
    d('扭矩、爆震、转速和温度传感器分布在曲轴、缸体、燃烧室、涡轮轴及流体回路。','Torque, knock, speed and temperature sensing spans crankshaft, block, combustion zones, turbo shaft and fluid circuits.','闭环控制燃烧与混动输出，并在爆震、超速、过热或润滑异常前触发保护。','They close the combustion and hybrid loops and protect against knock, overspeed, overheating and lubrication faults.','不同信号带宽差异很大：爆震需高频分析，温度较慢；所有通道仍要统一时间基准和合理性。','Bandwidths differ greatly: knock needs high-frequency analysis and temperature is slow; all channels require common timing and plausibility.','它们是发动机的耳朵、转速表和体温计，让控制器知道每一次燃烧是否健康。','They are engine ears, tachometer and thermometer, revealing the health of each combustion event.'),
  ],
  differential: [
    d('多挡齿轮组和输入、输出轴沿变速箱壳体布置在动力单元之后。','The multi-ratio gear train and input/output shafts occupy the gearbox casing behind the power unit.','用离散传动比把动力单元高转速转成赛道所需轮速与轮上扭矩。','They use discrete ratios to convert high power-unit speed into required wheel speed and torque.','啮合比决定速度和扭矩转换；齿根弯曲、齿面接触、效率和轴系扭振共同约束设计。','Mesh ratio transforms speed and torque; tooth bending, contact stress, efficiency and torsional vibration constrain design.','它像一组可选杠杆，让同一台动力单元在慢弯和高速直道都落在有效转速区。','It is a selectable set of levers keeping the same power unit effective in slow corners and long straights.'),
    d('换挡鼓、拨叉和执行器安装在齿轮组侧面，通过短行程移动接合机构。','The shift drum, forks and actuator sit beside the gearset and move engagement hardware through short strokes.','在受控扭矩卸载窗口内快速选择目标挡位并确认接合。','They select the target ratio quickly during a controlled torque-cut window and confirm engagement.','作动时序需协调点火、MGU-K和离合；未完全接合会冲击狗齿并产生跳挡。','Actuation timing coordinates ignition, MGU-K and clutch; incomplete engagement impacts dogs and can jump out of gear.','它像极快的机械选档手，只有在动力暂时松开的几毫秒内才能把下一挡推到位。','It is a very fast mechanical selector working in a millisecond torque-release window.'),
    d('主减速齿轮位于变速箱输出与差速器之间，通常以固定比完成最后一级减速。','The final drive lies between gearbox output and differential and provides the last fixed reduction.','把所有挡位共同缩放到轮端范围，并改变半轴所见扭矩。','It scales every gear to the wheel-speed range and sets torque delivered to halfshafts.','更大减速提高轮上扭矩但降低同转速车速；齿轮啮合还需覆盖最高持续功率和冲击载荷。','More reduction raises wheel torque but lowers speed at a given rpm; mesh capacity must cover sustained power and shocks.','它像变速箱后的总倍率旋钮，一次设定会同时改变所有挡位的长短。','It is the global ratio knob after the gearbox, lengthening or shortening every gear.'),
    d('可控差速器位于后轴中心，左右输出分别连接两根半轴。','The controlled differential sits on the rear centreline with separate outputs to left and right halfshafts.','允许转弯时左右轮速不同，并按状态管理两轮扭矩分配与锁止程度。','It permits cornering speed difference and manages left-right torque and locking state.','差速运动学满足平均转速关系；摩擦或控制锁止产生附加扭矩与偏航影响，不能等同固定轴。','Differential kinematics preserve average-speed relation; friction or controlled locking adds torque and yaw effects without becoming a solid axle.','它像允许两条跑道速度不同的交通协调器，抓地不足时又会限制一侧空转。','It is a traffic coordinator allowing two wheel speeds while limiting wasteful one-wheel spin.'),
    d('左右半轴从差速器穿过后悬架空间连接轮毂，等速节允许轮跳和角度变化。','Left and right halfshafts cross rear-suspension space from differential to hubs, with CV joints accommodating travel and angle.','把差速器输出扭矩传到车轮，同时允许悬架完整运动。','They transmit differential torque to the wheels while allowing full suspension articulation.','轴的扭转刚度影响扭矩建立，万向节角度影响效率、温度和周期载荷。','Shaft torsional stiffness affects torque build-up; joint angle affects efficiency, heat and cyclic load.','它们是会随悬架摆动的旋转传动杆，既要弯路线，也不能把扭矩丢掉。','They are rotating drive links that articulate with suspension without losing torque.'),
    d('壳体包围齿轮和差速器并承接悬架硬点，轴承与润滑通道沿各轴系布置。','The casing encloses gears and differential and carries suspension hardpoints; bearings and oil passages follow each shaft.','保持齿轮对中、把悬架载荷送入车体，并用油膜排热和防磨损。','It preserves gear alignment, carries suspension load and uses oil film for heat removal and wear control.','壳体挠度改变齿面接触；轴承预载、油温、曝气和喷油位置共同决定寿命与效率。','Casing deflection changes tooth contact; bearing preload, oil temperature, aeration and jet placement set life and efficiency.','它既是变速箱外壳又是后悬架骨架，里面的油同时负责润滑、冷却和带走磨屑。','It is both gearbox shell and rear suspension skeleton, with oil lubricating, cooling and carrying debris.'),
  ],
  cooling: [
    d('高温冷却回路环绕气缸盖和缸体，并通往侧箱内对应散热器。','The high-temperature coolant loop passes through cylinder heads and block to its sidepod radiator.','带走燃烧系统余热并保持材料、燃烧和润滑处于可控温度。','It removes combustion heat and keeps materials, combustion and lubrication within temperature bounds.','热流由质量流量、比热和温升决定；局部沸腾、气穴和泵入口裕量限制流量提升。','Heat flow follows mass flow, heat capacity and temperature rise; local boiling, cavitation and inlet margin limit flow increases.','它是发动机的主水循环，把最热区域的热搬到侧箱散热器。','It is the engine’s main water circuit, moving heat from the hottest zones to sidepod radiators.'),
    d('机油与变速箱油回路分别连接轴承、齿轮、活塞冷却和专用换热器。','Engine- and gearbox-oil circuits feed bearings, gears, piston cooling and dedicated heat exchangers.','同时润滑、清洁和冷却高负荷摩擦副，并维持液压可用黏度。','They lubricate, clean and cool loaded interfaces while maintaining usable viscosity.','油温过低增加泵损和阻力，过高降低油膜并加速氧化；压力不等于所有支路都有流量。','Cold oil raises pumping loss, hot oil thins films and oxidizes; pressure alone does not prove branch flow.','它不是只让零件“滑”，还像移动的冷却液，把轴承和齿轮里的热带走。','It does more than lubricate; it is a moving coolant extracting heat from bearings and gears.'),
    d('增压空气从压气机经中冷换热路径进入进气歧管，布置在侧箱或动力单元邻近区域。','Charge air travels from compressor through an intercooling path to the plenum near sidepods or power unit.','降低压缩后进气温度、提高密度并扩大爆震裕量。','It reduces post-compressor temperature, raises density and improves knock margin.','换热降低温度却引入压降和容积；尺寸选择需要在密度、迟滞、阻力和封装间平衡。','Cooling lowers temperature but adds pressure drop and volume; sizing balances density, lag, drag and packaging.','它像涡轮后的空气冰箱，凉空气更密，但冰箱过大也会让响应变慢。','It is the turbo’s air refrigerator: cooler charge is denser, but excess volume slows response.'),
    d('电池和功率电子低温回路连接能量存储、逆变器及相关换热器，与发动机高温回路隔离。','A low-temperature loop links energy store, inverter and dedicated exchangers separately from the hot engine circuit.','保持电芯和半导体结温在较低窗口，并控制部件间温差。','It holds cells and semiconductor junctions in lower temperature windows and limits gradients.','同一冷却液入口温度对不同部件并不等效；热阻和瞬态热容量决定结温与电芯核心温度。','The same coolant inlet is not the same component temperature; thermal resistance and capacitance set junction and cell-core values.','它像电子系统的独立冷水机，不能直接接到更热的发动机水路上。','It is a separate chiller for electronics, not simply an extension of the hotter engine circuit.'),
    d('侧箱换热器、进气口和导流通道位于驾驶员两侧，出口与百叶共同连接外部气流。','Sidepod heat exchangers, inlets and ducts sit beside the driver and discharge through outlets and louvres.','以尽可能小的外部阻力和气动扰动获得所需空气质量流与换热面积。','They obtain required air mass flow and exchange area with minimal external drag and aero disturbance.','换热量受空气与液体侧热阻共同限制；开口增大有助冷却，却会增加阻力并改变尾部流场。','Heat is limited by air- and liquid-side resistance; larger openings aid cooling but add drag and alter rear flow.','它像赛车两侧的散热肺，开得越大越凉，但也越破坏空气动力效率。','They are the car’s cooling lungs: larger openings breathe more but cost aero efficiency.'),
    d('泵和膨胀罐位于各流体回路高可维护区域，百叶在车身出口，传感器覆盖压力与温度关键点。','Pumps and expansion tanks occupy serviceable circuit locations; louvres form body exits and sensors cover key pressures and temperatures.','维持循环、排气和容积补偿，并按赛道与环境配置出口面积。','They maintain circulation, deaeration and expansion volume and tune outlet area for circuit and ambient conditions.','泵工作点由系统阻力曲线决定；压力、温度和流量组合才能区分堵塞、气蚀、泄漏与换热不足。','Pump operating point follows the system curve; combined pressure, temperature and flow distinguish blockage, cavitation, leak and poor exchange.','它们是冷却系统的心脏、气泡分离器和可调散热窗，三者共同决定回路是否稳定。','They are cooling-system heart, bubble separator and adjustable heat window, jointly stabilizing the circuit.'),
  ],
  ecu: [
    d('标准电子控制单元安装在受保护、低振动且可散热的位置，并连接规定车辆网络。','The standard ECU is mounted in a protected, cooled, low-vibration location on the mandated vehicle networks.','以统一硬件执行关键控制、记录和监督功能，建立可审计接口。','It executes critical control, logging and supervision on common hardware with auditable interfaces.','实时任务必须满足确定性周期、输入时间戳和看门狗；算力平均值不能代替最坏执行时间。','Real-time tasks require deterministic periods, timestamps and watchdogs; average CPU load does not replace worst-case timing.','它像全车共用的实时指挥中心，每条命令必须准时、可记录、可复现。','It is the car’s real-time command centre, where every instruction must be timely, recorded and reproducible.'),
    d('动力单元控制和扭矩仲裁运行在控制器的软件层，连接发动机、MGU-K、逆变器和车手请求。','Power-unit control and torque arbitration run in software across engine, MGU-K, inverter and driver demand interfaces.','在多个动力源及安全限制之间分配最终可交付扭矩。','They allocate deliverable torque among power sources and safety constraints.','最终命令通常取请求、附着、热、电压和故障边界的交集，并限制变化率以保护传动和稳定性。','Final command intersects demand with grip, thermal, voltage and fault bounds and applies slew limits for driveline stability.','它像同时指挥燃油发动机和电机的总调度员，承诺多少扭矩就必须准确交付多少。','It is the dispatcher coordinating engine and motor so promised torque matches delivered torque.'),
    d('能量管理与SOC目标贯穿整圈策略层，并与制动回收和加速释放控制相连。','Energy management and SOC targets span the lap strategy layer and connect braking recovery to acceleration deployment.','在有限可用能量与功率边界下，把电能放到最能改善圈速的位置。','They place limited electrical energy where it improves lap time most within power and energy bounds.','每段净能量由功率对时间积分；局部最强助推可能导致后程SOC不足，因此需要整圈优化。','Segment energy is the time integral of power; local maximum boost can starve later sections, requiring lap-level optimization.','它像整圈的能量预算员，不是见到直道就把电花光，而是决定哪一米最值得用。','It is the lap’s energy budgeter, spending electricity on the metres where it matters most.'),
    d('线控制动和换挡协调逻辑位于高优先级任务中，并跨接制动、MGU-K、发动机与变速箱。','Brake-by-wire and shift coordination occupy high-priority tasks spanning brakes, MGU-K, engine and gearbox.','在回收变化和换挡扭矩中断期间维持车手期望的减速度与纵向稳定。','They preserve requested deceleration and longitudinal stability through regen changes and shift torque interruptions.','不同执行器延迟必须补偿；状态机、确认信号和超时处理比单一连续公式更关键。','Different actuator delays require compensation; state machines, confirmations and timeouts matter more than one continuous formula.','它像几名演奏者的指挥，让液压刹车、电机和换挡在毫秒级换手时不出现空拍。','It is the conductor coordinating hydraulic brake, motor and shift handovers without a missed beat.'),
    d('车载网络连接控制器、传感器和记录器，共用同步时钟并将数据写入持久存储。','Vehicle networks link controllers, sensors and loggers around a synchronized clock and persistent storage.','可靠传输命令与测量，并让不同系统数据能按同一时间轴重建。','They transmit commands and measurements reliably and reconstruct all systems on a common timeline.','总线负载、优先级和丢包影响延迟；没有同步时间戳，相关性不代表真实因果顺序。','Bus load, priority and loss affect latency; without synchronized timestamps, correlation cannot establish sequence.','它像全车的神经网络和统一时钟，让每个传感器的故事能拼成同一圈比赛。','It is the car’s nervous network and common clock, aligning every sensor story into one lap.'),
    d('安全监控跨越踏板、扭矩、高压、制动和通信通道，故障降级输出到各执行器与车手界面。','Safety monitors span pedal, torque, HV, braking and communication channels, with degradation outputs to actuators and driver interface.','发现不合理状态、隔离故障并转入仍可控或安全停机的模式。','They detect implausible states, isolate faults and transition to controllable or safe shutdown modes.','诊断覆盖率依赖独立证据、故障注入与失效时间；同源软件重复两遍不等于真正冗余。','Diagnostic coverage needs independent evidence, fault injection and fault-tolerant timing; duplicated common software is not true redundancy.','它是控制系统的安全裁判，发现信号“讲不通”时会限制性能，而不是继续赌。','It is the control system’s safety referee, reducing performance when signals no longer make sense.'),
  ],
  sensors: [
    d('惯性测量单元靠近车辆参考点刚性安装，车辆速度来自融合的轮速、惯性与其他许可来源。','The IMU is rigidly mounted near the vehicle reference point; speed is fused from wheel, inertial and other permitted sources.','测量加速度和角速度，重建车身运动、偏航与赛道速度状态。','It measures acceleration and angular rate to reconstruct body motion, yaw and vehicle speed.','安装角和杆臂会把旋转混入线加速度；偏置积分导致漂移，因此需要坐标变换与融合校正。','Mounting angle and lever arm mix rotation into acceleration; integrated bias drifts, requiring transforms and fusion.','它像赛车的内耳，知道车在加速、侧倾还是旋转，但必须先清楚自己装在哪里。','It is the car’s inner ear, sensing acceleration and rotation only after its own pose is known.'),
    d('轮速传感器位于四个轮端，制动压力和温度、轮胎压力与表面温度分布在对应系统。','Wheel-speed sensors sit at all corners; brake pressure/temperature and tyre pressure/surface temperature cover their systems.','量化滑移、锁止、制动状态和轮胎工作窗口。','They quantify slip, lock tendency, braking state and tyre operating window.','轮速不等于车速，尤其在制动和加速时；温压数据还需时间对齐和环境补偿。','Wheel speed is not vehicle speed under braking or drive; thermal and pressure data need timing and ambient compensation.','它们像四只脚上的速度表和体温计，比较起来才知道哪只轮正在滑或过热。','They are speedometers and thermometers at each foot; comparison reveals slip and overheating.'),
    d('悬架位移传感器连接摇臂或阻尼器，应变片贴在校准结构，载荷代理来自压力或挠度。','Suspension displacement sensors attach to rockers or dampers; strain gauges bond to calibrated structures and load proxies use pressure or deflection.','估计车高、侧倾、轮胎载荷变化和结构受力，用于气动与底盘关联。','They estimate ride height, roll, tyre-load variation and structural load for aero-chassis correlation.','代理量必须用试验标定并考虑温漂、安装比和交叉载荷；它不是直接测得的轮胎力。','Proxies require test calibration for drift, motion ratio and cross-load; they are not direct tyre-force measurements.','它们像通过弹簧压缩和结构微弯来称重的间接秤，需要先建立可靠换算表。','They are indirect scales reading spring motion and tiny strain, dependent on a trusted calibration.'),
    d('动力单元、电气和热传感器分布在燃烧、轴系、高压母线及所有流体入口和出口。','Power-unit, electrical and thermal sensors span combustion, shafts, HV bus and all fluid inlets and outlets.','计算功率与效率，保护温度、压力、电压和电流边界，并定位损失来源。','They calculate power and efficiency, protect thermal/pressure/voltage/current limits and locate losses.','功率需要同步的电压电流或转矩转速；入口出口温差只有结合流量才能代表热量。','Power needs synchronized voltage-current or torque-speed; inlet-outlet temperature difference needs flow to represent heat.','它们把看不见的能量流画出来：电从哪里来、机械功到哪里去、热又在哪里积累。','They map invisible energy flow: electrical input, mechanical output and heat accumulation.'),
    d('遥测链路把选定实时数据发往车队，车载记录器保存更高带宽通道，所有源使用同步时间。','Telemetry sends selected live data to the team while onboard logging stores higher-bandwidth channels on synchronized time.','支持实时安全判断、性能分析和赛后完整重放。','They support live safety decisions, performance analysis and complete post-run replay.','无线带宽有限，需要分级和降采样；记录丢包、时钟漂移与版本元数据必须可见。','Radio bandwidth requires prioritization and downsampling; packet loss, clock drift and version metadata must remain visible.','遥测像直播，记录器像原片；一个让工程师当下判断，一个保留事后逐帧分析。','Telemetry is the live broadcast, logging the master recording: one aids now, the other supports frame-by-frame review.'),
    d('事故、车手安全与规则通道连接事故记录器、生理或救援接口以及规定监督信号。','Accident, driver-safety and regulatory channels connect event recorders, rescue interfaces and mandated supervision signals.','在重大事件中保存可信证据、支持救援并证明关键系统遵守规定状态。','They preserve trusted evidence, support rescue and demonstrate regulated system states during major events.','通道需独立供电、抗撞击、带明确触发前后窗口并防止普通软件覆盖关键记录。','Channels need independent power, crash resistance, defined pre/post-trigger windows and protection from ordinary software overwrite.','它像航空器的黑匣子和紧急联络线，平时安静，事故时必须留下完整而可信的事实。','It is the car’s black box and emergency line, quiet normally but authoritative during an accident.'),
  ],
}

export function grandPrixWorkshopFacts(partId: PartId, lesson: EngineeringLesson): SubassemblyFact[] {
  const details = DETAILS[partId]
  if (details.length !== lesson.subcomponents.length) {
    throw new Error(`Grand Prix workshop facts mismatch for ${partId}: ${details.length}/${lesson.subcomponents.length}`)
  }
  return details.map((item) => ({ ...item }))
}
