import type { LocalText } from './engineeringData'
import type { PartId } from './data'

export type QuestionType = 'concept' | 'calculation' | 'scenario' | 'diagnosis' | 'design'
export type AnswerIndex = 0 | 1 | 2
type LocalOption = [zh: string, en: string]
type QuestionOptions = [LocalOption, LocalOption, LocalOption]
export type KnowledgeQuestion = {
  id: string
  type: QuestionType
  difficulty: 1 | 2 | 3
  prompt: LocalText
  options: [LocalText, LocalText, LocalText]
  answer: AnswerIndex
  explanation: LocalText
  hint?: LocalText
}

const l = (zh: string, en: string): LocalText => ({ zh, en })
const q = (id: string, type: QuestionType, difficulty: 1 | 2 | 3, zh: string, en: string, options: QuestionOptions, answer: AnswerIndex, explainZh: string, explainEn: string, hintZh?: string, hintEn?: string): KnowledgeQuestion => ({ id, type, difficulty, prompt: l(zh, en), options: options.map(([a, b]) => l(a, b)) as [LocalText, LocalText, LocalText], answer, explanation: l(explainZh, explainEn), hint: hintZh && hintEn ? l(hintZh, hintEn) : undefined })

export const QUESTION_BANK: Record<PartId, [KnowledgeQuestion, KnowledgeQuestion, KnowledgeQuestion, KnowledgeQuestion, KnowledgeQuestion]> = {
  'front-wing': [
    q('fw-c', 'concept', 1, '前翼最核心的整车作用是什么？', 'What is the front wing’s primary vehicle-level role?', [['只降低前轮温度', 'Only cool the front tyres'], ['产生前轴下压力并组织下游气流', 'Create front downforce and condition downstream flow'], ['承担前悬架全部载荷', 'Carry all front-suspension loads']], 1, '前翼既决定前轴高速抓地，也会改变前轮尾流和底板入口条件。', 'The front wing sets front-axle high-speed grip and changes front-wheel wake and floor-inlet conditions.'),
    q('fw-n', 'calculation', 2, '同一前翼在 60 km/h 产生 300 N 下压力；气动系数不变时，120 km/h 约产生多少下压力？', 'The same wing makes 300 N at 60 km/h. With unchanged coefficients, what is expected at 120 km/h?', [['600 N', '600 N'], ['900 N', '900 N'], ['1200 N', '1200 N']], 2, '气动力与速度平方成正比，速度翻倍时载荷约变为四倍。', 'Aerodynamic force scales with speed squared, so doubling speed gives roughly four times the load.', '使用 F ∝ V²。', 'Use F ∝ V².'),
    q('fw-s', 'scenario', 2, '车手只在高速弯抱怨转向不足，低速机械平衡正常，最先应检查什么？', 'The driver reports understeer only in fast corners while low-speed mechanical balance is normal. What should be checked first?', [['前翼/底板的高速气动平衡与车高', 'High-speed aero balance and ride height'], ['方向盘外观', 'Steering-wheel appearance'], ['低压电池颜色', 'Low-voltage battery colour']], 0, '只随速度显著出现的问题首先指向气动载荷与平台，而不是静态机械外观。', 'A problem that grows strongly with speed points first to aero load and platform, not static appearance.'),
    q('fw-d', 'diagnosis', 3, '重刹时车辆总向右偏，检查发现左前翼端板有损伤。最合理的诊断路径是？', 'The car consistently yaws right under heavy braking and the left front-wing endplate is damaged. What is the best diagnostic path?', [['直接加右侧胎压抵消', 'Add right-side tyre pressure to compensate'], ['测量左右气动载荷、翼面几何与悬架/制动对称性', 'Measure side-to-side aero load, wing geometry, suspension and brake symmetry'], ['忽略，因为前翼只影响直线阻力', 'Ignore it because the wing only changes straight-line drag']], 1, '损伤可能造成左右下压力和流场不对称，但仍要排除制动与悬架因素，不能用另一项不对称掩盖。', 'Damage can create asymmetric load and flow, but braking and suspension must also be excluded rather than masked with another asymmetry.'),
    q('fw-e', 'design', 3, '设计前翼调节范围时，哪组约束最完整？', 'Which constraint set is most complete when defining front-wing adjustment range?', [['峰值下压力', 'Peak downforce only'], ['下压力、阻力、失速、结构刚度、规则和全车气动平衡', 'Downforce, drag, stall, stiffness, rules and whole-car aero balance'], ['只看翼片能否装上', 'Only whether the flap fits']], 1, '赛车部件的最佳点来自多目标约束，单个峰值不能保证稳定、合法或可制造。', 'A race component optimum is multi-objective; one peak does not ensure stability, legality or manufacturability.'),
  ],
  'rear-wing': [
    q('rw-c', 'concept', 1, '增大尾翼攻角通常同时带来什么？', 'What normally comes with increasing rear-wing angle?', [['后下压力与阻力都增加，接近失速后收益下降', 'Rear downforce and drag rise, with diminishing return near stall'], ['阻力下降且下压力不变', 'Drag falls while downforce stays constant'], ['只改变前轴抓地', 'Only front-axle grip changes']], 0, '攻角提高压差和载荷，也增大阻力与分离风险。', 'More angle raises pressure difference and load, as well as drag and separation risk.'),
    q('rw-n', 'calculation', 2, '尾翼下压力 900 N、阻力 150 N，其升阻比是多少？', 'A rear wing produces 900 N downforce and 150 N drag. What is its lift-to-drag ratio?', [['3', '3'], ['6', '6'], ['9', '9']], 1, '升阻比按下压力除以阻力计算：900/150=6。', 'Lift-to-drag is downforce divided by drag: 900/150=6.', 'L/D = |L|/D。', 'L/D = |L|/D.'),
    q('rw-s', 'scenario', 2, '耐久赛直道速度不足但高速弯后轴仍有较大抓地余量，合理尝试是？', 'Straight speed is poor in endurance while rear grip still has margin in fast corners. What is a sensible trial?', [['小幅减小尾翼并检查全车平衡和圈速', 'Reduce rear-wing level slightly and check whole-car balance and lap time'], ['拆除尾翼', 'Remove the rear wing'], ['增加制动盘厚度', 'Increase brake-disc thickness']], 0, '应通过可控的小步 A/B 测试交换阻力与后轴余量，同时观察前后平衡。', 'Use a controlled A/B step to trade drag against rear margin while monitoring front/rear balance.'),
    q('rw-d', 'diagnosis', 3, '高速弯后轴抓地逐圈下降，尾翼角度标记发生位移。最优先处理是？', 'Rear grip falls lap by lap in fast corners and the wing-angle witness mark has moved. What is the priority?', [['继续跑并让车手适应', 'Continue and ask the driver to adapt'], ['立即停驶，检查紧固、支座、裂纹和角度保持', 'Stop and inspect retention, mounts, cracks and angle holding'], ['把差速器锁得更紧', 'Add differential locking']], 1, '气动件的机械位移会导致不可预测载荷，属于需要立即停驶的结构/紧固风险。', 'Mechanical movement of an aero element causes unpredictable load and is an immediate stop-and-inspect risk.'),
    q('rw-e', 'design', 3, '尾翼支座设计最容易被忽略、却必须验证的载荷是什么？', 'Which often-overlooked load must rear-wing mounts be validated for?', [['只有静态自重', 'Static self-weight only'], ['气动弯矩、振动、路肩冲击和左右不对称组合', 'Combined aero moment, vibration, kerb impact and side asymmetry'], ['驾驶员踏板力', 'Driver pedal force']], 1, '支座承受的是动态、多方向组合载荷，不能只按平均下压力或自重设计。', 'Mounts see dynamic multidirectional combined loads, not just average downforce or self-weight.'),
  ],
  floor: [
    q('fl-c', 'concept', 1, '底板为什么对车高特别敏感？', 'Why is the floor especially sensitive to ride height?', [['地面构成流道边界并影响加速、密封和分离', 'The ground forms a flow boundary affecting acceleration, sealing and separation'], ['因为底板只靠弹簧工作', 'Because the floor works only through springs'], ['因为车高改变电池电压', 'Because ride height changes battery voltage']], 0, '地面与底板之间的通道尺寸直接决定压力分布，过低还可能堵塞和失速。', 'The passage between floor and ground directly sets pressure; too low can choke and stall it.'),
    q('fl-n', 'calculation', 2, '底板在 100 km/h 产生 1000 N 下压力；系数不变时 150 km/h 约是多少？', 'The floor makes 1000 N at 100 km/h. With unchanged coefficients, what is expected at 150 km/h?', [['1500 N', '1500 N'], ['2000 N', '2000 N'], ['2250 N', '2250 N']], 2, '载荷按速度平方变化：(150/100)²=2.25。', 'Load scales with speed squared: (150/100)²=2.25.', '比较速度比的平方。', 'Square the speed ratio.'),
    q('fl-s', 'scenario', 2, '提高车速时下压力先增加、随后突然下降并反复弹跳，最可能是什么？', 'Downforce rises with speed, then suddenly drops with repeated bouncing. What is most likely?', [['底板过低失速并与悬架形成平台振荡', 'Floor stall at too-low ride height coupled to suspension oscillation'], ['方向盘直径过大', 'Steering wheel too large'], ['CAN 终端电阻偏小', 'CAN termination too low']], 0, '速度提高增加下压力并压低车身，越过底板车高窗口后失速，载荷释放再抬高车身，可能形成循环。', 'Speed adds load and compresses the car; crossing the floor-height window stalls flow, releases load and can form a cycle.'),
    q('fl-d', 'diagnosis', 3, '底板压力传感数据异常，但只有一个通道出现尖峰。第一步应做什么？', 'Floor pressure data is abnormal, but only one channel spikes. What is the first step?', [['立刻修改底板几何', 'Immediately change floor geometry'], ['验证通道、导压管、同步与邻近传感器一致性', 'Verify channel, pressure line, timing and neighbouring-sensor consistency'], ['降低所有胎压', 'Lower all tyre pressures']], 1, '孤立通道异常首先需要验证测量链，避免用错误数据驱动结构修改。', 'An isolated channel anomaly requires measurement-chain validation before changing hardware.'),
    q('fl-e', 'design', 3, '底板优化目标应该怎样定义？', 'How should a floor optimisation objective be defined?', [['单一静态车高的最大下压力', 'Maximum downforce at one static ride height'], ['完整俯仰、侧倾、车高和偏航包络内的稳定载荷与效率', 'Stable load and efficiency over the heave, pitch, roll and yaw envelope'], ['最大扩散器角度', 'Maximum diffuser angle']], 1, '真实赛车持续改变姿态，稳健的工作窗口比一个孤立峰值更有价值。', 'A real car continually changes attitude, so a robust operating window is more valuable than an isolated peak.'),
  ],
  nose: [
    q('no-c', 'concept', 1, '鼻锥的结构任务是什么？', 'What is the nose’s structural duty?', [['仅支撑涂装', 'Support paint only'], ['支撑前翼并通过渐进压溃吸收正面碰撞能量', 'Support the front wing and absorb frontal impact through progressive crush'], ['储存制动液', 'Store brake fluid']], 1, '鼻锥同时位于前翼载荷路径和正面碰撞能量路径中。', 'The nose belongs to both the front-wing load path and the frontal-impact energy path.'),
    q('no-n', 'calculation', 2, '300 kg 等效质量以 7 m/s 碰撞，需要吸收多少动能？', 'How much kinetic energy must be absorbed by an equivalent 300 kg mass at 7 m/s?', [['3.7 kJ', '3.7 kJ'], ['7.35 kJ', '7.35 kJ'], ['14.7 kJ', '14.7 kJ']], 1, 'E=½mv²=0.5×300×49=7350 J。', 'E=½mv²=0.5×300×49=7350 J.', 'E = ½mv²。', 'E = ½mv².'),
    q('no-s', 'scenario', 2, '吸能测试总能量合格，但最初 20 mm 出现很高峰值，应该如何改进？', 'Total absorbed energy passes, but the first 20 mm has a very high force peak. What should be improved?', [['优化触发槽和首层压溃几何', 'Optimise triggers and first-stage crush geometry'], ['只加重车辆', 'Only add vehicle mass'], ['把传感器滤波调到极强', 'Apply extremely strong sensor filtering']], 0, '初始峰值通常与触发和局部刚度突变有关，不能用滤波掩盖真实载荷。', 'The initial peak normally comes from triggers and local stiffness discontinuity and must not be hidden with filtering.'),
    q('no-d', 'diagnosis', 3, '轻微碰撞后鼻锥表面无裂纹，但前翼位置发生变化，正确做法是？', 'After a minor impact the nose shows no surface crack, but front-wing position changed. What is correct?', [['目视正常即可继续', 'Continue because it looks normal'], ['拆检连接、测量几何并按复材 NDT/结构标准判定', 'Inspect joints, measure geometry and assess with composite NDT/structural criteria'], ['用前翼调角抵消', 'Compensate with wing angle']], 1, '复合材料可能存在不可见分层或连接损伤，几何变化本身就是需要深入检查的证据。', 'Composites can hide delamination or joint damage; changed geometry itself is evidence requiring deeper inspection.'),
    q('no-e', 'design', 3, '鼻锥压溃结构为什么不能只追求最低质量？', 'Why can a nose crush structure not target minimum mass alone?', [['还要满足能量、峰值力、稳定模式、安装和规则', 'It must also meet energy, peak force, stable mode, mounting and rules'], ['因为颜色会变浅', 'Because colour becomes lighter'], ['因为质量不影响赛车', 'Because mass does not affect a race car']], 0, '低质量若带来不稳定折叠、过高峰值或无法安装，就不是有效工程方案。', 'Low mass is not a valid solution if folding is unstable, peak force excessive or mounting impractical.'),
  ],
  monocoque: [
    q('mo-c', 'concept', 1, '提高单体壳扭转刚度的主要车辆收益是什么？', 'What is the main vehicle benefit of increasing monocoque torsional stiffness?', [['让悬架调校更可预测', 'Make suspension tuning more predictable'], ['自动提高电池电量', 'Automatically raise battery energy'], ['消除所有轮胎非线性', 'Remove all tyre nonlinearity']], 0, '车架不再主导轮端柔度时，弹簧和防倾杆调整更接近模型预期。', 'When chassis compliance no longer dominates wheel response, spring and bar changes follow the model more closely.'),
    q('mo-n', 'calculation', 2, '车架受 1200 N·m 扭矩时扭转 0.4°，扭转刚度是多少？', 'A chassis twists 0.4° under 1200 N·m. What is its torsional stiffness?', [['480 N·m/°', '480 N·m/°'], ['3000 N·m/°', '3000 N·m/°'], ['4800 N·m/°', '4800 N·m/°']], 1, 'K=T/θ=1200/0.4=3000 N·m/°。', 'K=T/θ=1200/0.4=3000 N·m/°.', 'K = T/θ。', 'K = T/θ.'),
    q('mo-s', 'scenario', 2, '两个车架质量相同，一个极高刚度但硬点局部柔软，另一个全局略低但硬点稳定。哪个更可能调校一致？', 'Two chassis have equal mass: one has very high global stiffness but soft hardpoints, the other slightly lower global stiffness with stable hardpoints. Which is more likely to tune consistently?', [['前者，因为只看全局数字', 'The first because only the global number matters'], ['后者，因为真实载荷路径和局部刚度同样关键', 'The second because real load paths and local stiffness also matter'], ['完全相同', 'They are identical']], 1, '悬架力通过硬点进入车架，局部柔度会直接改变定位和轮端响应。', 'Suspension forces enter through hardpoints, so local compliance directly changes alignment and wheel response.'),
    q('mo-d', 'diagnosis', 3, '事故后车架外观正常，但扭转台架斜率下降且滞回增大，最可能说明什么？', 'After an incident the chassis looks normal, but torsion slope drops and hysteresis grows. What does this suggest?', [['隐藏分层、芯材脱粘或连接损伤', 'Hidden delamination, core disbond or joint damage'], ['空气密度上升', 'Higher air density'], ['轮胎花纹变深', 'Deeper tyre tread']], 0, '刚度损失与滞回是复材内部或连接损伤的典型系统级信号，需要 NDT 定位。', 'Stiffness loss and hysteresis are system-level signs of internal composite or joint damage and require NDT.'),
    q('mo-e', 'design', 3, '复合材料单体壳铺层为什么必须依据载荷方向？', 'Why must composite monocoque layup follow load direction?', [['复材各向异性，纤维方向决定强度和刚度', 'Composites are anisotropic; fibre direction sets strength and stiffness'], ['所有方向性能完全相同', 'Performance is identical in every direction'], ['只为了外观纹理', 'Only for visual texture']], 0, '0/±45/90° 层分别承担不同的轴向、剪切和横向需求，铺层顺序也影响失效。', '0/±45/90° plies serve different axial, shear and transverse needs, and stacking order affects failure.'),
  ],
  halo: [
    q('ha-c', 'concept', 1, '本项目中“座舱防护”学习模块的正确范围是什么？', 'What is the correct scope of the “Halo/cockpit protection” module in this project?', [['只学习 F1 钛合金头部保护环', 'Only the F1 titanium Halo'], ['以大学生方程式防滚架、支撑、头枕、安全带和生存空间为主，F1 头部保护环作对比', 'Primarily Formula Student roll hoops, bracing, head restraint, harness and survival space, with Halo as comparison'], ['只学习座椅颜色', 'Only seat colour']], 1, '不同赛事规则必须隔离；大学生方程式的核心是完整驾驶舱防护与约束系统。', 'Rule sets must remain distinct; Formula Student focuses on the complete cockpit protection and restraint system.'),
    q('ha-n', 'calculation', 2, '一根有效承载面积 300 mm² 的杆件承受 60 kN 轴向力，名义应力是多少？', 'A member with 300 mm² effective area carries 60 kN axial load. What is nominal stress?', [['20 MPa', '20 MPa'], ['200 MPa', '200 MPa'], ['2000 MPa', '2000 MPa']], 1, 'σ=F/A=60000/300=200 N/mm²=200 MPa。', 'σ=F/A=60000/300=200 N/mm²=200 MPa.', '1 N/mm² = 1 MPa。', '1 N/mm² = 1 MPa.'),
    q('ha-s', 'scenario', 2, '结构计算通过，但高个驾驶员头盔接近防护包络边界。能否要求驾驶员长期低头解决？', 'Structure calculations pass, but a tall driver’s helmet approaches the protection envelope. Can the driver simply remain hunched?', [['可以，强度合格就行', 'Yes, strength is all that matters'], ['不可以，应重新调整座椅、头枕和结构并复测逃生', 'No; revise seat, restraint and structure and repeat egress checks'], ['只需减少胎压', 'Only reduce tyre pressure']], 1, '防护必须覆盖正常可持续驾驶姿态并满足逃生，不能把几何缺陷转移给驾驶员。', 'Protection must cover a sustainable normal posture and egress; geometry defects cannot be shifted to the driver.'),
    q('ha-d', 'diagnosis', 3, '防滚架支撑焊趾出现裂纹，正确措施是什么？', 'A crack appears at a roll-hoop brace weld toe. What is the correct action?', [['打磨表面继续使用', 'Polish the surface and continue'], ['停驶、NDT、查载荷路径与焊接工艺，再按批准方案修复验证', 'Stop, perform NDT, investigate load path and welding process, then repair and validate'], ['加大电机转矩', 'Increase motor torque']], 1, '安全结构裂纹必须追溯局部弯矩、刚度突变和工艺根因，覆盖表面不能恢复可信承载。', 'A safety-structure crack requires root-cause work on local moment, stiffness discontinuity and process; covering the surface does not restore capacity.'),
    q('ha-e', 'design', 3, '防护结构设计中哪项组合最完整？', 'Which set is most complete for cockpit protection design?', [['强度、刚度、生存空间、视野、逃生、人机和连接边界', 'Strength, stiffness, survival space, visibility, egress, ergonomics and mounting boundaries'], ['仅材料屈服强度', 'Material yield strength only'], ['仅外观对称', 'Visual symmetry only']], 0, '保护系统的成功标准包含事故载荷下的空间、约束和逃生，而不是单根杆件应力。', 'Protection success includes space, restraint and egress under accident loads, not one member stress.'),
  ],
  tires: [
    q('ty-c', 'concept', 1, '轮胎“载荷敏感性”是什么意思？', 'What does tyre load sensitivity mean?', [['法向载荷翻倍时可用力通常少于翻倍', 'When normal load doubles, available force normally rises by less than double'], ['载荷不影响抓地', 'Load does not affect grip'], ['只有静止轮胎有抓地', 'Only a stationary tyre has grip']], 0, '有效摩擦系数常随载荷增加而下降，因此载荷转移会降低整轴总能力。', 'Effective friction coefficient often falls as load rises, so load transfer reduces total axle capability.'),
    q('ty-n', 'calculation', 2, '轮胎滚动圆周速度 22 m/s，轮心速度 20 m/s，按 κ=(Rω−Vx)/Vx，滑移率是多少？', 'Tyre circumferential speed is 22 m/s and wheel-centre speed is 20 m/s. Using κ=(Rω−Vx)/Vx, what is slip?', [['5%', '5%'], ['10%', '10%'], ['20%', '20%']], 1, 'κ=(22−20)/20=0.10，即 10%。', 'κ=(22−20)/20=0.10, or 10%.', '先求速度差再除以轮心速度。', 'Divide speed difference by wheel-centre speed.'),
    q('ty-s', 'scenario', 2, '外侧胎肩持续比内侧高 18°C，且高速弯推头，优先考虑什么？', 'The outside shoulder remains 18°C hotter than the inside and the car understeers in fast corners. What should be considered first?', [['动态外倾、侧倾和热态压力是否让外肩过载', 'Whether dynamic camber, roll and hot pressure overload the outside shoulder'], ['增加车载音量', 'Increase audio volume'], ['关闭全部数据记录', 'Disable all logging']], 0, '温度分布与弯道症状共同指向接地姿态和载荷分配，但需核对测量时刻。', 'Temperature distribution and corner symptom point to contact attitude and load distribution, with measurement timing verified.'),
    q('ty-d', 'diagnosis', 3, '临界制动时单轮轮速快速振荡，如何区分轮跳与信号噪声？', 'One wheel-speed channel oscillates under threshold braking. How do you separate wheel hop from signal noise?', [['只看该轮速曲线', 'Look only at that wheel-speed trace'], ['同步比较阻尼器、IMU、制动压力和其他轮速，并检查传感器频谱', 'Synchronise damper, IMU, brake pressure and other wheel speeds and inspect sensor spectrum'], ['直接更换所有轮胎', 'Replace all tyres immediately']], 1, '真实轮跳会在结构运动与载荷信号中留下同步证据，电气噪声的相关性和频谱不同。', 'Real wheel hop leaves synchronous evidence in structural motion and load signals; electrical noise has different correlation and spectrum.'),
    q('ty-e', 'design', 3, '建立赛车轮胎模型时，最重要的覆盖变量组合是什么？', 'Which variable set is essential for a racing tyre model?', [['只用一个摩擦系数', 'One friction coefficient only'], ['载荷、滑移、外倾、温度、压力及联合滑移', 'Load, slip, camber, temperature, pressure and combined slip'], ['只用轮胎直径', 'Tyre diameter only']], 1, '轮胎是多变量非线性系统，单一 μ 无法支持平衡、热和控制设计。', 'The tyre is a multivariable nonlinear system; one μ cannot support balance, thermal and control design.'),
  ],
  brakes: [
    q('br-c', 'concept', 1, '为什么赛车制动系统需要前后双回路？', 'Why does a race car use independent front and rear brake circuits?', [['为了颜色不同', 'For different colours'], ['单一回路失效时仍保留另一回路的制动能力', 'To retain braking on the other circuit after one circuit fails'], ['为了提高电机转速', 'To raise motor speed']], 1, '双回路是关键失效容错，通常通过平衡杆连接两个主缸。', 'Dual circuits provide critical fault tolerance, commonly through a balance bar and two master cylinders.'),
    q('br-n', 'calculation', 2, '310 kg 赛车从 30 m/s 减速到 10 m/s，需要消散多少动能？', 'How much kinetic energy must a 310 kg car dissipate when slowing from 30 m/s to 10 m/s?', [['62 kJ', '62 kJ'], ['124 kJ', '124 kJ'], ['248 kJ', '248 kJ']], 1, 'E=½m(V1²−V2²)=0.5×310×800=124000 J。', 'E=½m(V1²−V2²)=0.5×310×800=124000 J.', '使用两个速度平方之差。', 'Use the difference of speed squares.'),
    q('br-s', 'scenario', 2, '重刹时后轮总是先锁，最安全的初步方向是什么？', 'The rear wheels always lock first under heavy braking. What is the safest initial direction?', [['增加前制动比例并验证动态轴荷与轮胎', 'Move bias forward and validate dynamic axle loads and tyres'], ['继续把平衡向后调', 'Move bias further rearward'], ['拆除前制动', 'Remove the front brakes']], 0, '后轮先锁会降低方向稳定性，应先恢复后轴裕量并确认并非左右故障或再生叠加。', 'Rear-first lock reduces directional stability; restore rear margin and confirm no side fault or regen overlap.'),
    q('br-d', 'diagnosis', 3, '踏板逐圈变长，但冷却后恢复且无可见泄漏，最可能优先排查什么？', 'Pedal travel grows each lap, recovers when cool and has no visible leak. What should be investigated first?', [['制动液沸腾、热回推和系统柔度', 'Fluid boiling, thermal knock-back and compliance'], ['尾翼涂装', 'Rear-wing paint'], ['GPS 地图', 'GPS map']], 0, '热相关恢复说明应检查液温、盘跳动、轴承间隙和软管/卡钳柔度。', 'Thermal recovery points to fluid temperature, disc runout, bearing play and hose/caliper compliance.'),
    q('br-e', 'design', 3, '制动盘设计为什么要分别评估单次和连续制动？', 'Why must brake-disc design assess single and repeated stops separately?', [['单次主要受热容量，连续制动还受散热稳态限制', 'A single stop is heat-capacity driven; repeated stops also depend on heat rejection'], ['两者完全相同', 'They are identical'], ['连续制动不产生热', 'Repeated braking creates no heat']], 0, '峰值温升与持续平衡是不同时间尺度，盘质量和冷却风道的作用也不同。', 'Peak temperature rise and sustained balance occur on different time scales, so disc mass and cooling play different roles.'),
  ],
  'front-suspension': [
    q('fs-c', 'concept', 1, '运动比 MR=弹簧位移/轮端位移时，轮端刚度与 MR 的关系是什么？', 'With MR=spring travel/wheel travel, how does wheel rate depend on MR?', [['kw=ks·MR²', 'kw=ks·MR²'], ['kw=ks/MR', 'kw=ks/MR'], ['kw 与 MR 无关', 'kw is independent of MR']], 0, '位移与力各引入一次杠杆关系，因此轮端刚度包含运动比平方。', 'Displacement and force each introduce a lever relation, producing the square of motion ratio.'),
    q('fs-n', 'calculation', 2, '弹簧刚度 80 N/mm、运动比 0.75，轮端刚度约是多少？', 'Spring rate is 80 N/mm and motion ratio is 0.75. What is wheel rate?', [['45 N/mm', '45 N/mm'], ['60 N/mm', '60 N/mm'], ['106.7 N/mm', '106.7 N/mm']], 0, 'kw=80×0.75²=45 N/mm。', 'kw=80×0.75²=45 N/mm.', '运动比要平方。', 'Square the motion ratio.'),
    q('fs-s', 'scenario', 2, '增加负外倾后高速弯更快，但直线制动距离变长，原因可能是什么？', 'More negative camber improves fast corners but lengthens straight braking distance. Why?', [['弯中接地改善，但直线时胎面接地更不均匀', 'Corner contact improves but straight-line footprint becomes less uniform'], ['电池容量自动下降', 'Battery capacity automatically falls'], ['车架质量消失', 'Chassis mass disappears']], 0, '外倾是弯道与直线接地的取舍，应结合侧倾和轮胎温度确定。', 'Camber trades corner and straight footprint and must be set with roll and tyre temperature.'),
    q('fs-d', 'diagnosis', 3, '静态前束正确，重刹时方向却不稳并出现左右轮滑移差，最应检查什么？', 'Static toe is correct, but heavy braking is unstable with side-to-side slip difference. What should be checked?', [['载荷下控制臂、拉杆、轴承和硬点的顺从前束', 'Compliance toe from control arms, tie rods, bearings and hardpoints under load'], ['只重新喷漆', 'Only repaint the car'], ['降低遥测采样率', 'Lower telemetry sample rate']], 0, '静态定位不能揭示制动力下的结构变形，应做带载 K&C 或等效测量。', 'Static alignment cannot reveal brake-load deformation; loaded K&C or an equivalent test is needed.'),
    q('fs-e', 'design', 3, '悬架硬点优化最合理的输入集合是什么？', 'What is the most appropriate input set for suspension hardpoint optimisation?', [['轮胎外倾需求、车高平台、转向几何、包装和载荷路径', 'Tyre camber needs, ride-height platform, steering geometry, packaging and load paths'], ['只看静态外观', 'Static appearance only'], ['只让控制臂最短', 'Only make arms shortest']], 0, '硬点同时定义运动学、结构力与包装，任何单指标优化都会转移问题。', 'Hardpoints define kinematics, structural force and packaging, so one-metric optimisation merely moves the problem.'),
  ],
  'rear-suspension': [
    q('rs-c', 'concept', 1, '增加后轴滚转刚度通常会怎样改变极限平衡？', 'How does increasing rear roll stiffness normally change limit balance?', [['提高后轴载荷差，通常让车辆更愿意旋转', 'Increase rear load difference and normally promote rotation'], ['消除所有载荷转移', 'Eliminate all load transfer'], ['只影响直线最高车速', 'Affect only straight-line top speed']], 0, '轮胎载荷敏感性使更大的后轴左右载荷差降低后轴总抓地，过量会导致突然过度转向。', 'Tyre load sensitivity makes greater rear side-to-side load difference reduce total rear grip; too much can create abrupt oversteer.'),
    q('rs-n', 'calculation', 2, '后弹簧 70 N/mm、运动比 0.8，轮端刚度约是多少？', 'Rear spring rate is 70 N/mm with motion ratio 0.8. What is wheel rate?', [['44.8 N/mm', '44.8 N/mm'], ['56 N/mm', '56 N/mm'], ['87.5 N/mm', '87.5 N/mm']], 0, 'kw=70×0.8²=44.8 N/mm。', 'kw=70×0.8²=44.8 N/mm.', 'kw=ks·MR²。', 'kw=ks·MR².'),
    q('rs-s', 'scenario', 2, '出弯内后轮卸载并空转，先采用哪种系统性方法？', 'The inside rear unloads and spins on corner exit. What is the first system-level approach?', [['协调后滚转刚度、差速锁止和扭矩斜率', 'Coordinate rear roll stiffness, differential locking and torque ramp'], ['只提高峰值电机电流', 'Only raise peak motor current'], ['减小前翼面积到零', 'Reduce front-wing area to zero']], 0, '问题同时涉及轮端载荷、扭矩分配和驱动瞬态，单独增加锁止可能损害过弯。', 'The issue combines wheel load, torque distribution and drive transient; adding lock alone may hurt mid-corner behaviour.'),
    q('rs-d', 'diagnosis', 3, '高速直线后轴漂移，低速定位正常，优先检查什么？', 'The rear wanders on fast straights while low-speed alignment is normal. What is the priority check?', [['下压力下的顺从前束、车高和底板平台', 'Compliance toe, ride height and floor platform under downforce'], ['驾驶员手套尺寸', 'Driver glove size'], ['静止时的电机颜色', 'Motor colour at rest']], 0, '速度相关问题可能来自气动载荷下的几何变形或平台失稳，静态定位无法证明高速状态。', 'A speed-dependent issue can come from geometry deformation or platform instability under aero load; static alignment does not prove the high-speed state.'),
    q('rs-e', 'design', 3, '抗蹲几何的正确理解是什么？', 'What is the correct interpretation of anti-squat geometry?', [['它改变力的传递路径和车身压缩，但不消除总载荷转移', 'It changes load path and body compression but does not remove total load transfer'], ['它免费增加轮胎法向载荷', 'It creates tyre normal load for free'], ['越高越好且无副作用', 'More is always better with no side effect']], 0, '过高抗蹲会增加连杆力、顶升和轮胎载荷突变，应结合路面与牵引优化。', 'Excessive anti-squat raises link force, jacking and abrupt tyre-load response and must be optimised with road compliance and traction.'),
  ],
  steering: [
    q('st-c', 'concept', 1, '理想阿克曼几何的低速目标是什么？', 'What is the low-speed purpose of ideal Ackermann geometry?', [['让内轮转角大于外轮以匹配不同转弯半径', 'Give the inner wheel more angle to match different turn radii'], ['让两轮完全同角', 'Make both wheels exactly equal'], ['让后轮主动转向', 'Actively steer the rear wheels']], 0, '内轮走更小半径，需要更大转角；高速最优还受轮胎侧偏与载荷影响。', 'The inner wheel follows a smaller radius and needs more angle; high-speed optimum also depends on tyre slip and load.'),
    q('st-n', 'calculation', 2, '方向盘转动 270°，平均前轮转动 45°，转向比是多少？', 'The steering wheel turns 270° while the average road-wheel angle is 45°. What is steering ratio?', [['3:1', '3:1'], ['6:1', '6:1'], ['12:1', '12:1']], 1, 'is=270/45=6:1。', 'is=270/45=6:1.', '方向盘角除以车轮角。', 'Divide steering-wheel angle by road-wheel angle.'),
    q('st-s', 'scenario', 2, '减小转向比后车手反映动作更快但方向盘更重、更敏感，这是否合理？', 'After making the steering ratio quicker, the driver reports faster response but heavier and more sensitive steering. Is this reasonable?', [['合理，需要在手部动作、力矩和稳定性间折中', 'Yes; hand motion, torque and stability must be traded'], ['不合理，转向比不影响任何感觉', 'No; ratio changes nothing'], ['说明电池一定故障', 'It proves a battery fault']], 0, '更快的几何传动比用更少方向盘角产生相同轮角，通常提高驾驶员所需力矩和输入敏感度。', 'A quicker ratio gives the same road-wheel angle from less hand motion, normally raising required torque and sensitivity.'),
    q('st-d', 'diagnosis', 3, '方向盘中心在几圈后改变，第一安全动作是什么？', 'Steering centre changes after several laps. What is the first safety action?', [['停驶并检查快拆、花键、拉杆锁紧和齿条安装的机械滑移', 'Stop and inspect quick release, splines, tie-rod locks and rack mount for mechanical slip'], ['用软件偏置方向盘角', 'Apply a software steering-angle offset'], ['提高车速确认', 'Drive faster to confirm']], 0, '任何转向连接滑移都可能发展成失去转向，必须先按机械安全故障处理。', 'Any steering-joint slip can progress to loss of steering and must first be treated as a mechanical safety fault.'),
    q('st-e', 'design', 3, '转向拉杆位置为什么要与控制臂瞬心共同设计？', 'Why must tie-rod location be designed with control-arm instant centres?', [['它们共同决定悬架跳动时的前束变化', 'Together they determine toe change with suspension travel'], ['为了改变电池 SOC', 'To change battery SOC'], ['只为外观平行', 'Only for visual parallelism']], 0, '拉杆与轮端运动弧不匹配会产生 bump steer，形成非驾驶员指令的偏航输入。', 'Mismatch between tie-rod and wheel motion arcs creates bump steer, an uncommanded yaw input.'),
  ],
  battery: [
    q('ba-c', 'concept', 1, '预充电路的作用是什么？', 'What is the purpose of the precharge circuit?', [['限制直流母线电容充电浪涌', 'Limit inrush while charging DC-link capacitance'], ['提高轮胎压力', 'Increase tyre pressure'], ['改变悬架外倾', 'Change suspension camber']], 0, '预充通过电阻让母线电压受控上升，避免主接触器带大电压差闭合。', 'Precharge raises bus voltage through a resistor so the main contactor does not close across a large voltage difference.'),
    q('ba-n', 'calculation', 2, '电池以 200 A 放电，等效内阻 40 mΩ，焦耳热约是多少？', 'A battery discharges at 200 A with 40 mΩ equivalent resistance. What is Joule heat?', [['0.8 kW', '0.8 kW'], ['1.6 kW', '1.6 kW'], ['8 kW', '8 kW']], 1, 'P=I²R=200²×0.04=1600 W。', 'P=I²R=200²×0.04=1600 W.', '先把 mΩ 换成 Ω。', 'Convert mΩ to Ω first.'),
    q('ba-s', 'scenario', 2, '低 SOC 时相同踏板请求得到更小功率，最合理的原因是什么？', 'At low SOC the same pedal request gives less power. What is the most reasonable reason?', [['端电压下降和单体欠压限值触发降额', 'Voltage sag and cell-undervoltage limits trigger derating'], ['后翼角度自动改变', 'Rear-wing angle changes automatically'], ['轴距缩短', 'Wheelbase becomes shorter']], 0, '低 SOC 下开路电压更低，内阻压降更容易让最弱单体触及安全下限。', 'At low SOC open-circuit voltage is lower and resistance sag more easily drives the weakest cell to its safety floor.'),
    q('ba-d', 'diagnosis', 3, '只有一个串联组在大电流时欠压，静置又正常，应如何诊断？', 'Only one series group undervolts at high current but rests normally. How should it be diagnosed?', [['比较动态压降、连接电阻、采样线和温度', 'Compare dynamic sag, joint resistance, sense wiring and temperature'], ['直接短接该组', 'Short the group'], ['提高欠压阈值容忍', 'Relax undervoltage threshold']], 0, '真实弱电芯、高阻连接和采样错误症状相似，必须用受控脉冲和独立测量区分。', 'A weak cell, resistive joint and sensing fault look similar and need controlled pulses and independent measurement to separate.'),
    q('ba-e', 'design', 3, '确定电池串并联拓扑时哪组输入最完整？', 'Which input set is most complete for battery series/parallel topology?', [['耐久能量、峰值功率、电压边界、热、质量和安全封装', 'Endurance energy, peak power, voltage limits, thermal, mass and safe enclosure'], ['只看额定 Ah', 'Rated Ah only'], ['只看最高开路电压', 'Maximum open-circuit voltage only']], 0, '串并联选择同时决定电压、电流、热和弱电芯风险，必须基于完整任务循环。', 'Series/parallel choice jointly sets voltage, current, heat and weak-cell risk and must use the full duty cycle.'),
  ],
  inverter: [
    q('iv-c', 'concept', 1, 'FOC 中 q 轴电流主要控制什么？', 'In FOC, what does q-axis current primarily control?', [['电磁转矩', 'Electromagnetic torque'], ['轮胎胎压', 'Tyre pressure'], ['车架扭转刚度', 'Chassis torsional stiffness']], 0, '在常见永磁同步电机控制中，q 轴电流是主要转矩分量，d 轴用于磁通/弱磁。', 'In common PMSM control, q-axis current is the main torque component while d-axis controls flux/field weakening.'),
    q('iv-n', 'calculation', 2, '逆变器向电机输出 60 kW，损耗 2 kW，效率约是多少？', 'An inverter delivers 60 kW with 2 kW loss. What is efficiency?', [['90.9%', '90.9%'], ['96.8%', '96.8%'], ['98.0%', '98.0%']], 1, 'η=60/(60+2)=96.77%。', 'η=60/(60+2)=96.77%.', '输入功率等于输出加损耗。', 'Input power equals output plus loss.'),
    q('iv-s', 'scenario', 2, '提高 PWM 频率后电流更平滑，但模块温度升高，原因是什么？', 'After increasing PWM frequency current is smoother but module temperature rises. Why?', [['单位时间开关次数增加，开关损耗上升', 'More switching events per second raise switching loss'], ['轮胎载荷变为零', 'Tyre load becomes zero'], ['制动盘吸热减少', 'Brake-disc heat falls']], 0, '更高频率降低纹波，却增加开通和关断能量的累计。', 'Higher frequency reduces ripple but accumulates more turn-on and turn-off energy.'),
    q('iv-d', 'diagnosis', 3, '高速弱磁区出现转矩脉动，优先检查哪组因素？', 'Torque ripple appears in high-speed field weakening. What should be checked first?', [['转子角度、控制延迟、电压饱和和电流环带宽', 'Rotor angle, control delay, voltage saturation and current-loop bandwidth'], ['尾翼端板颜色', 'Rear-wing endplate colour'], ['驾驶员体重标签', 'Driver weight label']], 0, '弱磁区电压裕量小，对角度和相位误差敏感，单纯滤波可能进一步增加延迟。', 'Field weakening has little voltage margin and is sensitive to angle and phase errors; filtering alone can add more delay.'),
    q('iv-e', 'design', 3, '逆变器冷却为什么要按绝对损耗而不是只看效率百分比？', 'Why must inverter cooling use absolute loss rather than efficiency percentage alone?', [['高功率下 98% 仍可能产生数千瓦热', 'At high power even 98% can mean kilowatts of heat'], ['效率与热完全无关', 'Efficiency is unrelated to heat'], ['百分比总是等于温度', 'Percentage always equals temperature']], 0, '热系统需要排出的正是损耗瓦数，且还要考虑时间和热阻。', 'The thermal system must reject loss watts, with duration and thermal resistance included.'),
  ],
  motor: [
    q('mt-c', 'concept', 1, '牵引电机为什么在基速以上转矩通常下降？', 'Why does traction-motor torque normally fall above base speed?', [['进入电压限制并需要弱磁', 'Voltage limit requires field weakening'], ['轮胎直径变为零', 'Tyre diameter becomes zero'], ['车架突然变软', 'Chassis suddenly softens']], 0, '母线电压限制反电动势，弱磁扩大转速范围但减少可用转矩。', 'DC voltage limits back-EMF; field weakening extends speed range at reduced torque.'),
    q('mt-n', 'calculation', 2, '电机输出 120 N·m、6000 rpm，机械功率约多少？', 'A motor produces 120 N·m at 6000 rpm. Approximately what is mechanical power?', [['37.7 kW', '37.7 kW'], ['75.4 kW', '75.4 kW'], ['120 kW', '120 kW']], 1, 'P=T·2πn/60=120×2π×6000/60≈75.4 kW。', 'P=T·2πn/60=120×2π×6000/60≈75.4 kW.', '把 rpm 转为 rad/s。', 'Convert rpm to rad/s.'),
    q('mt-s', 'scenario', 2, '增大减速比后低速加速提高但直道末端提前限速，说明什么？', 'A larger ratio improves low-speed acceleration but reaches a speed limit early on the straight. What does this show?', [['减速比在轮上力与最高车速之间取舍', 'Gear ratio trades wheel force against top speed'], ['减速比只影响质量', 'Ratio affects only mass'], ['电机功率无限', 'Motor power is unlimited']], 0, '更大速比放大转矩，也让电机在相同车速转得更快。', 'A larger ratio multiplies torque and also makes the motor spin faster at a given road speed.'),
    q('mt-d', 'diagnosis', 3, '绕组温度正常但轴承温度与振动持续上升，应优先做什么？', 'Winding temperature is normal but bearing temperature and vibration keep rising. What is the priority?', [['限制转速并分析对中、预载、润滑与电蚀', 'Limit speed and inspect alignment, preload, lubrication and electrical erosion'], ['提高相电流', 'Raise phase current'], ['忽略直到失效', 'Ignore until failure']], 0, '这是机械健康信号，继续高速可能导致转子/轴承严重故障。', 'This is a mechanical-health signal; continued high speed can cause major rotor/bearing failure.'),
    q('mt-e', 'design', 3, '电机选型为什么要使用整圈工作点分布？', 'Why should motor selection use the full-lap operating-point distribution?', [['峰值与连续热、效率、弱磁和能量需求不同', 'Peak and continuous thermal, efficiency, field-weakening and energy needs differ'], ['一个峰值代表全部工况', 'One peak represents all conditions'], ['圈速与电机无关', 'Lap time is unrelated to motor']], 0, '电机大部分时间不在峰值点，任务循环决定温度、能耗和真正可持续性能。', 'The motor spends most time away from one peak; the duty cycle sets temperature, energy and sustainable performance.'),
  ],
  differential: [
    q('df-c', 'concept', 1, '开放式差速器在内轮低载时为什么限制牵引？', 'Why does an open differential limit traction when the inside wheel is lightly loaded?', [['两侧扭矩近似相等，低附着侧限制共同扭矩', 'Side torques are nearly equal, so the low-grip side limits both'], ['它强制两轮同速', 'It forces equal wheel speed'], ['它关闭电池', 'It shuts down the battery']], 0, '开放式允许速度差但不能主动把更多扭矩给高附着外轮。', 'An open unit allows speed difference but cannot deliberately send more torque to the higher-grip outside wheel.'),
    q('df-n', 'calculation', 2, '左右轮角速度分别 80 和 100 rad/s，对称差速器壳体角速度是多少？', 'Left and right wheel speeds are 80 and 100 rad/s. What is symmetric differential carrier speed?', [['80 rad/s', '80 rad/s'], ['90 rad/s', '90 rad/s'], ['100 rad/s', '100 rad/s']], 1, '壳体速度是两侧平均值：(80+100)/2=90。', 'Carrier speed is the side average: (80+100)/2=90.', 'ωc=(ωL+ωR)/2。', 'ωc=(ωL+ωR)/2.'),
    q('df-s', 'scenario', 2, '提高锁止后出弯牵引改善，但中弯推头加重，如何处理？', 'More locking improves exit traction but adds mid-corner understeer. What should be done?', [['分开标定预载、加速锁止与扭矩斜率', 'Calibrate preload, power locking and torque ramp separately'], ['继续把所有工况锁死', 'Fully lock all phases'], ['拆除后悬架', 'Remove rear suspension']], 0, '差速作用随弯道阶段不同，应避免用一个锁止量同时解决所有阶段。', 'Differential needs differ by corner phase; one locking value should not be forced onto every phase.'),
    q('df-d', 'diagnosis', 3, '差速特性只在热态明显改变，优先检查什么？', 'Differential behaviour changes only when hot. What should be checked first?', [['油温、摩擦片磨耗、预载与润滑黏度', 'Oil temperature, plate wear, preload and lubricant viscosity'], ['前翼面积', 'Front-wing area'], ['GPS 卫星数量', 'GPS satellite count']], 0, '摩擦式限滑的摩擦系数和预载会随温度、磨耗与油液变化。', 'Plate-type LSD friction and preload vary with temperature, wear and lubricant.'),
    q('df-e', 'design', 3, '扭矩矢量控制必须受什么约束？', 'What must constrain torque-vectoring control?', [['总功率、左右轮摩擦圆、偏航稳定与变化率', 'Total power, side tyre friction ellipses, yaw stability and rate of change'], ['只受显示屏亮度', 'Dashboard brightness only'], ['没有任何约束', 'No constraints']], 0, '左右力差能制造偏航，但不能超过轮胎与动力能力，也不能用不可预测的突变。', 'Left/right force difference creates yaw but cannot exceed tyre or power capability or change unpredictably.'),
  ],
  cooling: [
    q('co-c', 'concept', 1, '为什么提高冷却液流量不一定解决所有过热？', 'Why does increasing coolant flow not solve every overheat?', [['瓶颈可能在界面或散热器空气侧', 'The bottleneck may be interface or radiator air side'], ['流量与换热永远无关', 'Flow never affects heat transfer'], ['温度只是软件数字', 'Temperature is only a software number']], 0, '总热阻由多个串联环节组成，降低一个已很小的液侧热阻收益有限。', 'Total thermal resistance has several series elements; reducing an already-small coolant-side term gives little benefit.'),
    q('co-n', 'calculation', 2, '质量流量 0.15 kg/s、比热 4000 J/(kg·K)、温升 10 K，带走多少热量？', 'Coolant mass flow is 0.15 kg/s, cp is 4000 J/(kg·K), and rise is 10 K. How much heat is carried?', [['0.6 kW', '0.6 kW'], ['6 kW', '6 kW'], ['60 kW', '60 kW']], 1, 'Q̇=ṁcpΔT=0.15×4000×10=6000 W。', 'Q̇=ṁcpΔT=0.15×4000×10=6000 W.', 'Q̇=ṁcpΔT。', 'Q̇=ṁcpΔT.'),
    q('co-s', 'scenario', 2, '低速高负荷过热、高速正常，最可能优先改善什么？', 'The car overheats at low speed/high load but is normal at high speed. What is the first likely improvement?', [['散热器风量、风扇和风道密封', 'Radiator airflow, fan and duct sealing'], ['提高转向比', 'Increase steering ratio'], ['减少轮速采样率', 'Reduce wheel-speed sample rate']], 0, '高速行驶提供更多空气，低速差异首先指向空气侧能力。', 'Vehicle speed supplies more air, so a low-speed-only difference points first to air-side capacity.'),
    q('co-d', 'diagnosis', 3, '泵速和电流都高，但流量低且有噪声，最先排查什么？', 'Pump speed and current are high, but flow is low and noisy. What should be checked first?', [['气锁、液位、入口条件、堵塞和气蚀', 'Air lock, level, inlet condition, blockage and cavitation'], ['更换所有制动片', 'Replace all brake pads'], ['增加尾翼攻角', 'Increase rear-wing angle']], 0, '高转速低流量伴噪声是气锁/气蚀或高阻力的典型证据，继续加速会损伤泵。', 'High speed with low noisy flow indicates air/cavitation or restriction; more speed can damage the pump.'),
    q('co-e', 'design', 3, '泵选型为什么必须使用系统曲线？', 'Why must pump selection use a system curve?', [['实际流量由泵压升与管路压降交点决定', 'Actual flow is the intersection of pump head and system pressure drop'], ['额定最大流量在任何管路都不变', 'Rated maximum flow is unchanged in every circuit'], ['泵不消耗功率', 'Pumps use no power']], 0, '只看零压最大流量会高估整车回路中的工作点。', 'Looking only at zero-head maximum flow overestimates the installed operating point.'),
  ],
  ecu: [
    q('ec-c', 'concept', 1, '扭矩仲裁的基本原则是什么？', 'What is the basic torque-arbitration principle?', [['采用驾驶员、电池、电机、轮胎和安全边界中最严格允许值', 'Use the tightest allowed driver, battery, motor, tyre and safety boundary'], ['永远输出驾驶员请求的 100%', 'Always output 100% driver request'], ['随机选择一个限值', 'Choose a random limit']], 0, '最终扭矩必须同时满足全部子系统能力，并记录当前限制源。', 'Final torque must satisfy every subsystem capability and identify the active limiting source.'),
    q('ec-n', 'calculation', 2, '周期 10 ms 的任务最坏执行 2 ms，周期 20 ms 的任务最坏执行 3 ms，总利用率是多少？', 'A 10 ms task executes for 2 ms worst-case and a 20 ms task for 3 ms. What is total utilisation?', [['25%', '25%'], ['35%', '35%'], ['50%', '50%']], 1, 'U=2/10+3/20=0.2+0.15=35%。', 'U=2/10+3/20=0.2+0.15=35%.', '相加 Ci/Ti。', 'Sum Ci/Ti.'),
    q('ec-s', 'scenario', 2, '温度接近降额阈值时扭矩每秒来回跳变，怎样改进？', 'Torque chatters each second near a thermal derate threshold. How should it be improved?', [['连续限值、合适滞回和受控恢复斜率', 'Continuous limit, suitable hysteresis and controlled recovery ramp'], ['删除过温保护', 'Delete overtemperature protection'], ['扩大传感噪声', 'Increase sensor noise']], 0, '既要避免边界抖动，也要保留快速越界保护，不能简单取消安全功能。', 'Boundary chatter must be removed while retaining rapid out-of-bounds protection, not by deleting safety.'),
    q('ec-d', 'diagnosis', 3, '加速中偶发扭矩瞬断，多个报警随后同时出现，根因分析应从哪里开始？', 'An intermittent torque cut produces many subsequent alarms. Where should root-cause analysis start?', [['按时间查找第一个触发事件和限制源', 'Find the first triggering event and limiting source in time order'], ['只看最后一个报警', 'Look only at the final alarm'], ['清空日志继续跑', 'Erase logs and continue']], 0, '连锁报警会掩盖根因，首次事件通常能定位供电、通信、合理性或任务超时。', 'Cascading alarms hide root cause; the first event often locates supply, communication, plausibility or task overrun.'),
    q('ec-e', 'design', 3, '安全状态机为什么要显式定义合法转换？', 'Why must a safety state machine explicitly define legal transitions?', [['避免隐含状态，保证正常和故障响应可预测、可测试', 'Avoid hidden states and make normal/fault responses predictable and testable'], ['让代码行数更多', 'Only to add code'], ['为了提高空气动力', 'To improve aerodynamics']], 0, '关机、预充、待命、可行驶、降额和锁存故障之间必须只有清晰可验证的路径。', 'Off, precharge, standby, drive, derate and latched fault need clear verifiable paths.'),
  ],
  sensors: [
    q('se-c', 'concept', 1, '高分辨率是否等于高准确度？', 'Does high resolution equal high accuracy?', [['是，二者完全相同', 'Yes, they are identical'], ['否，分辨率是最小可辨变化，准确度是接近真值程度', 'No; resolution is smallest discernible change, accuracy is closeness to truth'], ['只有温度传感器不同', 'Only temperature sensors differ']], 1, '传感器可以显示很多小数位但存在大偏置，因此必须标定并给出不确定度。', 'A sensor can show many digits yet carry large bias, so calibration and uncertainty are required.'),
    q('se-n', 'calculation', 2, '要测量最高 80 Hz 的有效信号，下列最低哪个采样率满足奈奎斯特条件？', 'To measure useful content up to 80 Hz, which is the lowest listed sample rate that satisfies the Nyquist condition?', [['80 Hz', '80 Hz'], ['160 Hz', '160 Hz'], ['200 Hz', '200 Hz']], 2, 'fs 必须严格大于 2×80=160 Hz，因此选项中 200 Hz 是最低合格值；工程上还要为抗混叠滤波过渡带留余量。', 'fs must be strictly greater than 2×80=160 Hz, so 200 Hz is the lowest valid option; practical systems also need margin for the anti-alias filter transition band.', 'fs > 2fmax，不能等于 2fmax。', 'fs > 2fmax; equality is not sufficient.'),
    q('se-s', 'scenario', 2, '制动压力看起来比减速度晚 20 ms，能否直接认定液压延迟？', 'Brake pressure appears 20 ms later than deceleration. Can hydraulic delay be concluded immediately?', [['可以，曲线顺序永远正确', 'Yes, plot order is always correct'], ['不可以，先验证设备时间同步、缓存、滤波和共同触发', 'No; first verify clock sync, buffering, filtering and shared trigger'], ['只需增加胎压', 'Only increase tyre pressure']], 1, '跨记录器时间偏移能制造虚假先后关系，因果分析前必须校准时间轴。', 'Cross-logger time offset can create false ordering; the time axis must be calibrated before causal analysis.'),
    q('se-d', 'diagnosis', 3, '一个信号曲线非常平滑，却在车辆静止时随转向变化，正确判断是什么？', 'A signal is very smooth but changes with steering while the car is stationary. What is the right interpretation?', [['平滑证明一定真实', 'Smoothness proves it is true'], ['检查通道映射、串扰、接地、单位和解码', 'Check channel mapping, crosstalk, grounding, units and decoding'], ['立刻修改车辆几何', 'Immediately change vehicle geometry']], 1, '物理不可能性比曲线美观更重要，应做端到端已知输入验证。', 'Physical impossibility outweighs a pretty trace; perform an end-to-end known-input test.'),
    q('se-e', 'design', 3, '一个完整测量通道规范至少应包含什么？', 'What should a complete measurement-channel specification include?', [['量程、带宽、采样率、单位、标定、不确定度、时间源和用途', 'Range, bandwidth, sample rate, unit, calibration, uncertainty, time source and purpose'], ['只有通道名称', 'Channel name only'], ['只有线束颜色', 'Harness colour only']], 0, '没有这些元数据，数据无法判断是否超量程、混叠、错单位或不适合某项分析。', 'Without this metadata data cannot be assessed for range, aliasing, unit correctness or fitness for an analysis.'),
  ],
}
